project-hatohol/hatohol

server/src/DBAgent.cc, server/src/DBAgent.h, server/src/DBAgentMySQL.cc, server/src/DBAgentMySQL.h, server/src/DBAgentSQLite3.cc, server/src/DBAgentSQLite3.h, server/test/DBAgentTest.cc, server/test/DBAgentTest.h, server/test/testDBAgentMySQL.cc
Because an inappropriate format specifier "PRId64" is used for uint64_t, a value which is bigger
than max int64 becomes zero on updating it on MySQL.
(DBAgentSQLite3 uses PRId64 intentionally because it doesn't have unsigned type.)
Although it's a small bug, we have to fix many codes since it's a static function and used from
some other static functions in DBAgentSQLite3.
issue #850
=> [server] Fix incorrect updating of BIGUINT values

server/test/testHatoholArmPluginGate.cc
loadTestDBServer() is called in the previous function loadTestDBTablesConfig().
So it is called twice in mistake.
=> [testHatoholArmPluginGate] Remove a unnecessary setup.

server/common/NamedPipe.cc, server/common/Utils.cc, server/mlpl/test/testLogger.cc, server/src/ActionManager.cc, server/src/FaceRest.cc, server/src/main.cc, server/test/HttpServerStub.cc, server/test/testActionManager.cc
https://developer.gnome.org/glib/stable/glib-String-Utility-Functions.html#g-strerror
=> Use g_strerror() instead of strerror() to improve portability

hatohol.spec.in
Otherwise, we get "unrecognized service" error when uninstalling
server package.
=> [server] spec: Stop service before uninstalling files.

server/src/ConfigManager.cc
=> [server] ConfigManager: --load-old-events option was not applied.

server/src/DBTablesMonitoring.cc
In Hatohol DB has tens of millions of events data (occured 40 events / sec), ajax_events show events too slow.
I and @yoshfuji san investigate this problem and found cause of this issue.
As a result of investigation, the cause did not create index for events.
So, I think we need to add new index for events.
Related to #158
Fix of #916
=> [DBTablesMonitoring] Add new DB index for events: EventsTimeSequence

client/static/js/hatohol_connector.js
This commit fixes issue #938.
Because the "request" property of HatoholConnector is stored to
an inappropriate object, it can't recognize the HTTP method
correctly on a certain condition.
=> [HatoholConnector] Add a missing local variable "self"

server/common/ZabbixAPI.cc
I found a mistake in #934.
We should use ```addTrue()``` or ```addFalse()``` function when we set value of JSON as boolean value.
=> [ZabbixAPI] Use addTrue() function instead of add() function.

server/src/DBTablesMonitoring.cc
I'm sorry, I didn't noticed.... :cold_sweat: 
```log
entend_info ->
extend_info
^
```
=> [server][DBTablesMonitoring] Fix a typo column name

server/src/FaceRest.h, server/src/RestResourceHost.cc, server/src/RestResourceHost.h, server/test/DBTablesTest.cc, server/test/testFaceRestHost.cc
Contains:
* deliver ~~`extendedInfo`~~ `expandedDescription` column information to hatohol client
* Add ~~`extendedIinfo`~~ `expandedDescription` assertion into FaceRestHost
=> [server][Zabbix] Zabbix macro replacement face rest

server/common/ZabbixAPI.cc, server/common/ZabbixAPI.h, server/src/ArmZabbixAPI.cc, server/src/ArmZabbixAPI.h, server/test/testArmZabbixAPI.cc
I've remove unused `items` argument from functions which are getting expanded information from Zabbix.
=> [server][Zabbix] Zabbix macro replacement adjust argument

client/static/css/hatohol.css, client/static/js/history_view.js
* Remove redundant properties of HistoryView ("endTime" and "timeSpan") because the "timeRange" object has same information
* Replace the word "refresh" with "reload" to unify them
* Unify calling $.plot.dateGenerator()
=> Clean up history view

server/src/DBAgent.cc, server/src/DBAgent.h, server/src/DBAgentSQLite3.cc, server/src/DBAgentSQLite3.h, server/test/DBAgentTest.cc, server/test/DBAgentTest.h, server/test/testDBAgentMySQL.cc, server/test/testDBAgentSQLite3.cc
When a combination of columns for an index is changed,
DBAgent tries to create the new one. However, it fals due
to existence of the previous one.
This patch removed the existing index with the same name as
the one that will be created before the creation.
=> [DBAgent] Fix the problem in which updating an index fails.

server/src/DBTablesUser.cc
Without this patch, the following warning is shown.
DBTablesUser.cc:320:26: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
StringUtils::sprintf("%s=%"FMT_OPPRVLG,
=> [DBTablesUser] Suppress a warning when using C++11 compiler.

server/src/AMQPMessageHandler.h
The keyword can be used only for override method.
But it had been used for a normal method.
=> [AMQPMessageHandler] Remove an wrong override keyword.

client/viewer/userconfig.py
mimetype is depreated.  Use content_type instead.
Otherwise, we get following noisy errors:
| [:error] [pid XXX] /usr/lib/python2.7/site-packages/django/http/response.py:xxx: DeprecationWarning: Using mimetype keyword argument is deprecated, use content_type instead
| [:error] [pid XXX]   super(HttpResponse, self).__init__(*args, **kwargs)
Note that other callers already use content_type. index_core is the
last one.
Closes: #985 
=> [web] userconfig: Use content_type instead of deprecated mimetype.

client/viewer/userconfig.py
We see tons of following message in apache error_log:
| [:error] [pid xxx] A logger: viewer.userconfig has been created
This is annoying for ordinal users.
Drop the level from INFO to DEBUG.
Closes: #987
=> [web] userconfig: Change log level of starting userconfig from INFO to DEBUG.

client/hatohol/settings.py
Info nor debug logs should not be written to stderr by default,
especially if the frontend web is running with apache.
Otherwise, such log messages are recorded in error_log.
=> [web] hatohol/settings: Do not emit DEBUG/INFO logs to console by default.

server/test/testHapProcessStandard.cc
A GLibMain loop instance is wrongly used by two threads. So the
unexpected behavior has happened.
=> [testHapProcessStandard] Fix a race that sometimes makes tests fail.

client/hatohol/settings.py
I found these line when use pep8 command to check pep8 style.
```
hatohol/client/hatohol $ pep8 *.py
hatohol_def.py:155:1: W391 blank line at end of file
settings.py:104:5: E265 block comment should start with '# '
settings.py:114:5: E265 block comment should start with '# '
settings.py:139:5: E265 block comment should start with '# '
settings.py:140:5: E265 block comment should start with '# '
settings.py:141:5: E265 block comment should start with '# '
settings.py:142:5: E265 block comment should start with '# '
settings.py:143:5: E265 block comment should start with '# '
```
=> [Client][Python] Add space after '#'.

.gitignore, configure.ac, server/README.md, server/tools/hatohol-db-initiator, server/tools/hatohol-db-initiator.in
A part of works related to #672.
* `hatohol-db-initiator` start to use `hatohol.conf` settings info.
* After this pull request is merged, `hatohol-db-initiator` requires command line arguments as follows:
Before:
```bash
$ hatohol-db-initiator db_name db_user db_password
```
After:
Before creating hatohol database:
```bash
$ hatohol-db-initiator --db_user root --db_password rootpass
```
After creating hatohol database:
```bash
$ hatohol-db-initiator
```
`db_name`, `db_user` and `db_password` are read from `hatohol.conf` by default.
=> [server][tools] hatohol-db-initiator starts to use hatohol.conf

client/static/js/events_view.js, client/test/browser/test_events_view.js
Because users may misunderstand them as bad events.
=> [EventsView] Don't colorize severity labels of good events

server/src/GateJSONEventMessage.cc, server/src/GateJSONEventMessage.h, server/src/HatoholArmPluginGateJSON.cc, server/test/testGateJSONEventMessage.cc
It implements a request at #1009.
New HAPI JSON format:
```text
{
"type": "event",
"body": {
"id": ${Event ID as an integer},
"timestamp": ${Event occurred time as UNIX time in float or ISO 8601 format string},
"hostName": "${Host name where event is occurred as string}",
"content": "${Event detail as string}",
"severity": "${Severity of the event (optional) (default: unknown)}",
"type": "${Type of the event (optional) (default: bad)}"
}
}
```
Optional `$.body.type` parameter is added. Available values are `good`, `bad` (default) and `unknown`. They are mapped to `EVENT_TYPE_GOOD`, `EVENT_TYPE_BAD` and `EVENT_TYPE_UNKNOWN`.
=> HAPI-JSON supports event type

client/static/css/zabbix.css
トリガーの概要のwarningの色を暗い黄色から明るい黄色（Pastel yellow）に変更しました。
=> [Issue 208] Color of warning in overview:trigger is pastel yellow

server/src/ArmNagiosNDOUtils.cc
=> Add the process of setting ”validity” to host registration of NagiosNDOUtils.

server/tools/hatohol-db-initiator.in
Current implementation cannot be used when the config. file is
not correctly installed. However, mainly developers sometimes
want to use this script w/o installation. This patch enables it.
As for the DB user name and the password for Hatohol server
the default values of the previous version (user: hatohol,
password: hatohol), is automatically used.
i.e. The user can omit --hatohol-db-user and --hatohol-db-password.
=> [hatohol-db-initiator] Add an option to be carried out w/o config. file.

server/src/DBHatohol.cc, server/src/DBTables.cc, server/src/DBTables.h, server/src/DBTablesAction.cc, server/src/DBTablesAction.h, server/src/DBTablesConfig.cc, server/src/DBTablesConfig.h, server/src/DBTablesHost.cc, server/src/DBTablesHost.h, server/src/DBTablesMonitoring.cc, server/src/DBTablesMonitoring.h, server/src/DBTablesUser.cc, server/src/DBTablesUser.h, server/test/testDBTables.cc
These patches add a mechanism to check DBTables's major versions.
And if one of the major versions changes, it throws an exception. As a
result, hatohol server stop at the boot.
=> Db major version

server/src/FaceRestPrivate.h
As a side effect, getParamWithErrorReply() can accept std::string
as a template paramter.
=> [FaceRestPrivate] Remove duplicated and similar lines.

server/src/DBTermCodec.cc, server/src/DBTermCodec.h, server/src/FaceRestPrivate.h, server/test/testDBTermCodec.cc
Different from the previous one #1024, this pull request only contains a fix of DBTermCodec.
The way to provide C-style string will be proposed in another pull request.
=> Dbterm codec ver up 2

server/src/DBTermCStringProvider.cc, server/src/DBTermCStringProvider.h, server/src/Makefile.am, server/test/Makefile.am, server/test/testDBTermCStringProvider.cc
This class provides a method that returns a C-style string (const char *).
This is covenient to be used in conjunction with printf families
to make an SQL statement.
For example,
[Previously]
StringUtils::sprintf("column=%s", dbTermCodec.enc(value).c_str());
[New]
StringUtils::sprintf("column=%s", dbTermProvider(value));
=> [DBTermCStringProvider] Add a new class.

client/static/css/hatohol.css, client/static/js/hatohol_monitoring_view.js, client/static/js/history_view.js, client/static/js/utils.js, client/test/browser/index.html, client/test/browser/test_history_view.js, client/viewer/base_ajax.html, client/viewer/history_ajax.html
You can choose items to plot onto a graph by a dialog.
The dialog can be open by pressing the gear button on a history page.
It will be opened automatically if the page has no item
(open http://url.of.hatohol/ajax_history without query parameters).
Unfortunately there is no way to save the configuration yet.
And also there is no way to customize other settings (e.g. axes parameters).
I'm now working on them.
=> [Graph] Add UI for selecting items

server/src/HostResourceQueryOption.cc, server/src/HostResourceQueryOption.h, server/test/Makefile.am, server/test/TestHostResourceQueryOption.cc, server/test/TestHostResourceQueryOption.h, server/test/testHostResourceQueryOption.cc
Generating a part of an SQL string depends on the DB being used.
So direct reference of the DBTermCodec instance defind statically
is not undesirable.
=> [HostResourceQueryOption] Use getDBTermCodec().

client/conf/locale/ja/LC_MESSAGES/djangojs.po, server/common/HatoholError.cc, server/common/HatoholError.h, server/common/MonitoringServerInfo.cc, server/common/MonitoringServerInfo.h, server/src/DBTablesConfig.cc, server/src/DBTablesConfig.h, server/test/testDBTablesConfig.cc
監視サーバ設定でポーリング間隔とリトライ間隔のチェックを行うようにしました。
それぞれの有効範囲は以下の通りです。
ポーリング間隔（秒）: 1～31,622,400(366日)
リトライ間隔（秒）: 1～2,678,400(31日)
=> [Issue 595] Add 'Polling interval' and 'Retry interval' to validation

client/hatohol/forwardview.py, client/static/js/hatohol_connector.js, client/static/js/hatohol_reply_parser.js, server/src/FaceRest.cc, server/src/FaceRestPrivate.h, server/test/FaceRestTestUtils.cc, server/test/FaceRestTestUtils.h, server/test/testFaceRestUser.cc
This pull request contains *experimental feature* for improving testability, as follows:
* `FaceRest::ResourceHandler::replyJSONData` and `FaceRest::ResourceHandler::replyError` can accept arbitrary HTTP status code such as **401 (Unauthorized)**, **403 (Forbidden)**, ... and so on.
* Default HTTP status is **200 (OK)**.
* Hatohol client can handle non-200 response from Hatohol server.
* Try to send response which is non-200 status code in user authentication.
Here is failing user authentication senario:
When failing to user authenticate, Hatohol server send **401 (Unauthorized)** response to Hatohol client(WebUI). Hatohol client just passes through Hatohol server response. Nevertheless non-200 status response from Hatohol server.
Finally, user's browser receives **401 (Unauthorized)** …
=> [Experimental][client][server] set arbitrary http status code

server/src/DBTablesMonitoring.cc, server/src/DBTablesUser.cc
This patches mainly use DBTermCStringProvider that is a helper
class of DBTermCodec. Its instance is named 'rhs' that means
Right Hand Side of a condition equation in an SQL statement.
The name also aims to avoid readers from being confused.
In this project, instances of DBTables
and the child classes have been named dbXXXX such as
dbMonitoring and dbHost.
The name 'rhs' seems to be a too short and meaningless. However,
lines to generate an SQL statement tend to be a long. So I believe
the short name makes the code simple after all.
=> Use dbterm cstr provider 3

client/test/feature/feature_test_utils.js, client/test/feature/register_action_test.js, client/test/feature/register_redmine_test.js, client/test/feature/register_server_test.js
Previous implementation uses 200 msec to wait response as magic number.
This pull request uses more abstract method to wait a response.
And it makes slightly faster feature test execution.
Before:
```log
PASS 71 tests executed in 18.101s, 71 passed, 0 failed, 0 dubious, 0 skipped.
```
After:
```log
PASS 71 tests executed in 16.774s, 71 passed, 0 failed, 0 dubious, 0 skipped. 
```
=> [client][test][feature] Reduce wait msec magic number

server/tools/hatohol-db-initiator.in
Previously, ```hatohol-db-initiator``` shows following message when user input (or write to config file) fault value for connecting to  MySQL server.
(Example: Input wrong password for ```root``` user.)
Before:
``` bash
$ hatohol-db-initiator --db_name hatohol --db_user root --db_password hatohol
Traceback (most recent call last):
File "/usr/local/bin/hatohol-db-initiator", line 221, in <module>
start(args)
File "/usr/local/bin/hatohol-db-initiator", line 154, in start
user=args.db_user, passwd=args.db_password)
File "/usr/local/lib/python2.7/dist-packages/MySQLdb/__init__.py", line 81, in Connect
return Connection(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/MySQLdb/connections.py", line 187, in __init__
super(Connection, self).__init__(*args, **kwargs2) …
```
=> [HatoholDBInitiator] Show MySQL error message.

server/data/hatohol.conf, server/src/ConfigManager.cc, server/src/ConfigManager.h, server/src/FaceRest.cc, server/test/testConfigManager.cc
FaceRestのワーカー数を設定する機能を追加しました。
Command line option:
-T, --face-rest-workers
0以下の値が指定された場合はエラーで終了
Config file:
[FaceRest]
workers=4
0以下の値が指定された場合はワーニング表示をしてデフォルト値(4)で起動
両方指定された場合はコマンドラインを優先します。
=> [Issue 189][FaceRest][ConfigManager] Add a setting of the number of FaceRest worker threads.

server/tools/hatohol-db-initiator.in, server/tools/hatohol-server-type-util
Following files didn't display licence header.
So, I add licence header to following files.
- hatohol-db-initiator(.in)
- hatohol-server-type-util
If these file don't need to display licence header, please close this Pull Request.
=> Add licence header.

server/test/ZabbixAPIEmulator.cc
If the targert paramter doesn't exist, 'value' that is not initialized
is use the comparison.
=> Fix invalid access in the parameter check.

server/src/ConfigManager.cc, server/src/ConfigManager.h, server/test/Helpers.cc
Otherwise some tests will fail if the config file is already
installed.
=> [test][ConfigManager] Don't load the config file after calling setupTestDB()

server/src/DBTablesAction.cc
type and command are used in validator.isValid(actionDef).
However, they are not correctly loaded to actionDef.
=> [DBTablesAction] Fix an invalid access to uninitialized region.

server/test/DBTablesTest.cc, server/test/testFaceRestHost.cc
Number of testServerInfo & testServerStatus are mismatched.
=> [testFaceRestHost] Fix invalid memory access in test_overview()

server/src/FaceRest.cc, server/test/DBTablesTest.cc, server/test/testFaceRestAction.cc
If the requested trigger is not found, the code refers
the invalid iterator. So this patch make it return immediately.
In addition, this patch also avoids such situation on the test.
=> [FaceRest] Avoid an invalid memory access on a condition.

server/test/testDBTablesHost.cc
The iterator has been used after the object pointed by it was removed.
=> [testDBTablesHost] Fix an invalid memory (iterator) access.

server/common/HatoholException.cc, server/common/HatoholException.h
Sometime we want a detailed stack trace when an exception is
thrown. If the following environment variable is set, hatohol
calls abort() soon after an HatoholException object is created.
HATOHOL_EXCEPTION_ABORT=1
=> [HatoholException] Option to call abort() immediately on an exception.

server/src/RestResourceAction.cc
RestResourceAction.cc:272:33: warning: adding 'ComparisonType' to a string does not append to the string [-Wstring-plus-int]
"type: " + cond.triggerSeverityCompType);
~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
=> [RestResourceAction] Fix an invalid error message

wercker.yml, wercker/Dockerfile
This pull request contains **experimental feature** for CI with CentOS 6.x series.
I found that `Wercker` supports Docker backend. ref: http://devcenter.wercker.com/articles/docker/
Docker backend makes for us to running various containers under `Wercker` CI environment!
That is, CentOS 6.x Docker container can run under `Wercker` Docker backend. :laughing: 
CI with Docker container (CentOS6.6) runs like this:
https://app.wercker.com/#build/54fd95a782ba1add4201ae34
`Wercker`'s worker running limit is 25 minutes.
So this wercker.yml and Dockerfile is only for building `Hatohol` server and web frontend.
For now, `Wercker`'s Docker feature seems to be *beta* feature, though. :<
=> [experimental] wercker: Try to add Wercker to build CentOS 6.x series

server/src/ArmZabbixAPI.cc, server/src/DBTablesMonitoring.cc, server/src/DBTablesMonitoring.h, server/src/HatoholArmPluginGate.cc, server/src/UnifiedDataStore.cc, server/src/UnifiedDataStore.h, server/test/DBTablesTest.cc
In addition I changed the first argument of
DBTablesMonitoring::addMonitoringServerStatus() from pointer to
reference because there is no possibility to pass a NULL pointer.
=> [HatoholArmPluginGate] Save MonitoringServerStatus on getting items

server/mlpl/src/SmartBuffer.cc
If realloc() fails, it does not free old block.  We have to remember
the old pointer pointer, or we leak.
=> [server][MLPL] SmartBuffer: Do not leak buffer after realloc() failure.

server/test/testArmZabbixAPI.cc
Rebased version of  #1084
Related issues:
* #915
* #1058
=> [testArmZabbixAPI] Add tests for "--load-old-events" 2

server/common/ZabbixAPI.cc
JSONBuilder::add() can accept std::string directly.
So c_str() can be ommited.
=> [ZabbixAPI] Make code simple (clean up).

server/common/HatoholArmPluginInterface.h, server/common/Params.h, server/common/ZabbixAPI.cc, server/common/ZabbixAPI.h, server/hap/HapProcessCeilometer.cc, server/hap/HapProcessZabbixAPI.cc, server/src/ArmZabbixAPI.cc, server/src/DBTablesAction.cc, server/src/DBTablesAction.h, server/src/DBTablesMonitoring.cc, server/src/HatoholArmPluginGate.cc, server/src/HatoholDBUtils.cc, server/src/RestResourceAction.cc, server/src/RestResourceHost.cc, server/test/DBTablesTest.cc, server/test/DBTablesTest.h, server/test/Helpers.cc, server/test/testActionManager.cc, server/test/testArmBase.cc, server/test/testArmZabbixAPI.cc, server/test/testDBTablesAction.cc, server/test/testDBTablesMonitoring.cc, server/test/testFaceRestAction.cc, server/test/testFaceRestHost.cc, server/test/testHatoholArmPluginGate.cc, server/test/testHatoholDBUtils.cc, server/test/testHostResourceQueryOptionSubClasses.cc, server/test/testUnifiedDataStore.cc, server/test/testZabbixAPI.cc, server/test/zabbix-api-response-collector.cc
[server] Change the type of the Hostgroup ID in Action conditionItem ID to a string.
Some monitoring systems such as OpenStack's ceilometer
use UUIDs to identify some resources. In order to save that
kind of data, Hatohol should also handle them as a string.
=> Host group ID in Action condition => String

server/hap/HapProcessCeilometer.cc, server/hap/HapProcessCeilometer.h
Type of ID was modified to string. therefore this function is unnecessary.
=> Remove function generateHashU64.

server/common/ZabbixAPI.cc, server/common/ZabbixAPI.h, server/src/ArmNagiosNDOUtils.cc, server/src/ArmZabbixAPI.cc, server/src/DBTablesMonitoring.cc, server/src/DBTablesMonitoring.h, server/src/HatoholArmPluginGate.cc, server/test/ZabbixAPITestUtils.cc, server/test/ZabbixAPITestUtils.h, server/test/testArmZabbixAPI.cc, server/test/testDBTablesMonitoring.cc, server/test/testZabbixAPI.cc
In a recent commit, getLastEventId() had changed to use cast().
in order to get the maximum number from the ones saved as a string.
However, it cannot utilize indexes. So it degrades the performance.
This patch just reverts it and uses max() again as with the code before.
Instead, the events have to be saved with the same digit number.
For Zabbix events, this has already been done in the previous commit.
NOTE: We should delete all events in DB before use it.
=> Get max event

server/src/DBTablesHost.cc
Now HostgroupIdType is a string. So the complicated conversion is no long needed.
=> [DBTablesHost] Clean up.

server/src/ArmBase.cc
In the previous code it always pass TRIGGER_STATUS_PROBLEM as
the second argument of ArmUtils::updateTriggerStatus() even if
ArmPollingResult is COLLECT_OK. Although it doesn't use the second
argument in this case, it's too misleading.
=> [ArmBase] Set proper trigger status at setServerConnectStatus()

server/src/ArmNagiosNDOUtils.cc, server/src/ArmZabbixAPI.cc, server/src/DBTablesHost.cc, server/src/DBTablesHost.h, server/src/HatoholArmPluginGate.cc, server/src/HatoholDBUtils.cc, server/src/HatoholDBUtils.h, server/test/DBTablesTest.cc, server/test/testDBTablesHost.cc
These patches add 'host_id', in other words Global Host ID in hostgroup_member.
It make some SQL statements simple. Previously some statements use the combination
of Server ID and (loacal) Host ID. This PR eliminates the need for it.
=> Use global host id 3

server/src/DBTablesAction.cc, server/src/DBTablesMonitoring.cc, server/src/DBTablesMonitoring.h, server/src/HatoholDBUtils.cc, server/test/testArmBase.cc
Until now, some members in EventInfo such as severity and brief
have been filled using a join operation with the trigger table,
when it's retrieved. This way has the following two demerits.
(1) It's hard to delete records in the trigger table.
(2) The number of the save of an event is only once, however
it may be read many times with join operations.
So this patch resolves the problems by storing duplicated information
in the event table.
=> Take some trigger information in events when the save

server/src/DBTablesMonitoring.cc, server/src/HostResourceQueryOption.cc, server/src/HostResourceQueryOption.h, server/test/DBTablesTest.cc
These patches creates SQL statements that use global host ID for the join.
As a result, the statements become simple.
=> Join with global host id 2

server/hap/HapProcessCeilometer.cc, server/hap/HapProcessCeilometer.h
Now an instance ID is also sent with the item ID.
So it's unnecessary to include an instance ID.
=> [HapProcessCeilometer] Use a simple Item ID string.

server/src/DBTablesMonitoring.cc, server/test/DBTablesTest.cc, server/test/Helpers.cc, server/test/testFaceRestHost.cc, server/test/testHostResourceQueryOptionSubClasses.cc
This work is for https://github.com/project-hatohol/hatohol/pull/1109#issuecomment-81364017.
* These patches keep migration code as possible. 
* Stop to use joining triggers and events tables.
=> [server][DBTablesMonitoring] Use events.extended_info instead of triggers' one

client/static/js/servers_view.js, client/test/browser/test_server_view.js
issue #1108.
Since the trigger Reload is not a setting change, 
to enable all users if possible monitoring.
=> Trigger reload is possible with all users.

server/src/DBTablesMonitoring.cc, server/src/DBTablesMonitoring.h, server/test/testHostResourceQueryOptionSubClasses.cc
使われなくなった古いホスト関連テーブルを削除します。
これに伴い、古いテーブルを参照したままだった箇所の修正や使われなくなったコードの削除も行っています。
#1119 でコンフリクトの修正ミスがあったので再送です。
=> Remove obsolete tables

server/src/DBTablesMonitoring.cc
=> [DBTablesMonitoring] Fix a broken hostgroup filter for items

server/src/DBTablesMonitoring.cc, server/test/testFaceRestHost.cc, server/test/testHostResourceQueryOptionSubClasses.cc
* fix a bug that exception is raised when filtering with hostname in event page
* Add a reproduce test case for this bug
=> [server][DBTablesMonitoring] Fix exception when filtering with hostname in event page (for releng_15.03)

server/src/DBTablesAction.cc
This work is related to #1140.
=> [server][DBTablesAction] Fix a bug that actions does not run when monitored servers belong to multiple hostgroups

server/test/testDBTablesAction.cc
This work is related to https://github.com/project-hatohol/hatohol/pull/1154#issuecomment-85028522.
* Add test case for found one hostgroupMemberId
* Add test case for found two hostgroupMemberIds
=> [server][DBTablesAction] Add test cases that actions does not run when monitored servers belong to multiple hostgroups

server/src/DBTablesAction.cc, server/src/DBTablesAction.h, server/test/testDBTablesAction.cc
This work is related to https://github.com/project-hatohol/hatohol/pull/1160#issuecomment-85766514.
Before:
* '1', '2' -> Fail
* '2', '1' -> Pass
After:
* '1', '2' -> Pass
* '2', '1' -> Pass
Because `getHostgroupIdStringList` does not gurantee a hostgroupId sequence.
* Add test for `getHostgroupIdStringList`
=> [server][test][DBTablesAction] Loosen assertion for HostgroupIdStringList

server/src/DBTablesAction.cc, server/src/DBTablesAction.h, server/test/testDBTablesAction.cc
This work is related to https://github.com/project-hatohol/hatohol/pull/1164#issuecomment-85854750.
* Remove `String` from `getHostgroupIdStringList` and related tests
* Add `call` prefix for same name function wrapper
=> [server][test][DBTablesAction] Adjust coding style

wercker/Dockerfile
CentOS 6.x can use DevToolSet version 2.
Thus, gcc 4.8.x series work fine in CentOS 6.x series.
This pull request intends to prepare to use C++11 and partially C++14 feature in Wercker.
=>C++11: [N3337](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2012/n3337.pdf)
=>C++14: [N3797](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3797.pdf)
* gcc 4.8 seems to support almost all C++11 feature. (see ref: https://gcc.gnu.org/gcc-4.8/cxx0x_status.html)
* gcc 4.8 seems to support C++14 feature partially. (see ref: https://gcc.gnu.org/projects/cxx1y.html)
---
NOTE:
If we want to use almost all C++14 feature in Wercker, we have to build a Docker image which contains gcc 5.x series build toolchain and its runtime.
Or, we have to build a Docker image which contains clang and llvm 3.4 or …
=> [wercker][expermental] Use DevToolSet-2 on CentOS 6.x series

.travis.yml
Travis CI cpp instance's default gcc is 4.6.
This pull request intents to use gcc-4.8.x series in Travis CI. 
Related to #1186.
=> [Travis] Switch to use gcc-4.8.x series in Travis

server/src/FaceRest.cc
This work is related to #1144.
Hatohol Server does not use HTTP authentication, so it should be used Bad Request (400) status code instead of Unauthorized(401).
=> [server][FaceRest] Use 400 status when authentcation failed

configure.ac
This pull request permits to use C++11 by default.
Related to #1186.
=> [configure][server] Enable C++11 by default

server/common/MonitoringServerInfo.h, server/src/DBAgent.h, server/src/DBAgentMySQL.cc, server/src/DBAgentMySQL.h, server/src/DBAgentSQLite3.cc, server/src/DBAgentSQLite3.h, server/src/DBTablesConfig.cc, server/src/RestResourceServer.cc, server/test/DBTablesTest.cc, server/test/Helpers.cc, server/test/testDBAgent.cc, server/test/testFaceRestServer.cc
Because it's required in HAPI 2.0:
https://github.com/project-hatohol/HAPI-2.0-Specification
In addition change the length of servers.base_url to 2047 according to https://github.com/project-hatohol/HAPI-2.0-Specification/issues/5
Revise #1196.
=> Add extended info for monitoring server

server/src/AMQPConnection.cc, server/src/AMQPConnection.h, server/src/AMQPConnectionInfo.cc, server/src/AMQPConnectionInfo.h, server/src/AMQPConsumer.cc, server/src/AMQPConsumer.h, server/src/AMQPMessageHandler.cc, server/src/AMQPMessageHandler.h, server/src/AMQPPublisher.cc, server/src/AMQPPublisher.h, server/src/HatoholArmPluginGateJSON.cc, server/test/Makefile.am, server/test/testAMQPConnection.cc
AMQPConnection (which is a wrapper class for rabbitmq-c) doesn't have an ability to send a message.
@cosmo0920 and I added an ad-hoc implementation of it.
Although I'll heavily modify it later to introduce an abstraction layer of the communication,
I want to merge the current code to implement the skeleton of the server side of HAPI-2.0 ASAP.
=> [AMQPConnection] Add an ability to publish a message

server/test/testAMQPConnection.cc
test_transferMessage should be executed only when TEST_AMQP_URL
is set, but it ignores the env value.
=> [testAMQPConnection] Fix a bug that a test isn't omitted

server/src/RestResourceServer.cc
Since handlerTriggerUpdateServer() sets HTTP response immediately
in the function, it shouldn't do it again in the callback function.
So the callback function isn't needed anymore because it doesn't
do other things.
Fix #1218
=> [RestResourceServer] Remove needless calllback for fetching triggers

server/src/DBTablesLastInfo.cc
I didn't notice this use case in #1202 and #1206.
We should rewrite this pattern by more sophisticated way near future?
=> [server][DBTablesLastInfo] Revise getItem from DB pattern with range-based for

server/test/testDBTablesHost.cc
I suddenly found this typo during adding test code for sync and delete series methods. :sweat: 
```log
worng ->
wrong
^^
```
=> [server][test][DBTablesHost] Fix a typo

server/common/Monitoring.h, server/src/DBTablesHost.cc, server/src/DBTablesHost.h, server/src/DBTablesMonitoring.cc, server/src/DBTablesMonitoring.h, server/test/testDBTablesHost.cc, server/test/testDBTablesMonitoring.cc
Because these APIs are requested HAPI2.0 specification: `updateType=ALL`.
* deleteHostgroupList
* syncHostgroups
* deleteVMInfoList
* deleteHostgroupMemberList
* deleteHostgroupMembers
* deleteTriggerInfo
* syncTriggers
* syncVMInfo(syncHostParents)
- `hostParents` procedure specification is not frozen, still disscussed [here](https://github.com/project-hatohol/HAPI-2.0-Specification/pull/22).
=> [server][DBTablesHost][DBTablesMonitoring] Implement sync & delete series APIs

server/src/DBTablesMonitoring.cc
Because new host management migration is already done.
=> [server][DBTablesMonitoring] Remove DBTablesHost.h include directive

server/common/HatoholError.cc, server/src/DBTablesConfig.cc
Fix validations to accept HAPI2 server types.
In addition, I added missing error types to investigate this issue.
It's an easy fix, so I'll merge it by myself.
=> Accept HAPI2 server types

server/test/DBTablesTest.cc, server/test/testHatoholArmPluginGateHAPI2.cc
loadTestDBServer() fails on saving HAPI2 server info because
it doesn't pass ArmPluginInfo to DBTablesConfig::addTargetServer().
=> [testHatoholArmPluginGateHAPI2] Fix broken tests in #1250

.travis.yml, server/hap2/rabbitmqconnector.py, server/hap2/test/README, server/hap2/test/TestRabbitMQConnector.py, server/hap2/test/run-test.sh, server/hap2/test/setup.sh, server/misc/setup-rabbitmq-server-port.sh, test/run-server-test.sh
Now we launch both Qppid (w/ default port 5672) and RabbitMQ server (with port 5673).
=> Add a HAPI2.0 transporter implementation RabbitMQConnector.

server/src/HatoholArmPluginGateHAPI2.cc
MLPL_WARN() in it isn't needed because warning messages are
output on parsing a response of exchangeProfile.
=> [HatoholArmPluginGateHAPI2] Fix a build error in #1260

client/static/js.plugins/hap1-ceilometer.js, client/static/js.plugins/hap1-zabbix.js, client/static/js.plugins/hapi-json.js, client/static/js.plugins/nagios.js, client/static/js.plugins/zabbix.js, client/static/js/servers_view.js, client/static/js/utils.js, client/test/browser/index.html, client/test/browser/test_utils.js, client/viewer/base_ajax.html, client/viewer/urls.py, client/viewer/views.py, server/tools/hatohol-def-src-file-generator.cc
* Plugin files are loaded from /static/js.plugins
* The file names should be {Plugins's UUID}.js
* A plugin must define a new object hatohol.hap_{UUID}
* Obsolete types (zabbix, nagios, ...) use "type" value instead of UUID
* The plugin implementation should be added to the object.
* type: UUID
* label: string
* getTopURL()
* getItemGraphURL()
* getMapsURL()
=> Add a basic mechanism for WebUI plugins

client/static/js/hatohol_graph.js, client/static/js/latest_view.js, client/static/js/utils.js, client/test/browser/test_utils.js
Because we are going to remove it in HAPI 2.0.
See also https://github.com/project-hatohol/HAPI-2.0-Specification/issues/43
It also fix a bug that an incorrect "prevValue" is shown for a string item.
=> [client] Avoid using "valueType" in items

server/hap2/test/TestHaplib.py
For example, https://travis-ci.org/project-hatohol/hatohol/builds/68278198
failed with the following exception.
File "/usr/lib/python2.7/dist-packages/pika/connection.py", line 56, in __init__
raise TypeError("Port must be an int")
Since the test of RabbitMQConnector is done in TestRabbitMQConnector,
the test causing the problem is redundant and unnecessary.
=> Fix a problem that raises an exception in TravisCI test.

server/test/testAMQPConnection.cc, server/test/testHatoholArmPluginGateHAPI2.cc
C++11 also provides `std::atomic`.
This class provides 
* `operator=` (same as `AtomicValue<T>.operator=` functionality)
* `operator()` (same as `AtomicValue<T>.operator()` functionality)
* `load()` (same as `AtomicValue<T>.get()` functionality)
* `store()` (same as `AtomicValue<T>.set()` functionality)
and various convenient member functions and operators since C++11.
ref. [cppreference.com | std::atomic](http://en.cppreference.com/w/cpp/atomic/atomic)
=> [server][test][HAPI2] Use std::atomic

client/static/js/hatohol_server_edit_dialog_parameterized.js
Should use "uuid" instead of "type" to distinguish each HAPI2
server type, because the "type" value of HAPI2 server types always
"7" (hatohol.MONITORING_SYSTEM_HAPI2).
=> [HatoholServerEditDialogParameterized] Enable to select HAPI2 server types

server/common/HatoholArmPluginInterfaceHAPI2.cc, server/common/HatoholArmPluginInterfaceHAPI2.h, server/src/HatoholArmPluginGateHAPI2.cc, server/src/HatoholArmPluginGateHAPI2.h
If armPluginInfo.path isn't empty, execute it with an argument "start" or "stop" when a instance of
HatoholArmPluginGateHAPI2 starts or stops.
=> [HAPI2] Initial support of starting & stopping HAPI2 plugins automatically

server/hap2/haplib.py, server/hap2/test/TestHaplib.py
The previous implementation forcely name the plugin from its
file name. This patch enables developers to name it something to like.
If the name is not given, the class name is used by default.
=> Can give the plugin name.

server/hap2/rabbitmqconnector.py, server/hap2/test/TestRabbitMQConnector.py
This Pull request fixes the broken test for RabbitMQConnector.
The 2nd patch extracts the lines related with the setting for SSL as
a method in order to make it easy to test, and adds a test for that.
=> Fix rabbitmq ssl

server/hap2/haplib.py
The combination of block=True and timeout=0 causes busy loop.
The "timeout" out should be None or a positive value when blocking
process is needed.
https://docs.python.org/2.7/library/queue.html#Queue.Queue.get
=> [hap2][CommandQueue] Fix an inappropriate timeout value for Queue.get()

server/test/testFaceRestHost.cc
"prevValue" in an item is removed at b7c7f182.
=> [testFaceRestHost] Fix broken tests

server/hap2/hap2_nagios_ndoutils.py, server/hap2/haplib.py, server/hap2/test/TestHaplib.py
NDOUtils seems to suse the local time. While HAPI2.0 uses UTC.
So the time conversion is needed.
=> Timezone hap2 nagios

server/src/DBTablesConfig.cc, server/src/DBTablesConfig.h, server/src/RestResourceServer.cc, server/test/testDBTablesConfig.cc, server/test/testFaceRestServer.cc
"uuid" is required on searching a HAPI2 server type
=> [DBTablesConfig][RestResourceServer] Fix an issue that can't find an appropriate HAPI2 server type

server/hap2/hap2_fluentd.py, server/hap2/test/TestHap2Fluentd.py
Previous implementation propagates the exception. However, things
like this might happen sometimes. So we just ignore them.
=> [hap2_fluentd] Ignore unepxected input line.

client/test/browser/test_events_view.js
EventsView calls stupidsort() of stupidtable, and it calls
setTimeout(function(){...}, 10) implicitly. It breaks tests of
EvensView.
This modification avoid it by waiting 20 ms.
=> [test][EventsView] Fix broken tests

server/hap2/hap2_fluentd.py, server/hap2/test/TestHap2Fluentd.py
Previously, such things causes stall.
=> Handle properly failure of the launch and the unexpected exit of the child process.

server/tools/hatohol-db-initiator.in
To accept the SQL files for HAPI2.0 plugins which consists of multple lines,
hatohol-db-initiator.in was also fixed.
=> Add server types of HAPI2.0 plugins.

ReleaseNote
一通りPRをチェックしましたが、 @ashie および @cosmo0920 は今回ほぼ HAPI 2.0 のサーバサイド
しかやっていませんので、ひとまずHAPI2.0を実装したことのみ記述しておきます。
実装されていない機能やTODOがいくつかありますが、どこまで書くべきか判断がついていません。
* プラグインの自動起動(今からスクリプト作成着手)
* updateMonitoringServerInfo
* セルフモニタリング
* putHostParentsのupdateType=ALL
* クライアント側procedureコールのタイムアウト処理
* ...
=> [ReleaseNote] Add description about HAPI2.0

server/hap2/hatohol/haplib.py, server/hap2/hatohol/test/TestHaplib.py, server/hap2/hatohol/test/TestStandardHap.py
This patch suppors a module name with multiple dots.
=> Support trasporter modules in deep path (#1374)

server/src/HatoholArmPluginGateHAPI2.cc
Length modifier of format specifier is invalid.
=> [HatoholArmPluginGateHAPI2] Fix broken timestamp parse on CentOS 6.5

server/hap2/hatohol/hap2_ceilometer.py, server/hap2/hatohol/hap2_fluentd.py, server/hap2/hatohol/hap2_nagios_ndoutils.py, server/hap2/hatohol/hap2_zabbix_api.py, server/hap2/hatohol/haplib.py, server/hap2/hatohol/standardhap.py, server/hap2/hatohol/test/TestHap2Ceilometer.py, server/hap2/hatohol/test/TestHap2Fluentd.py, server/hap2/hatohol/test/TestHap2NagiosNdoutils.py, server/hap2/hatohol/test/TestHap2ZabbixApi.py, server/hap2/hatohol/test/TestHaplib.py
This patch devides constructor into two phases. One is, of course,
__init__() which is called when the object is created. In it,
we just put liens that don't raise exceptions. And setup() is
added as a bottom half of the constructor, which may cause
exceptions. This mechanism makes sure that the object is
certainly created and it enables calling destroy method of
the object if the setup() raises.
With the mechanism, I fixed #1366 by destroying object that
raised an exception.
=> hap2: Improvement the recover mechanism (#1366)

client/viewer/views.py
issue #1373 の問題の修正です。
これで直ると思うのですが、手元の開発環境で何故かApacheで動作させることができておらず、
マシン不調などもあって別途環境を用意するのも時間がかかるので、まだApacheでテストする
ことができていません。
申し訳ありませんが、ひとまずこれでテストしてみて頂けますでしょうか。
もしまだAapacheで問題が解消しないようなら教えて下さい。
前のコードは現在のワーキングディレクトリを考慮せずに相対パスで取ってしまっているので、
どのみちこの修正は入れるべきだと思います。
=> [client] Fix path of HAPI2 plugins for WebUI

server/hap2/hatohol/hap2_ceilometer.py, server/hap2/hatohol/hap2_nagios_ndoutils.py, server/hap2/hatohol/test/TestHap2Ceilometer.py, server/hap2/hatohol/test/TestHap2NagiosNdoutils.py
HostIds in fetchItems and fetchTriggers is optional.
However, hap2 plugin was supposed to be always.
This patch fixed it.
=> Accept fetchItems request w/o hostId

server/hap2/hatohol/haplib.py
Without this patch, the children terminated remains as zonbie.
=> hap2: Collect child process soon after the termination.

server/hap2/hatohol/hap2_fluentd.py, server/hap2/hatohol/haplib.py, server/hap2/hatohol/standardhap.py
This patch makes all the HAP processes terminate when SIGTERM is received.
=> Terminate all the processes when the main plugin gets SIGTERM.

server/hap2/Makefile.am
The previsou code doesn't install them when DESTDIR is empty.
=> [hap2] Fix installing Python scripts

server/hap2/hatohol/rabbitmqconnector.py
`pika.channel.basic_publish` can be set `content-type` with `properties=pika.BasicProperties()`.
In hap2, `content-type` should be set `application/json`.
=> [hap2] Set content-type to "application/json"

server/hap2/hatohol/haplib.py
An unexpected message is sometimes sent to MainPlugin.
This patch drops if's that case.
=> [haplib] Make sure there's 'method' before message is sent to RPC queue.

client/static/js.plugins/hap2-ceilometer.js, client/static/js/utils.js, client/test/browser/index.html, client/test/browser/test_hap2_ceilometer.js, client/test/browser/test_utils.js
When the host ID of the ceilometer's alarm is "N/A", it's shown as Unknown ID.
These patches fixes it.
=> Ceilometer hostname fixup

server/hap2/hatohol/haplib.py, server/hap2/hatohol/rabbitmqconnector.py
This patch fixed the problem in which HAP2 plugins cannot recover
successfully when AMQP broker is restarted (#1384)
=> Fix 1384 recovery when amqp broker restart2

server/common/Utils.h, server/src/HatoholArmPluginGateHAPI2.cc, server/src/RestResourceServer.cc
* Pass more convenient environment variables to the plug-in control script
* Run the plug-in control script synchronously (these script shouldn't block long time)
* Complete relative path of plug-in control script
* Handle "passiveMode" parameter from WebUI correctly
* Allow empty queue name (generate it automatically)
=> 15.06 releng/hapi2 improve launching control script 2

server/common/AMQPConsumer.cc
* more customizable wait in `AMQPConsumer.mainThread`
=> [server][HAPI2][AMQPConsumer] Use semaphore instead of sleep to retry consume

server/hap2/hatohol/hap2_ceilometer.py
Lower version of Python such as 2.6 doesn't support
non-value dictionary. Instead this patch uses frozenset,
which is one of the built-in features of Python.
=> Don't use non-value dictionary.

server/hap2/hatohol/test/TestZabbixApi.py, server/hap2/hatohol/test/test_urllib2.py
Current items with lastclock=0 are dropped. So we have to choose one
other than 0.
=> [hap2] Fix a broken test: TestZabbixApi.TestZabbixApi.test_get_items()

hatohol.spec.in
* Specify `__os_install_post ` value strictly
* Loosen rm *.egg-info target
=> [rpm][15.06] Fix packaging failure in CentOS 6

setup-with-ansible/Vagrantfile, setup-with-ansible/centos7.yml, setup-with-ansible/setup-hatohol-dev.yaml
This playbook works as follows:
* Vagrant 1.6.5 or later.
Because vagrant 1.6.4 or earlier, following error occurred:
```log
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!
ARPCHECK=no /sbin/ifup eth1 2> /dev/null
Stdout from the command:
Stderr from the command:
```
```bash
$ CPU_NUM=4 MEMORY=4096 vagrant up hatohol-centos-7-x86_64
```
```bash
% vagrant ssh hatohol-centos-7-x86_64
$ git clone https://github.com/project-hatohol/hatohol.git
$ cd hatohol
$ ./autogen.sh
$ ./configure
$ make -j4
$ make dist -j4
$ MAKEFLAGS="-j 4" rpmbuild -tb hatohol-*.tar.bz2
```
=> [Ansible] Add CentOS7 playbook

server/hap2/Makefile.am
* Add --prefix option for install
* Add uninstall rule
I confirmed following things:
* "make hatoholdistcheck" succeeds
* It can build RPM packages correctly
=> [HAP2] Modify make rules for python scripts

client/static/css/hatohol.css, client/static/js/servers_view.js, client/viewer/servers_ajax.html
監視サーバ編集画面を開かなくても、監視サーバの設定を表示できるようにしました。
* マップの右に[info]アイコンを置き、その付近をホバーした時に表示します
* [info]アイコンの位置がウィンドウの右端に近いため、ポップオーバーは左側に出しました
* URLがはみ出るためポップオーバーの最大幅をbootstrapのデフォルトより広げました
* タイトルは通信状態のポップオーバーと同一としました
* パスワード欄も"******"として表示しました
* チェックボックスの状態は "True" / "False" で表示します
* 値が設定されていない要素の場合、ヒントがあればそれを表示するようにしました（設定後の値なので"(empty: Default)"のみのはずです）
=> [client][servers_view] Add popover of server info.

.travis.yml
It requires an old versio of phantomjs (1.9.1 - 1.9.7-15).
The error log:
5495 error peerinvalid The package phantomjs does not satisfy its siblings' peerDependencies requirements!
5495 error peerinvalid Peer mocha-phantomjs@3.6.0 wants phantomjs@1.9.1 - 1.9.7-15
=> [travis] Fix install error of mocha-phantomjs

.gitignore, .travis.yml, client/test/Makefile.am, client/test/feature/run-test.sh, configure.ac, package.json, test/run-client-test.sh
To prevent such issue: https://github.com/project-hatohol/hatohol/pull/1477
If we want to use latest dependent JavaScript libraries forcedly, this pull request should be rejected.
=> [npm] Use package json to specify JavaScript libraries version strictly

server/src/HatoholArmPluginGateHAPI2.cc
Should use a copy of ServerInfo instead of a reference.
=> [HatoholArmPluginGateHAPI2] Fix a bug that the self monitoring feature causes crashes

server/src/HatoholArmPluginGateHAPI2.cc
An error response should be returned when it receives a too large
events array.
=> [HatoholArmPluginGateHAPI2] Implement a missing error response

client/static/js/events_view.js, server/common/Monitoring.h, server/src/DBTablesMonitoring.cc, server/src/DBTablesMonitoring.h, server/src/RestResourceHost.cc, server/test/testDBTablesMonitoring.cc, server/test/testDBTablesMonitoring.h, server/test/testHostResourceQueryOptionSubClasses.cc
EventType should be used to filter events instead of TriggerStatus because the "Status" column
of EventsView uses EventType, not TriggerStatus.
Issue #1491
=> [EventsView] Filter events by EventType instead of TriggerStatus

hatohol.spec.in
It's disabled by default, but the RPM package still includes
hatohol-arm-plugin-zabbix which depends on Qpid.
=> [hatohol.spec] Add "--with-qpid" to configure script

configure.ac
For building RPM packages for testing.
issue #1451
=> [configure.ac] Bump version number to 15.07_dev1

server/common/HatoholArmPluginInterfaceHAPI2.cc, server/common/HatoholArmPluginInterfaceHAPI2.h, server/src/HatoholArmPluginGateHAPI2.cc
In the current implementation, HatoholArmPluginGateHAPI2 waits a response from a plugin forever
when it doesn't respond to a request.
This modification let it to give up waiting a response after 60 seconds are passed. 
issue #1458
=> [HatoholArmPluginGateHAPI2] Implement time-out feature for calling plugin's methods

hatohol.spec.in, server/hap2/hatohol/Makefile.am, server/hap2/hatohol/hap.py, server/hap2/hatohol/hap2_ceilometer.py, server/hap2/hatohol/hap2_fluentd.py, server/hap2/hatohol/hap2_nagios_ndoutils.py, server/hap2/hatohol/haplib.py, server/hap2/hatohol/standardhap.py, server/hap2/hatohol/test/TestHap.py, server/hap2/hatohol/test/TestHap2Ceilometer.py, server/hap2/hatohol/test/TestHap2NagiosNdoutils.py, server/hap2/hatohol/test/TestHaplib.py, server/hap2/setup_common.py
hap.py includes more basic components that are used from all hap
modules. haplib.py provides more framework-like components and
shall not be used from transporter and the sub classes.
=> [hap2] Split haplib.py into haplib.py and hap.py

.travis.yml
Because current build steps in Travis is heavily depends on sudo.
Upgrading document is here: http://docs.travis-ci.com/user/migrating-from-legacy/
But, sadly, I have no idea to upgrade Travis build step to adopt new Travis infrastructure.
=> travis: use `sudo: required` explicitly

server/hap2/hap2-control-functions.sh.in
…ated.
Currently the failure of the creation of the PID file is ignored.
However, the execution should be terminated on such situation.
One of the typical situations is execution by a user who cannot
create a file under /var/run.
=> [hap2] Abort launching hatohol plugin if the PID file couldn't be created.

hatohol.spec.in, server/hap2/hatohol/Makefile.am, server/hap2/hatohol/haplib.py, server/hap2/hatohol/standardhap.py, server/hap2/hatohol/test/TestHaplib.py, server/hap2/hatohol/test/TestStandardHap.py, server/hap2/hatohol/test/TestTransporter.py, server/hap2/hatohol/test/stub.py, server/hap2/hatohol/transporter.py, server/hap2/hatohol/transporters/__init__.py, server/hap2/hatohol/transporters/rabbitmqhapiconnector.py, server/hap2/setup_rabbitmqconnector.py
In HAPI2.0 framework, a transporter module is replaceable.
To improve the flexibility, this patch tries to find transporter
modules: hatohol/transporters under each $PYTHONPATH.
=> [hap2] find and load transporter modules dynamically (#1461)

server/hap2/hatohol/hap.py, server/hap2/hatohol/haplib.py, server/hap2/hatohol/simple_server.py, server/hap2/hatohol/test/TestHap.py
multiprocessing.Queue.get() might raise IOError due to EINTR.
The added functions provides the wrapper function get() that
retries when EINTR is raised in it.
=> [hap2] Retry Queue.get() when it interrputs by EINTR.

server/src/HostResourceQueryOption.cc, server/src/HostResourceQueryOption.h, server/test/Helpers.cc, server/test/Helpers.h, server/test/testDBTablesHost.cc, server/test/testDBTablesMonitoring.cc, server/test/testDBTablesMonitoring.h, server/test/testFaceRestHost.cc, server/test/testHostResourceQueryOption.cc, server/test/testHostResourceQueryOptionSubClasses.cc, server/test/testUnifiedDataStore.cc
{get,set}FilterForDataOfDefunctServers ->
{get,set}ExcludeDefunctServers
Because the word "filter" doesn't indicate the meaning "exclude",
it's hard to recognize its behaviour.
In addition, the term "dataOf" is verbose in this context.
=> [HostResourceQueryOption] Rename unclear & too long function names

server/hap2/hatohol/standardhap.py
This has been contaminated in the patch that replaces logging with logger.
=> [hap2] Fix the typo in the option usage.

server/hap2/hatohol/test/TestHaplib.py
The previous test reuse the same HapiProcessor instance. This depends on the situation and might cause unstable results. This patch uses a new instance in all the tests.
=> Use independent instance in test of hapi processor

server/src/HatoholArmPluginGateHAPI2.cc, server/src/HostInfoCache.cc, server/src/HostInfoCache.h, server/test/testHostInfoCache.cc
This pull request suppress warning of HostInfoCache.
The warning is shown when the correspond host is not found in the DB.
However, some HAPs such as hap2_fluentd.py doesn't send host information.
In that case, the warning is shown repeatedly. The patches automatically
unknown hosts register in HostInfoCache ad hoc.
=> Suppress warning of host cache #1424 2

server/common/Params.h, server/src/HostResourceQueryOption.cc, server/src/HostResourceQueryOption.h, server/test/DBTablesTest.cc, server/test/TestHostResourceQueryOption.cc, server/test/TestHostResourceQueryOption.h, server/test/testDBTablesMonitoring.cc, server/test/testHostResourceQueryOption.cc, server/test/testHostResourceQueryOptionSubClasses.cc
Add member functions to set filters by plural {servers,hostgroups,hosts}.
It's the revised version of #1537.
=> [HostResourceQueryOption] Filter by plural {servers,hostgroups,hosts}

server/src/RestResourceHost.cc, server/test/testFaceRestHost.cc
It's the Web API for #1538.
Example query:
```
/events?selectHosts%5B0%5D%5BserverId%5D=1&selectHosts%5B1%5D%5BserverId%5D=2&selectHosts%5B1%5D%5BhostgroupId%5D=3&selectHosts%5B2%5D%5BserverId%5D=4&selectHosts%5B2%5D%5BhostId%5D=5&excludeHosts%5B0%5D%5BserverId%5D=2&excludeHosts%5B1%5D%5BserverId%5D=6&excludeHosts%5B1%5D%5BhostgroupId%5D=7&excludeHosts%5B2%5D%5BserverId%5D=8&excludeHosts%5B2%5D%5BhostId%5D=9
```
The decoded string of the query part:
```
selectHosts[0][serverId]=1&selectHosts[1][serverId]=2&selectHosts[1][hostgroupId]=3&selectHosts[2][serverId]=4&selectHosts[2][hostId]=5&excludeHosts[0][serverId]=2&excludeHosts[1][serverId]=6&excludeHosts[1][hostgroupId]=7&excludeHosts[2][serverId]=8&excludeHosts[2][hostId]=9
```
It can be generated by $.param():
```js
var exampleQuery = { …
```
=> [FaceRest] Add queries to select or exclude {server,hostgroups,hosts}

Makefile.am, autogen.sh, configure.ac, version-generator.sh
Developers and tester sometimes would like to use a temporarily
built package. However, it's needed to have a large version number
update the package on the test platfrom.
This patch enables to include date and time to the version string
automatically.
=> Can add date and time to the package version.

configure.ac, version-generator.sh
This is a fix for the problem that was pointed out at #1541.
I confirmed that it can be build on CentOS 6.
=> Use m4_esyscmd in order to build on CentOS6.

server/test/Helpers.cc, server/test/Helpers.h, server/test/testDBTablesMonitoring.cc
The order of a returned event list by getEventInfoList() is
undetermined and depends on the used storage engine.
Thus comparision between the output and the expectation should be
done after sorting.
Actually, some tests such as test_getEventsSelectByServersAndHosts()
fail w/o this fix when MEMORY storage engine is used as.
<pre>
$ HATOHOL_MYSQL_ENGINE_MEMORY=1 MLPL_LOGGER_LEVEL=WARN ./run-test.sh -t /Monitoring/
</pre>
=> [server][test] Compare the return value with sorting.

server/src/DBTablesMonitoring.cc, server/src/DBTablesMonitoring.h, server/test/testDBTablesMonitoring.cc
This methods provides runtime information of the componet.
At this point, events statistics are only available.
=> Add a new method: DBTablesMonitoring::getSystemInfo()

server/src/FaceRestPrivate.h, server/src/RestResourceAction.cc, server/src/RestResourceAction.h, server/src/RestResourceHost.cc, server/src/RestResourceHost.h, server/src/RestResourceIncidentTracker.cc, server/src/RestResourceIncidentTracker.h, server/src/RestResourceServer.cc, server/src/RestResourceServer.h, server/src/RestResourceUser.cc, server/src/RestResourceUser.h
Currently, subclasses of FaceRest::ResourceHandler have their own
Factory classes. However, their implementations are basically similar.
So these patches provide the following two template methods to realize
them with a tiny code.
- FaceRestResourceHandlerSimpleFactoryTemplate
- FaceRestResourceHandlerArg0FactoryTemplate
=> Rest resource factory template

server/src/FaceRest.cc, server/src/FaceRestPrivate.h, server/src/RestResourceAction.cc, server/src/RestResourceHost.cc, server/src/RestResourceHost.h, server/src/RestResourceIncidentTracker.cc, server/src/RestResourceServer.cc, server/src/RestResourceServer.h, server/src/RestResourceUser.cc, server/src/RestResourceUser.h
Some sub classes of ResoureHandler had to implement similar manadatory
methods such as handler(). This patch addressed the boring work by
calling the handler in the base class: ResourceHandler instead of
each sub class.
=> [server][FaceRest::ResourceHandler] Eleminate redundant lines.

server/src/FaceRest.cc, server/src/FaceRestPrivate.h
m_staticHandlerFunc ->
m_staticHandler
RestHandlerFunc ->
RestStaticHandler
As a result, we can make it easy to see the following pair.
RestStaticHandler <-> RestMemberHandler
=> [server][FaceRest] Use an organized name.

server/src/FaceRest.cc, server/src/FaceRest.h, server/src/FaceRestPrivate.h, server/src/RestResourceHost.cc, server/src/RestResourceHost.h, server/src/RestResourceServer.cc, server/src/RestResourceServer.h, server/src/RestResourceUser.cc, server/src/RestResourceUser.h
In the previous implementation, ResourceHandler has both variables for
a static handler and a member handler, although only one of them
is used. And it has conditional branch in handle().
This patch adds the specialized class for them and makes the code
more simple with the minimum impact to the existing code.
=> [server][FaceRest] New classes: RestResourceStatic/MemberHandler.

server/src/DBTablesMonitoring.cc, server/src/DBTablesMonitoring.h, server/src/FaceRest.cc, server/src/Makefile.am, server/src/OperationPrivilege.h, server/src/RestResourceSystem.cc, server/src/RestResourceSystem.h, server/src/UnifiedDataStore.cc, server/src/UnifiedDataStore.h, server/test/Helpers.cc, server/test/Helpers.h, server/test/Makefile.am, server/test/testDBTablesMonitoring.cc, server/test/testFaceRestSystem.cc, server/tools/hatohol/voyager.py
This Pull Request adds a new REST API /system-info.
The API provides the system information. However, Currently
the feature only deals with the number of events every
10, 100, and 1000 seconds.
=> Events statistics system wide

wercker.yml, wercker/Dockerfile
Related to #1563.
Wercker is working like this: https://app.wercker.com/#build/55ff8629ee52f86b6d085d88
For future work:
Docker 1.9 or later will support environment variables interpolation in building time.
In more detail, refer to this docker repo's PR: https://github.com/docker/docker/pull/15182
=> [wercker][CentOS] Specify commit in Wercker with its environment variable

server/src/DBTablesMonitoring.cc, server/src/DBTablesMonitoring.h, server/src/RestResourceHost.cc, server/src/RestResourceHost.h, server/src/UnifiedDataStore.cc, server/src/UnifiedDataStore.h, server/test/testDBTablesMonitoring.cc, server/test/testFaceRestHost.cc, server/test/testFaceRestNoInit.cc
An example query:
* /events?countOnly=true&serverId=3 (Any event filters can be added)
An example response:
{
"apiVersion": 4,
"errorCode": 0,
"numberOfEvents:4"
}
=> [server] Add REST API to get only number of events

client/hatohol/forwardview.py
This patch doesn't contain the error reason in the response,
because it's internal information and should not to be published.
=> [WebUI] Fix the response code that calls absent memebers.

server/src/ConfigManager.cc, server/src/DBHatohol.cc, server/src/DBHatohol.h, server/tools/hatohol-db-initiator.in, test/feature-test.sh
Previously hatohol-db-initiator is hard to initialize tables in
the DB server on an another machine.
This patch provides the way to specify the DB server and the port.
In addtion, some paramters for hatohol-db-initiator are set
by default to make it easy to use.
=> [server] Can initialize tables for Hatohol on another machine.

client/test/browser/test_events_view.js
Because stupidtable is completely removed from EventsView, the
work arround code for it isn't needed anymore.
=> [test][EventsView] Remove needless code

client/static/js/hatohol_add_action_dialog.js, client/static/js/hatohol_incident_trackers_editor.js, client/static/js/incident_settings_view.js, client/test/browser/index.html, client/test/browser/test_hatohol_incident_tracker_editor.js, server/src/ArmIncidentTracker.cc, server/src/UnifiedDataStore.cc
Add Hatohol incident tracker type to IncidentTrackerEditor.
=> [IncidentTrackerEditor][WebUI] Add Hatohol incident tracker settings

client/Makefile.am, client/conf/apache/django.wsgi, client/hatohol/base_settings.py, client/hatohol/settings_devel.py, client/hatohol/settings_product.py, client/manage.py
When a DEBUG variable in settings.py is True and any problem happens in
WebUI code, some debug information is sent to the broweser. This behavior
is generally undesired.
This fix suggests two settings files for development and procduction
respectively.
=> [WebUI] Make DEBUG False to avoid internal information from being shown.

client/static/css/hatohol.css, client/static/js/events_view.js, client/viewer/events_ajax.html
Stop to apply filter immediately.
* Keep previous behaviour
* Stop to apply filter immediately.
* Users should be push `apply filter(s)` button to use filter
(Above screen shot is with `?devel=true&legacy=true`)
=> Stop to apply filter immediately

server/common/Params.h, server/src/DBTablesConfig.cc, server/src/DBTablesConfig.h, server/test/DBTablesTest.cc, server/test/DBTablesTest.h, server/test/testDBTablesConfig.cc
| id | status| color         |
| ---| ------------- | ----------- |
| int(11) `auto increment` `primary key` |  int(11)   | varchar(255) |
* upsertSeverityRankInfo(Create|Update)
* updateSeverityRankInfo(Update)
* getSeverityRankInfo(Read)
* deleteSeverityRanks(Delete)
Used by getSeverityRankInfo.
* (get|set)targetStatus
* (get|set)targetColor
* Define CRUD `severity_ranks` related privileges
* Check `severity_ranks` related privileges in CRUD phase
=> [DBTablesConfig][SeverityRank] Implement severity_ranks table elementary CRUD operations

test/launch-hatohol-for-test.sh, test/run-client-test.sh
test/run-client-tesst.sh launches Hatohol server and manage.py,
although it never terminate them.
It is no problem unless this script is used in Travis CI, because
the new Hatohol server and manange.py is not required and launched.
However, on developemnet, some situation need to terminate them
in order to run the script again.
=> [test] Terminate launced Hatohol server and manage.py.

autogen.sh
Previously we have to remove m4 cache dir and add an environemnt
variable to autogen.sh.
This patch does it only with -d option.
=> Add an option easy to select date-version package or not.

server/src/DBTablesConfig.cc, server/src/DBTablesConfig.h, server/src/UnifiedDataStore.cc, server/src/UnifiedDataStore.h, server/test/testDBTablesConfig.cc
And this PR contains the commit which renames `getSeverityRateInfo` function to  `getSeverityRates`.
=> [UnifiedDataStore] Add severity rate CRUD functions

client/static/css/hatohol.css, client/static/js/events_view.js, client/viewer/events_ajax.html
In addition, some minor fixes are also included in thie PR:
* Swap the position of "Status" filter & "Minimum Severity" filter to follow the default order of events table's columns
* Avoid shrinking events table's width when the incident feature isn't enabled
This is the rebased version of #1612.
=> [EventsView] Add "Treatment" (a.k.a incident status) filter

wercker.yml, wercker/Dockerfile
Wercker says: age (6.6) from centos, Server error: 400 trying to fetch remote history.
It seems that centos:6.6 image has been deleted from DockerHub.
We should start using CentOS 6.7 image in Wercker.
=> [Wercker] Try to use CentOS 6.7 docker image

server/src/DBTablesConfig.cc, server/src/DBTablesConfig.h, server/src/RestResourceSeverityRank.cc, server/test/DBTablesTest.cc, server/test/Helpers.cc, server/test/testDBTablesConfig.cc, server/test/testFaceRestSeverityRank.cc
I've found missing label and as_important in severity_ranks table and its REST API.... :'(
Follow up #1618.
=> [REST API][SeverityRank] Severity rank REST API fix

wercker.yml
Before merging this PR, it also needs to switch Wercker build settings from classic.
Related to #1615.
Yes, new Wercker build stack can use Docker image directly!!
=> [Wercker] Rewrite wercker.yml to adopt new Docker based building stack

server/src/HatoholArmPluginGateHAPI2.cc
In addition, auto value: lastInfo was a copy. It might degrade
the performance slightly. This expression doesn't have a copy.
=> [HatoholArmPluginGateHAPI2] Use a simpler expression.

server/src/DBAgent.cc, server/src/DBAgent.h, server/test/testDBAgent.cc
This feature aims to be used for adressing #1569 in which
last info and data body isn't save atomically.
=> Save lastinfo body atomic #1569 2

server/src/HatoholArmPluginGateHAPI2.cc
The variable that is now not used, but we will use future, causes a build warning.
Instead of the warning, we show the message as a reminder using the variable.
=> [HatoholArmPluginGateHAPI2] Suppress a build warning. 

server/test/testConfigManager.cc
In hatoholInit(), ConfigManager::reset() is invoked with loadConfigFile = true. This makes the test results depend on contents of the configuration file.
Here, we call reset() with loadConfigFile = false in order to eliminate the dependency and makes sure the same conditions.
=> Dont read config file on conf manager test

server/src/DBAgent.cc, server/src/DBAgent.h, server/test/testDBAgent.cc
Because this statement is needed by summary SQL query like this:
```
mysql> select severity, count(severity) from incidents left join events on
events.unified_id = incidents.unified_event_id where severity in
(3,4,5) group by severity;
```
And "GROUP BY" clause place is between "WHERE" and "ORDER BY" clauses.
This clause is also omittable same as "WHERE" and "ORDER BY" etc.
Strictly speaking, "HAVING" clause can put into between "GROUP BY"
clause and "ORDER BY" clauses. But now, this clause does not implement
yet.
=> [DBAgent] Add "GROUP BY" statement

client/static/js/events_view.js, client/viewer/events_ajax.html
When hatohol incidents server is absent, information which is related to hatohol type incidents server is needless to display.
=> [EventsView] Try to conceal hatohol type incidents releated to information when hatohol incidents server is absent

server/test/Helpers.cc, server/test/testFaceRestHost.cc
The order of elements in a JSON object is arbitrary. So the simple JSON strings comparision is sometimes inappropriate and causes false-positive.
=> [testFaceRestHost] Compare as JSON object.

server/src/DBTables.h, server/src/DBTablesHost.cc, server/src/DBTablesMonitoring.cc
Some methods in DBTables's subclasses insert multiple records in a transaction.
Each of them ran for-loop with the similar pattern. These patches add a template
method that is commonly used and use it to make code simple.
=> Make code in a transaction simple.

client/viewer/events_ajax.html
Minimum severity filter select box becomes like this:
Related to #1645.
=> [EventsView][WebUI] Add labels to minimum severity filter select box

server/hap2/hatohol/haplib.py, server/hap2/hatohol/standardhap.py
Some situation would need to select a sort of polling targets such hosts,
trigger, and events. This patch adds an option to enumerate them.
=> [hap2] Can select polling targets.

server/hap2/hatohol/standardhap.py
An argument: status_log_interval is just passed to the constructor
of BasePoller. So there's no needed to be declared explicitly.
And this way make it easy to pass parameters that are added in
the future.
=> [hap2] Remove the explict declaration of argument just passed.

client/static/js/events_view.js
* Apply severity ranks color settings to pieChart and table
Note that this feature is too honest implementation.
This feature works as below:
=> [EventsView] Apply severity ranks color settings

client/static/js/events_view.js, client/viewer/events_ajax.html
In addition, clear "End time" field when "Latest events" is
clicked.
=> [EventsView] Move "Latest events" button next to "Apply filter" button

client/static/js/events_view.js
Set the begin time of the default filter as the placeholder of
"Begin time" entry.
=> [EventsView] Show default filter's begin time

server/hap2/hatohol/zabbixapi.py
Previously, the fact that KeyError is caught logged, however,
the key name the exception caused is not shown. This makes
investigation of the reason difficult.
This patch logs exception details.
=> [hap2][zabbixapi] Log KeyError reason.

client/static/js/events_view.js
Because event["status"] is a status of a trigger, not a event.
We should use event["type"] instead of event["status"].
=> [EventsView] Fix a bug that statuses of some problem events become green 

client/test/browser/test_events_view.js
An event status value should be "0" when the label is "OK".
=> [test][EventsView] Fix a wrong test

server/hap2/hatohol/hap2_zabbix_api.py
last_info in haplib is hold as a type: unicode because the input
type of event id is it. However, the code n hap2_zabbix_api excepts
an integer type. As a result, right event_form parameter is not
calculated.
=> [hap2_zabbix_api] Fix a bug of calculating event_from for Zabbix API.

client/static/js/hatohol_events_view_config.js, client/test/browser/test_hatohol_events_view_config.js, client/viewer/events_ajax.html, server/src/DBTablesMonitoring.cc, server/src/DBTablesMonitoring.h, server/src/RestResourceHostUtils.cc, server/test/testDBTablesMonitoring.cc, server/test/testFaceRestHost.cc, server/test/testHostResourceQueryOptionSubClasses.cc
Currently "statuses" filter is used for selecting events with certain states.
But "statuses" filter is inappropriate in most case because it means "Trigger statuses", not "Event statuses".
We should use "types" filter for selecting event states.
=> Add "types" filter for events

server/src/RestResourceHost.cc
The cause is less reference count of RestResourceHost.
=> [RestResourceHost] Fix a crash bug of updating an incident

server/src/RestResourceSummary.cc
Status::DONE should be treated as assigned events.
(Souldn't be treated as unassigned events.)
=> [RestResourceSummary] Fix the number of assigned events

server/hap2/hatohol/hap.py
Currently the traceback of the exception is logged without
linebreaks. It is hard to recognize the content.
This patch improve the visibility by inserting line breaks
into the messages.
Example:
[currently]
2015-11-05 12:45:33,541    ERROR [21870] hatohol.hap:92:  Unexpected error: <type 'exceptions.ValueError'>, No JSON object could be decoded, ['  File "/home/kyamato/hatohol/server/hap2/hatohol/haplib.py", line 976, in __poll_in_try_block\n    self.poll()\n', '  File "hatohol/hap2_zabbix_api.py", line 138, in poll\n    self.make_sure_token()\n', '  File "hatohol/hap2_zabbix_api.py", line 57, in make_sure_token\n    self.__api = zabbixapi.ZabbixAPI(ms_info)\n', '  File "/home/kyamato/hatohol/server/hap2/hatohol/zabbixapi.py", line 39, in __init__\n    monitoring_server_info.password)\n', …
=> [hap2] Show line breaks in traceback.

server/hap2/hatohol/haplib.py
last info is str() in HAPI2.0 specification.
=> [haplib] Cast event last info to str()

server/src/OperationPrivilege.cc, server/test/testOperationPrivilege.cc
`1` is not `unit64_t` literal but `int32` literal.
It should use `1ULL` instead. 
Related to #1694.
=> [Operationprivilege][server] Expand privileges bit width

client/static/css/zabbix.css, client/static/js/events_view.js, client/static/js/hatohol_events_view_config.js, client/test/browser/test_events_view.js, client/viewer/events_ajax.html
* status: The current trigger status which is concerned with the
event.
* type:   The event state.
In usual cases we should use the later one for events, but the
former one was often used in the previous code.
This commit fixes this issue to avoid confusion.
Please clear your config value of "event.columns" to reset the
default setting.
=> [EventsView] Distiguish the properties "type" and "status" of events correctly in internal code

server/hap2/hatohol/haplib.py, server/hap2/hatohol/test/TestHaplib.py, server/hap2/hatohol/test/TestZabbixApi.py, server/hap2/hatohol/zabbixapi.py
Presently, the accuracy of time form the Zabbix server is dropped in hap2_zabbix_api.py.
This patch address the problem by handling unix time and nanoseconds separately.
=> [hap2] Fix the bug in which effective digit of time is dropped (#1704).

server/hap2/hatohol/zabbixapi.py
enumerate() is not necessary. So this patch removes it.
=> [hap2][zabbixapi] Remove unused enumerate().

server/tools/hatohol-def-src-file-generator.cc
`hatohol-db-initiator` should be able to treat over 32bit integer.
Otherwise, admin privileges wrongly disappears due to overflow.
=> [hatohol-def-src-file-generator] Add uint64_t version of toString utility function

server/hap2/hatohol/hap2_zabbix_api.py, server/hap2/hatohol/test/TestHap2ZabbixApi.py, server/hap2/hatohol/test/TestZabbixApi.py, server/hap2/hatohol/test/test_urllib2.py, server/hap2/hatohol/zabbixapi.py
[hap2_zabbix_api] Fix update_events function
- Separate update_event to incase of polling and fetch
- Define MAX_NUMBER_OF_EVENTS_FROM_ZABBIX
- Split a requset that sent to Zabbix API
[zabbixapi] Implement get_end_id
Related: #1668
=> [hap2_zabbix_api] Fix update events function

server/hap2/hatohol/simple_server.py
Previously a null object is returned. This behavior violates the HAPI-2.0 Spec.
=> [simple_server] Send an empty string in accordance with HAPI-2.0 Spec.

client/static/js/custom_incident_labels_view.js, client/static/js/hatohol_navi.js, client/viewer/custom_incident_labels_ajax.html, client/viewer/urls.py, server/data/custom-incident-statuses.sql
Added in Navigate Menu like this:
Labels columns are editable:
Saving mechanism is imitating from severity_ranks view.
=> [CustomIncidentLabels][WebUI] Add custom incident labels in WebUI

server/hap2/hatohol/hap2_zabbix_api.py
When polling is aborted. this patch calls ZabbixAPIConductor's
reset(). It internally releases the ZabbixAPI object. As a
result, recreation of it is performed in the next polling
in which auth. token is obtained again too.
=> [hap2_zabbix_api] Reset zabbixapi object after error. (#1718)

server/hap2/hatohol/test/TestZabbixApi.py, server/hap2/hatohol/test/test_urllib2.py, server/hap2/hatohol/zabbixapi.py
auth token取得に使用するメソッド以外で2系から3系への変更点は見当たらなかった。
組み込み，HAPI2.0ともに動作を確認。
user.loginメソッドはzabbix２系，3系共通のメソッドのため，これに変更することで両verに対応できる。
=> [zabbixapi] Correspond to the zabbix3.0

data/test/setup.sql
In the development, there's already have some of the tables depending on the situation.
Even in that case, this patch makes the SQL run successfully.
=> [test/setup.sql] Skip creating DB if existing.

server/src/HatoholArmPluginGateHAPI2.cc, server/test/testHatoholArmPluginGateHAPI2.cc
HAPI2.0 spec. defines the type of itemGroupName as an array of
strings. However, the implementation has handled it as a single
string. This patch addresses the problem.
*****
This PR is a fixed version of #1735 and #1736.
=> [HatoholArmPluginGateHAPI2] Handle array of itemGroupName.

configure.ac, server/data/Makefile.am, server/tools/hatohol-db-initiator.in
These patches addresses the problem in which HAPI1 plugins
are shown in Web UI (servers) even HAPI1 cannot be used
due to the build without QPID development packages.
=> Remove HAPI1 plugins from web dialog #1626

client/static/js/events_view.js, client/test/browser/test_events_view.js
If users set up custom incident labels like this...:
In events view, these values are used in tables and select box like these:
* from NONE to DONE are always shown and be able to use
* from USER01 to USER06 are only shown when label is defined
=> [EventsView][WebUI] Set up custom incident status label

server/src/RestResourceServer.cc
When using HAPI2 and selected `passive mode`, it should clear `armPluginInfo.path`.
Otherwise, detect code for HAPI2 passive mode, such as `path.empty()`, is meaningless.
Related to #1733.
With this patch, hatohol server can recognize HAP2 passive mode like these:
=> [RestResourceServer] Clear plugin path when HAPI2 passiveMode

client/static/js/events_view.js, server/common/Monitoring.h, server/src/IncidentSenderHatohol.cc, server/src/IncidentSenderHatohol.h, server/src/RestResourceSummary.cc, server/src/UnifiedDataStore.cc, server/src/UnifiedDataStore.h, server/test/testFaceRestSummary.cc, server/test/testIncidentSenderHatohol.cc
Revise #1744.
Accept user-defined incident statuses at IncidentSenderHatohol.
In addition, this PR also modifies counting assigned/unassigned important events at RestResourceSummary
because they are also concerned with incident statuses.
=> [Server] Accept user-defined incident statuses 

client/hatohol/views.py, client/test/python/TestEventFiltersView.py, client/test/python/TestGraphsView.py
In the previous version, Django reports the following warning
message when a user save a new filter which includes UTF-8 string.
This modification fixes this issue by converting a bytestring to
an unicode string.
/usr/lib/python2.7/dist-packages/django/db/models/fields/__init__.py:245: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
if not self.blank and value in self.empty_values:
/usr/lib/python2.7/dist-packages/django/db/models/fields/__init__.py:202: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
if value in self.empty_values:
Fix #1751
=> [client] Suppress UnicodeWarning of Django

client/static/css/hatohol.css
In the previous version following styles are applied to all ul &
li elements. It breaks the layout of navbar.
display: inline-block;
vertical-align: middle;
The above style is introduces at 29cac9bf to align "Latest events"
button and pager buttons. But it's not needed anymore because
"Latest events" button has been moved to other place.
=> [client] Remove broken styles

client/static/css/hatohol.css, client/static/js/events_view.js, client/viewer/events_ajax.html
Default checkbox state is unchecked:
When this checked, event descriptions are abbreviated like this:
=> [EventsView] Support toggle abbreviating event descriptions feature

server/common/HatoholError.cc, server/common/HatoholError.h
Error messages are statically defined. So this patch provides a
way to get it without instantiation.
=> [server][HatoholError] Add a static version of getMessage().

client/static/js/events_view.js, server/src/RestResourceSummary.cc, server/src/RestResourceSummary.h, server/test/testFaceRestSummary.cc
* Replcae numOfUnAssignedImportantEvents with numOfAssignedImportantEvents
* Because all unknown statuses should be treated as "UnAssigned"
* Apply "AND" condition against user filter & important severities
* Apply "AND" condition against user filter & "assigned" incident statuses
* Change the path of the REST resource to accentuate "important" condition
* /summary -> /summary/important-events
* Remove unused property: numOfNotImportantEvents
=> [RestResourceSummary] Correct wrong count of important events

server/src/HatoholArmPluginGateHAPI2.cc
Because `LAST_INFO_XXX` constants are rvalue(temporary value).
Thus, these constants will be destroyed after following constructor finished:
```cpp
Impl::UpsertLastInfoHook lastInfoUpserter(*m_impl, LAST_INFO_HOST);
```
Hence, lastInfoUpserter refers corrupted memory region and inserts wrong
`data_type` value.
We SHOULD store its copy into UpsertLastInfoHook member variable.
Related to https://github.com/project-hatohol/hatohol/issues/1769.
=> [HatoholArmPluginGateHAPI2] Fix memory corruption due to rvalue reference variable lifetime

client/Makefile.am, client/conf/locale/ja/LC_MESSAGES/django.po, client/hatohol/base_settings.py, client/hatohol/branding_settings.py, client/static/css/hatohol.css, client/static/js/hatohol_navi.js, client/static/js/utils.js, client/viewer/base_ajax.html, client/viewer/events_ajax.html, client/viewer/views.py
This modification makes easy to replace the brand name & logo.
If you want to use your own brand name & logo, modify client/hatohol/branding_settings.py
then put your logo image to /static/images in your site.
=> [client] Rebranding mechanism

server/test/Helpers.cc, server/test/Helpers.h
A newly added magic column: DBCONTENT_MAGIC_CURR_TIME enables
a unix time to be tested.
=> [test][Helpers] Add a new magic column for checking the content.

server/src/SessionManager.cc
Previously session timer is alive after reset(). And reset() also
recreates a SessonManager instance that is refered by the timer
handler. As a result, invalid memory access may happen.
This patch fixed the bug.
***
Note that  one of the test on TravisCI failed. However, no valgrind reported invalid memory access for all the test on my environment. So the cause of the failure doesn't seem to be related with the SessionManger.
=> [server][SessionManager] Address an invalid memory access after reset().

server/test/testDBAgent.cc
Without this patch, Valgrind reports the problem like
==18336== Conditional jump or move depends on uninitialised value(s)
==18336==    at 0x794E8B4: DBAgent::TableProfile::TableProfile(char const*, ColumnDef const*, unsigned long const&, DBAgent::IndexDef const*) (DBAgent.cc:93)
==18336==    by 0xB0D887C: void testDBAgent::TestDBAgent::assertUpdateArgAdd<long, int>(long const*, unsigned long const&) (testDBAgent.cc:277)
==18336==    by 0xB0CAC0D: testDBAgent::test_updateArgAddTime_t() (testDBAgent.cc:594)
==18336==    by 0x4E7E26C: ??? (in /usr/lib/libcutter.so.0.1.0)
==18336==    by 0x4E7449F: ??? (in /usr/lib/libcutter.so.0.1.0)
==18336==    by 0x4E7455D: cut_test_case_run_with_filter (in /usr/lib/libcutter.so.0.1.0)
==18336==    by 0x4E7C2F4: ??? (in /usr/lib/libcutter.so.0.1.0) …
=> [test][DBAgent] Fix the access to unitialized variable.

server/common/Monitoring.h, server/src/Makefile.am, server/src/SelfMonitor.cc, server/src/SelfMonitor.h, server/test/Makefile.am, server/test/testSelfMonitor.cc
The purpose of this class is to replace the self monitoring feature
which ArmUtils is currently in chage of. The implementation si ArmUtils
is a little complicated and it is hard to propagate status change among
self monitors. This new class is newly designed to addresses these problem.
****
The proposed code is identical to the one in the previous PR. It was just rebased.
=> [server][SelfMonitor] Add a new class to monitor Hatohol internals (＃1745)

client/static/js/hatohol_connector.js
The previous implementation never show any message and doesn't
happen anything after the login button is puressed when the
Hatohol server is down.
Although it has the basic mechasim to show the message.
However, it's never been performed due to the exception at
$.parseJSON() with an empty data.
However, parsing the response data has been meaningless,
because parseLoginResultWithError() is called only when
the HTTP respose is NOT 200 (OK).
This patch simply show an error message when this method
is called back.
=> [WebUI] Show an error message when Hatohol server is not working (#1581)

server/src/FaceRest.cc, server/test/testFaceRestUser.cc
The failure of login to Hatohol Server is not HTTP error.
So we should return Code 200.
=> [server] Return HTTP code 200 on login failure. (#1581)

server/common/Utils.cc, server/common/Utils.h, server/src/HatoholArmPluginGateHAPI2.cc, server/src/HatoholArmPluginGateHAPI2.h, server/test/testHatoholArmPluginGateHAPI2.cc, server/test/testSelfMonitor.cc
The self monitoring feature by ArmUtils makes code complicated and
hard to change the status depending on the other monitors.
This patch uses the newly desgined self monitroing SelfMonitor which
address the above problems.
Patch also added one self monitoring target. The class has the
following four self monitors in the result.
(1) Internal Error (Plugin)
(2) Parse Error of JSON object from a plugin
(3) Internal Error (HatoholArmPluginGateHAPI2)
(4) Broker connection
Note: (4) is not working correctly. I will address that (#1778).
****
This is a revised version of #1790, #1794
=> Use SelfMonitor instead of ArmUtils (#1745)

client/static/css/hatohol.css, client/viewer/events_ajax.html
In the previous implementation the check box is placed in
"change-incident-container" which isn't shown when no incident
tracking system exists. But the check box should always be shown
because it's not concerned with incidents.
=> [EventsView] Fix a bug that "Abbreviate Event Descriptions" check box isn't shown by default

server/hap2/hatohol/test/TestZabbixApi.py, server/hap2/hatohol/test/test_urllib2.py, server/hap2/hatohol/zabbixapi.py
* "state" property of trigger object isn't supported by Zabbix 2.0.
In addition, it's not suitable propery to determine trigger's
state, we should use "value" property instead. See the following
page for more details:
https://www.zabbix.com/documentation/2.2/manual/api/reference/trigger/object
* In Zabbix 2.0, array of property for "selectHosts" on getting
events isn't supported:
https://www.zabbix.com/documentation/2.0/manual/appendix/api/event/get
Instead require hosts on getting triggers.
Fix #1799
=> [hap2_zabbix_api] Enable to work with Zabbix 2.0

.travis.yml
Because pip fails to build it on the new TravisCI infrastructure
(sincde Dec. 2015).
=> [travis] Use apt-get instead of pip to install MySQLdb of python

server/mlpl/test/testLogger.cc
It might be lucky. The test of syslogoutput() succeeded.
And because this patch is considered that the test does not degrades, I sent a PR.
https://travis-ci.org/project-hatohol/hatohol/builds/95976552
=> [mlpl] Fix the failure of syslogoutput.

server/src/IncidentSenderManager.cc, server/src/IncidentSenderManager.h, server/src/RestResourceHost.cc
Revise #1812
In the previous code RestResourceHost doesn't return error when
it fails to update an incident that doesn't have valid incident
tracker. This patch fixes the issue.
Fix #1589
=> [RestResourceHost][IncidentSenderManager] Report error on updating incident

server/mlpl/test/testLogger.cc
In many system including TravisCI, messages logged by syslog() are
buffered by the default setting. To make sure the flush of the
logged message, this patch restarts rsyslogd.
=> [mlpl][test] Flush logging message before the check.

server/hap2/hatohol/haplib.py, server/hap2/hatohol/test/TestStandardHap.py
The actual object and the expected one should be compared.
However, previous code uses assertTrue(), which would be
wrongly written.
=> Fix test standard hap

server/common/AMQPConsumer.cc
```log
AMQPConsumer.cc:108:47: warning: if statement has empty body [-Wempty-body]
if (m_impl->m_connection->startConsuming());
^
AMQPConsumer.cc:108:47: note: put the semicolon on a separate line to silence
this warning
1 warning generated.
```
=> [AMQPConsumer] Suppress empty-body warning take 2

server/src/DBTablesUser.cc, server/src/OperationPrivilege.cc, server/src/OperationPrivilege.h, server/src/RestResourceUser.cc, server/test/DBTablesTest.cc, server/test/testDBTablesAction.cc, server/test/testDBTablesConfig.cc, server/test/testDBTablesUser.cc, server/test/testFaceRestUser.cc, server/test/testHatoholArmPluginGateHAPI2.cc, server/test/testOperationPrivilege.cc, server/tools/hatohol-def-src-file-generator.cc
Revise #1824.
Suppress the following compile time warnings:
OperationPrivilege.h:115:37: warning: 'ALL_PRIVILEGES' defined but not used [-Wunused-variable]
const static OperationPrivilegeFlag ALL_PRIVILEGES =
In addition, remove an unused variable.
=> [OperationPrivilege] Move ALL_PRIVILEGES & NONE_PRIGILEGE into OperationPrivilege class

server/src/ActorCollector.cc, server/src/ArmRedmine.cc, server/src/ConfigManager.cc, server/src/DB.cc, server/src/DB.h, server/src/DataStoreManager.cc, server/src/IncidentSender.cc, server/src/IncidentSenderManager.cc, server/src/ThreadLocalDBCache.cc, server/src/UnifiedDataStore.cc
Related to #1233.
This PR does not include replacing  `HatoholArmPluginGate.cc` because this file is for HAP1.
And `DBTables.(cc|h)`'s AutoMutex are not replaced with `std::lock guard<mutex>` because it causes following internal compiler error:
```log
testDBTables.cc: In function 'void testDBTables::test_tableInitializer()':
testDBTables.cc:210:2: internal compiler error: in create_tmp_var, at gimplify.c:479
};
^
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
```
=> [C++11][server] Replace AutoMutex with std::lock guard<mutex>

client/static/js/hatohol_modal.js
We will replace HatoholDialog that uses jQuery-UI with
HatoholModal by bootstrap's Modal. This patch is a mimimum
implementation to realize a reconnect modal, which will be
merged later.
***
This is a fixed version of #1829.
=> [WebUI] Add the first implementation of HatoholModal.

client/static/js/hatohol_reconnection_modal.js
This class shows a modal on which retry countdown is performed.
***
This is a fixed version of #1833. The difference is the following.
- Use gettext() for messages.
- Revise the title string: Connection Failure -> Connection Error
=> [WebUI] Add a new class HatoholReconnectionModal.

server/common/HatoholError.cc, server/common/HatoholError.h, server/src/RestResourceHost.cc, server/src/RestResourceHost.h, server/test/DBTablesTest.cc, server/test/DBTablesTest.h, server/test/testFaceRestHost.cc
Following two parameters are required to post an incident:
* unifiedEventId
* incidentTrackerId
Parameters of the incident are generated from the specified event.
For issue #681
=> [RestResourceHost] Implement POST method for incident

server/src/SelfMonitor.cc, server/src/SelfMonitor.h, server/test/testHatoholArmPluginGateHAPI2.cc, server/test/testSelfMonitor.cc
Previously, the host name is not correctly shown in WebUI.
This patch shows it as "(self-monitor)".
=> [server] Register a host for self monitor (#1836).

client/static/js/events_view.js, client/static/js/hatohol_events_view_config.js
Related to #1834.
If users set up following custom incident labels,
Incident filter candidates are shown like this:
=> [EventsView] Apply user-defined incident labels to filer settings candidates

client/static/js/events_view.js, server/src/RestResourceHost.cc
Revise #1855 to fix https://github.com/project-hatohol/hatohol/pull/1855#discussion_r48215942
When Hatohol server doesn't register an incident for an event, Hatohol client can't update the status of
the incident. This patch fixes this issue by posting a new incident before changing it's status.
Currently this feature is enabled for INCIDENT_TRACKER_HATOHOL only.
When other type of incident trackers are enabled, the feature that changing incident status isn't enabled.
=> [EventsView] Enable to post new incident

server/data/Makefile.am, server/data/actions.sql, server/data/incident-trackers.sql, server/tools/hatohol-db-initiator.in
To make it easy to use the incident feature of Hatohol, insert an incident tracker and
an incident sender action by default.
=> [hatohol-db-initiator] Add a default incident sender

server/src/HatoholArmPluginGateHAPI2.cc, server/src/SelfMonitor.cc, server/src/SelfMonitor.h, server/test/testSelfMonitor.cc
Some monitoring items don't have the status. They detect some issues
discontinuously. The concept trigger is not suitable form them.
This patch adds a new working mode: STATELESS_MONITOR. Monitors
with the mode mainly generates events.
Thie PR also includes the patch that makes the following two self monitors STATELESS_MONITOR.
- monitorGateInternal
- monitorParseError
In addtion, some errors are saved as event. As a result, they
are shown in WebUI.
=> Make some self monitors stateless.

client/static/css/hatohol.css
Since the style of '.checkbox input[type="checkbox"]' has been
changed in the latest Bootstarp, the layout of the checkbox in the
server edit dialog is broken. This commit fixes the issue.
Fix #1874
=> [HatoholServerEditDialog] Fix the position of check boxes

server/hap2/hatohol/hap2_ceilometer.py, server/hap2/hatohol/hap2_fluentd.py, server/hap2/hatohol/hap2_nagios_ndoutils.py, server/hap2/hatohol/hap2_zabbix_api.py, server/hap2/hatohol/standardhap.py
'hap' is defined as a global variable and it overwrites the package
with the same name. This patch addresses it by removing the global
variable.
=> [Hap2] Resolve global variable name collision.

server/src/HatoholArmPluginGateHAPI2.cc
This PR contains
- a new self monitor for HAP2 connection
- making the plugin internal monitor stateless
=> Fire self monitor on timeout #1590

server/hap2/hatohol/hap2_ceilometer.py, server/hap2/hatohol/hap2_fluentd.py, server/hap2/hatohol/hap2_nagios_ndoutils.py, server/hap2/hatohol/hap2_zabbix_api.py
The previous code, __name__ of hap_zabbix_api.py and the family
is replaced with  '__main__'.
The default logging setting: hap2-logging.conf has the following
line to specify the logging target.
qualname: hatohol
As a result, their logging APIs are not loggged.
=> [hap2] Give a logger name prefix 'hatohol.' (#1876).

client/viewer/urls.py
Previous implementaion returns the content that is the same
as ajax_dashboard when the top page is requested. In this
case, a browser looks that the url /hatohol has the contents.
And if the login dialog is shown at that time, the JavaScript
code saves the session ID in the cookie for the page.
with the path: '/'.
However, the login dialog is shown at other pages such as
/hatohol/ajax_events, the path in the cookie is '/hatohol'.
Thus the two cookies are saved and the wrong (expired) one
may be used.
This patch ensures that all contents (pages) of WebUI are
under /hatohol.
=> [WebUI] Redirect the top page to ajax_dashboard. (#1761)

client/static/js/hatohol_monitoring_view.js, client/static/js/latest_view.js, client/static/js/overview_items.js, client/static/js/overview_triggers.js, client/static/js/triggers_view.js, client/viewer/events_ajax.html, client/viewer/latest_ajax.html, client/viewer/overview_items_ajax.html, client/viewer/overview_triggers_ajax.html, client/viewer/triggers_ajax.html
Although we use "---------" as the label of the wild card item
of each filters, it's not shown since we upgrade jQuery in our
repository.
The cause is that HatoholMonitoringView.setupHostFilters() tries
to set a wrong value to the drop down menu when the wild card item
is selected.
This commit fixes the issue.
=> [client] Set the correct label for the wild card item of filters 

server/hap2/hatohol/zabbixapi.py
I'm not sure the culture of exception treating in Python, but I think that it is useful to define used-defined exception for representing AuthenticationError.
After applied this patch, Hatohol WebUI reports more concrete error type like this:
=> [hap2][zabbixapi] Use user-defined authentication exception

client/conf/locale/ja/LC_MESSAGES/djangojs.po, client/static/js/hatohol_reconnection_modal.js
Generally "sec." means "Byou" in Japanese. However it is being used as
"Byougo" in the context.
=> [WebUI] Use msgctxt of gettext for a little complicated usage. (#1904)

client/static/css/hatohol.css, client/static/js/hatohol_item_selector.js, client/viewer/history_ajax.html
Related to #1918.
For too long item elements, I've added popover for them as follows:
=> [WebUI] Fix overflow elements in graph settings

client/static/js/severity_ranks_view.js
重要度設定のプレースホルダーが新デザインのマージの時からなくなってしまっていた。これを修正。
修正は大したことがないのですが、これは意図したデザインかどうかがわからないので @BlueSkyDetector さんあたりに目を通して頂きたいです。
=> [SeverityRanksView][server] Reactivate placeholder in severity ranks view

client/viewer/history_ajax.html
In Graph settings, following `server-item` selector wrongly selected:
This PR fixes as follows:
Similar PR is #1893.
=> [16.01][HistroyView][Graph] Fix default option in graph settings modal

doc/server/hap2/HowToUse.md
* Add `rabbitmq-server` installation document
* For CentOS 7, add `erlang` and `rabbitmq-server` installation 
* Add `rabbitmq-server` settings document
* Add hap2 plugins dependent Python packages installation document
* Add Tips for pitfail (mainly HAP2 Zabbix)
=> [HAP2][doc] Initial writing up HAP2 document

client/Makefile.am, configure.ac
Use msgfmt directly.
Fix #1939
=> [client] Don't require Django for compiling mo files

README.md, server/README.md
* Set supported CentOS version to 7
* Add built-in Hatohol incident tracker to supported tracking software
* Add `Zabbix 3.0` into supported monitoring software
* Remove Qpid releated packages installation and its server set-up descriptions
* Follow `hatohol-db-initiator` options change
* Should we remove Hatohol project repository descriptions? Unify json-glib installation way?
- CentOS 7 repository provides `json-glib` package.(Currently:  `json-glib-0.16.0-3.el7.x86_64.rpm`). 
* Should we add `librabbimq-devel` and `rabbitmq-server` setting-up descriptions for CentOS 7?
=> [16.01][server][README] Update readme

hatohol.spec.in, wercker.yml
It got success building Hatohol rpms in Wercker: https://app.wercker.com/#buildstep/569c71813e708cf423045b51
=> [spec][wercker] Remove Django build require from hatohol package in spec

server/src/DBTablesConfig.cc
Because the table doesn't exist in the previous version (15.06).
=> [DBTablesConfig] Remove update procedures for severity_ranks table

client/static/js/triggers_view.js, client/viewer/triggers_ajax.html
It would be nice to use user-defined severity rank labels in TriggersView.
By default: 
Also displaying user-defined severity ranks labels:
=> [TriggersView] Use user-defined severity rank labels

package.json
Bump up casperjs semantic version to 1.1.0-beta4.
=> [npm] Use caperjs 1.1.0-beta4 explicitly

client/viewer/events_ajax.html
=> [EventsView] Fix broken clear button in time range filter

client/HowToTest.md, client/test/Makefile.am, configure.ac
Use package.json to install node modules.
You can install them by executing the following command at the top
directory:
$ npm install
Fix #2008
=> [client] Simplify setting up test environment for JavaScript

client/static/js/utils.js
We should use `var` for local variables and use `;`(semicolon) in end of line.
`var` has an effect to make narrowing variable scope.
`;`(semicolon) is needless for ordinary JavaScript codes, but it is needed for minifying them.
=> [client][js][utils] Add missing 'var's and semicolons

client/test/browser/test_triggers_view.js
As the comment in the patch, some platform generates a space
character just after a sytle property in a tag. This patch
address the problem by comparing a HTML generated by the testee
code with the expected string by match() method based on
regular expression.
In addition, the send patch clean up the position of line breaks.
=> Allow a little difference due to platform #2009

.jshintrc, Gulpfile.js, package.json
I've tried to add gulp lint task.
This task will be invoked by `$(npm bin)/gulp lint` after executing `npm install`.
How about start to use Gulp?
Related to https://github.com/project-hatohol/hatohol/pull/2026#issuecomment-183178893.
=> [gulp][lint][js] Start to use gulp lint task

client/static/js/hatohol_reconnection_modal.js
* Remove redundant semicolon
* Break a long line
* Use === instead of == for rigid comparison
Related to #2028.
=> [HatoholReconnectionModal][Lint] Fix lint errors

Gulpfile.js
Currently, default reporter does not return non zero exit status even if there are lint errors.
This PR introduces fail reporter to report them with exit status.
Because exit status is useful for CI task.
=> [Gulpfile] Add fail reporter to report lint errors

client/test/browser/index.html, client/test/browser/test_events_view.js, client/test/browser/test_latest_view.js, client/test/browser/test_server_view.js, client/test/browser/test_triggers_view.js, client/test/browser/test_utils.js
This patch is one of preparations for addressing #1938, which
will remove legacy built-in Arms for Zabbix and nagios.
So the tests using them should be fixed to use those of HAPI2
version.
=> [WebUI][test][browser] Use HAPI2 plugins as test targets.

client/test/feature/feature_test_utils.js, client/test/feature/register_action_test.js, client/test/feature/register_incident_setting_test.js, client/test/feature/register_server_test.js, client/test/feature/register_user_access_info_test.js
This patch is one of preparations for addressing #1938, which
will remove legacy built-in Arms for Zabbix and nagios.
So the tests using them should be fixed to use those of HAPI2
version.
=> [WebUI][test][feature] Use HAPI2 plugins as test targets.

setup-with-ansible/roles/upgrade-server/ubuntu/tasks/main.yml
Some simple environment such as a container soon after created
is required to have 'aptitude' to progress this setup.
=> [setup-by-ansible] Install aptitude first.

setup-with-ansible/roles/toolchain/redhat/tasks/main.yml, setup-with-ansible/roles/toolchain/redhat7/tasks/main.yml
Some simple environment such as a container donesn't have 'make'
by default.
=> [setup-by-ansible] Install make. (#1964)

Gulpfile.js, client/test/browser/index.html, package.json, test/run-client-test.sh
This PR makes to be able to run client test through gulp with `$(npm bin)/gulp browsertest`.
It would be nice to unify executing testing/linting interface.
=> [Gulp][client][browsertest] Use gulp-phantomjs to unify testing/linting task interface

client/static/css.external/bootstrap-select.css, client/static/js.external/bootstrap-select.js, client/static/js/triggers_view.js, client/test/browser/index.html, client/viewer/base_ajax.html, client/viewer/triggers_ajax.html
Related to #2040.
I've tried to use bootstrap-select to provide live-search for selectboxes elements.
Live-search is useful for many monitoring servers, hosts, and hostgroup and so on.
Appearance will become like this:
And live-search feature works like this:
=> [TriggersView] Try to use bootstrap-select for live-search

client/static/js/utils.js
Because I get often following error in development environment:
```
TypeError: plugin is undefined
addPriority() utils.js:128
sortByPriority() hatohol_server_edit_dialog_parameterized.js:201
replyCallback() hatohol_server_edit_dialog_parameterized.js:147
request/<.success() hatohol_connector.js:197
n.Callbacks/j()
...
```
Thus, we should validate `plugin` object not to be undefined.
`plugin` object has a possibility to be undefined.
How do you think of that, @Mnakagawa ?
=> [client][utils] Validate plugin object

test/run-client-test.sh
Revert #2056 partially.
This reverts commit 8bdb6823739a51e6e303c4cc278cf79fbc795dab.
In Travis CI, `gulp browsertest` is too fragile.
We should use mocha-phantomjs directly.
=> Revert "[test][client] Use gulp to run client test"

client/static/js/events_view.js
Related to #2044.
Take 2 #2086.
=> [EventsView] Use a magic comment to suppress lint too long line error

server/src/RestResourceHost.cc, server/test/testFaceRestHost.cc
This PR contains `hostname` version of beyond server filter.
But for now, it accept only one `hostname` in query.
=> [RestResourceHost][Triggers] Retrive hostname param

server/test/FaceRestTestUtils.cc
Many tests fail on Ubuntu 15.10 due to this bug.
=> [test][FaceRestTestUtils] Fix invalid memory reference

server/hap2/hatohol/hap.py
1b9e0c8f79a5560ac4b5afd059ed999d11b0efc7 is mistaken
=> [hap] Revert hap.py import sentence

client/static/js/latest_view.js, client/test/browser/test_latest_view.js, doc/server/rest-api/items.rst, hatohol.spec.in, server/common/Monitoring.h, server/src/DBAgent.h, server/src/DBAgentMySQL.cc, server/src/DBAgentMySQL.h, server/src/DBAgentSQLite3.cc, server/src/DBAgentSQLite3.h, server/src/DBTablesMonitoring.cc, server/src/DBTablesMonitoring.h, server/src/HatoholArmPluginGateHAPI2.cc, server/src/HatoholDBUtils.cc, server/src/RestResourceHost.cc, server/src/UnifiedDataStore.cc, server/src/UnifiedDataStore.h, server/test/DBTablesTest.cc, server/test/Helpers.cc, server/test/testDBAgent.cc, server/test/testDBTablesMonitoring.cc, server/test/testHatoholArmPluginGateHAPI2.cc, server/test/testHatoholDBUtils.cc, server/test/testHostResourceQueryOptionSubClasses.cc, server/test/testUnifiedDataStore.cc
Previosly, the HAPI2.0 interface implementation of Hatohol server
has accepted only the first item group (which calls it application in
ZABBIX) and drops the followed ones. This patch enables multiple
item groups to be handled properly.
To realize this feature, this patch adds the followings.
- adds a new table: item_categories instead of items.item_group_name
which can have only one group name.
- 'itemGroupName' and 'applications' in FaceREST request are replaced
'itemGroupNames' and 'ItemGroups' respectively for improving readability.
Note: The item groups (itemGroups) is called item categroy (itemCategory)
in Hatohol sever code to avoid confusion with the class ItemGroup already
existing, which is a generic container for ItemData.
=> Accept and stores multiple itemGroups (#1765).

client/static/js/hatohol_monitoring_view.js, client/static/js/triggers_view.js, client/viewer/triggers_ajax.html
This PR adds a feature which is the initial implementation beyond monitoring server filter for hostname.
`hostname` select box is newly added like this:
And this select box is always selectable:
=> [WebUI][TriggersView][BeyondMonitoringServerFilter] Add beyond monitoring server filter for hostname

server/hap2/hatohol/hap2_fluentd.py, server/hap2/hatohol/test/TestHap2Fluentd.py
This major purpose of this patch is to log the message from
fluentd (td-agent) itself including error information.
This is an example of logging result. The messages w/ an unxpected
format are marked with '%%'.
<pre>
2016-03-03 13:35:20,352    ERROR [23289] hatohol.hap2_fluentd:hap2_fluentd.py:160:  %% 2016-03-03 13:35:20 +0900 [info]: adding filter pattern="hatohol.**" type="record_transformer"
2016-03-03 13:35:20,352    ERROR [23289] hatohol.hap2_fluentd:hap2_fluentd.py:160:  %% 2016-03-03 13:35:20 +0900 [info]: adding match pattern="hatohol.**" type="stdout"
2016-03-03 13:35:20,352    ERROR [23289] hatohol.hap2_fluentd:hap2_fluentd.py:160:  %% 2016-03-03 13:35:20 +0900 [info]: adding source type="tail"
2016-03-03 13:35:20,353    ERROR [23289] hatohol.hap2_fluentd:hap2_fluentd.py:160: …
=> [hap2] Log message w/ unexpected formats. (#2010)

client/static/js/triggers_view.js
Refresh button has been broken since introducing `bootstrap-select` against selectboxes in triggers view.
=> [TriggersView] Refresh bootstrap-select's selectpickers correctly

server/hap2/hatohol/hap2_fluentd.py
Using raw string makes the regular expression very short.
=> [hap2_fluentd] Use more simple notation.

server/src/ArmBase.cc, server/src/ArmBase.h, server/src/ConfigManager.cc, server/src/ConfigManager.h, server/src/DBTablesConfig.cc, server/src/DBTablesConfig.h, server/src/DataStore.cc, server/src/DataStore.h, server/src/DataStoreFake.cc, server/src/DataStoreFake.h, server/src/UnifiedDataStore.cc, server/src/UnifiedDataStore.h, server/src/main.cc, server/test/testConfigManager.cc, server/test/testDBTablesConfig.cc, server/test/testFaceRestIncident.cc, server/test/testFaceRestMonitoring.cc
It's not used in the current code.
This commit doesn't remove enable_copy_on_demand column in the DB
to avoid troublesome migration.
Fix #2142
=> [server] Remove unused options "--{enable,disable}-copy-on-demand"

server/src/DBTablesHost.cc, server/src/DBTablesHost.h, server/src/RestResourceMonitoring.cc, server/src/RestResourceMonitoring.h, server/src/RestResourceUtils.cc, server/src/RestResourceUtils.h, server/src/UnifiedDataStore.cc, server/src/UnifiedDataStore.h, server/test/testDBTablesHost.cc, server/test/testFaceRestMonitoring.cc
* DBTablesHost
* implement getServerHostGrpSetMap to get ServerHostGrpSetMap with specified option condition
* RestResourceMonitoring
* retrieve `hostgroupName` option and use it for beyond monitoring server filter
* testFaceRestMonitoring
* partially refactored with StringMap to reduce assertion static method arguments 
- Let's prevent more and more adding arguments into `_assertTriggers`
=> [RestMonitoring][DBTablesHost] Receive hostgroup name query in REST trigger API

client/static/css/hatohol.css, client/static/js/events_view.js, client/test/browser/test_events_view.js, client/viewer/events_ajax.html
#1991 【イベント画面で概要を短縮した時、他の行が折り返されない範囲で、概要になるべく列幅を割り当てたい】
フロントエンド実装です。
=> [WebUI:events] Description Shorten

configure.ac, server/common/Params.h, server/mlpl/src/Reaper.h
Because --disable-cpp11 doesn't work anymore.
We alywas use C++11.
=> [configure] Remove "--enable-cpp11" switch

server/src/DBTablesMonitoring.cc, server/src/DBTablesMonitoring.h, server/test/testDBTablesMonitoring.cc
* Add DBTablesMonitoring::getTriggerBriefList readonly DB API to retrieve trigger briefs
=> [DBTablesMonitoring] Implement retriving trigger briefs

client/static/js/hatohol_add_action_dialog.js
Revise #2146
In the previous code the trigger status is always set to "ANY"
when a user edit an existing incident setting.
This commit fixes the issue by discarding the special treatment
for the incident setting.
Fix #2007
=> [HatoholAddActionDialog] Fix trigger status bug in incident setting dialog

client/test/browser/test_triggers_view.js
The test 'With a problem trigger' fails on certain environments.
The cause is that the test expects a fixed HTML string although
it's modified by jQuery dynamically.
To resolve it, we assert only existence of "severity5" class and
backgroud color in this test. Because other parameters are tested
in other tests, we don't need test them in this test.
Fix #2009
=> [tset][TriggersView] Fix an issue that a test fails on certain environments

hatohol.spec.in
Users sometimes want to save the previous settings.
With %config in RPM's spec. file, they are saved when the RPM
is removed.
=> Use %config for configuration files in RPMs.

server/common/Monitoring.h, server/src/DBTablesMonitoring.cc, server/src/DBTablesMonitoring.h, server/src/IncidentSenderHatohol.cc, server/src/RedmineAPI.cc, server/src/RestResourceMonitoring.cc, server/test/DBTablesTest.cc, server/test/Helpers.cc, server/test/testDBTablesMonitoring.cc, server/test/testDBTablesMonitoring.h, server/test/testFaceRestIncident.cc, server/test/testFaceRestMonitoring.cc, server/test/testFaceRestSummary.cc, server/test/testIncidentSenderHatohol.cc, server/test/testIncidentSenderManager.cc, server/test/testIncidentSenderRedmine.cc
It makes easy to get number of comments belongs to an incident.
https://github.com/project-hatohol/hatohol/issues/2119#issuecomment-195845731
=> [RestResourceMonitoring][DBTablesMonitoring] Add "commentCount" property to indeint object

client/Makefile.am, client/conf/webui.conf, client/hatohol/autotools_vars.py.in, client/hatohol/base_settings.py, client/hatohol/hatoholserver.py, client/test/python/TestHatoholserver.py, configure.ac, hatohol.spec.in
*** This is a fixed version of #2174 ***
Django framework provides a way to set some parameters such as
database server and the port. However, it's a python file and
hard to be edited by users.
So this patch adds a mechanism to try to read a configuration file
under the sysconfdir given by autoconf.
=> Webui use conf file for settings #2152 5

client/static/css/hatohol.css
#2040 でデザインの相談を　@ucksts さんに相談していたのでそれを実現してみました。
* 天地方向のフィルタ要素のbottom-merginの調整(20px→12px)
* 下位が選択できないことをグレーに準ずる色で表現
ただし、以下の修正はcssへは適用していません。
* セレクトボックス同士の間隔を20px確保する。
bootstrap-selectの機能(data-width="50%")ですでにセレクトボックス同士の間隔が20px以上確保されているからです。
=> Apply issue #2040 design advice

client/static/css/hatohol.css
#2005 
『フィルタの絞り込みエリアがもう少し小さくてもよいのではないか？』
項目名行間調整。
CSSのみ。
項目名要素のpタグの行間を文字サイズの１倍（line-height:100%）とし、上下揃えを中央（vertical-align:middle）とした。
vertical-alignはtable-cell要素内のみ適用されるため、当該pタグをtable-cellとした。
table-cellはtableまたはinline-table内のみtable-cellとして振る舞うため、pタグの親である.filter-elementをinline-tableとした。
本来ならば#hideDivそのものをdisplay:tableとしてしまうのが安定するが、イベント・トリガーともにHTML構造が大きく変わってしまうこと、.filter-elementがdisplay:inlineで表示が安定していることから、display:inline-tableを採用している。
=> [WebUI:events] adjust filter box line-height

client/conf/locale/ja/LC_MESSAGES/djangojs.po, client/static/js/events_view.js, client/test/browser/test_events_view.js
I think, 'Period' is incorrect.
The following is after changing.
=> [client] Fix Period to 'Date and time'

server/hap2/hatohol/hap.py
[hap2] Show initial hatohol's logging messages.
Recently hap2 code uses logger instances with name: hatohol.*.
In this case, we need to call setLevel for the logger instance
(not handler) in order to change the logging level.
So the previous implementation drops log messages issued by
logger.info() before setup_logger() is called.
****
This is a fixed version of #2192
=> Show initial info message 2

configure.ac, hatohol.spec.in, server/hap2/Makefile.am, server/hap2/hap2.conf.in, server/hap2/hatohol/autotools_vars.py.in, server/hap2/hatohol/hap.py, server/hap2/hatohol/standardhap.py, server/hap2/setup_common.py
Previously plugins need many command line arguments such as paramters to connet w/ AMQP brokers. This patch provides a feature in which they are given by the configuration file.
****
This is a fixed version of #2193
=> Hap2 conf 5

client/static/js/events_view.js, client/test/browser/test_events_view.js
It is temporary commit.
After release 16.04, we add new API to Hatohol server and re-display this column.
Related: #115
=> [client][event_view] Hide duration column

client/static/js/events_view.js
Abbreviating event descriptions is implemented by CSS in the current
implementation.
=> [EventsView] Remove needless code

server/test/testFaceRestIncident.cc
This variable has been left since this commit: https://github.com/project-hatohol/hatohol/commit/48c950c0ea8d9fbb5162d91208cb00576d3d4901#diff-85b92f69fd18823fb7079177939e0583
Previously, cut_teardown needs to tidy up CopyOnDemand releated
settings.
But current implementation does not use CopyOnDemand related code.
It had been removed completely at #2143.
=> [FaceRestIncident][test] Suppress a unused variable warning

client/static/js/servers_view.js, client/test/browser/test_server_view.js, client/viewer/servers_ajax.html
Recently built-in monitoring types are removed from Hatohol server.
As a result no monitoring type provides "Hostname" and
"IP Address" properties. So we should remove these columns.
Fix #2205
=> [ServersView] Remove unused columns

server/hap2/hatohol/test/TestStandardHap.py
The test has replaced sys.argv to hide some unittest arguments
and use a transporter for test (EzTransporter).
A recent chagange for ConfigFileParser added the partial parse
of the argument in the constructor of StandardHap. It is done
before the replacement of sys.argv. It may cause an unexpected
parse result.
This patch replaces sys.argv before it's parsed.
=> [Hap][test] Fix the broken test. (#2222)

client/static/js/events_view.js, client/static/js/hatohol_navi.js, client/static/js/hatohol_tracer.js, client/static/js/hatohol_user_profile.js, client/static/js/triggers_view.js, client/static/js/utils.js, client/test/browser/index.html, client/test/browser/test_hatohol_tracer.js, client/viewer/base_ajax.html
This patches provide a feature that calls back listers when the prefixed
trace points are invoked.
The motivation of this feature is to solve the problem #2052, in which
the intended page transition should be distinguished and allowed.
=> Hatohol tracer

client/static/js/before_close.js, client/viewer/base_ajax.html
#2052 【[WebUI] ブラウザクローズの誤操作防止】
HatoholTracePoint.PRE_HREF_CHANGE 参照型
https://github.com/project-hatohol/hatohol/pull/2206
からの文言修正。
いただいたプレビュー環境を破損してしまったため、別branchにてpush。
=> [WebUI:All page] Close defender with hatohol-tracer

client/static/js/graphs_view.js, client/static/js/hatohol_navi.js, client/static/js/latest_view.js, client/static/js/triggers_view.js, client/static/js/utils.js, client/test/browser/test_graphs_view.js, client/test/browser/test_hatohol_navi.js, client/test/browser/test_latest_view.js, client/test/browser/test_triggers_view.js, client/test/browser/test_utils.js
Some links in WebUI such as menu items should not open an another a window
or a tab in order to prevent an expected situation.
This PR realizes it by forcing its own page transition method domesticLink().
NOTE: This is the fixed version of #2229
=> [WebUI] Prevent internal links from opening on a new window

client/static/js/history_view.js, client/viewer/graphs_ajax.html, client/viewer/latest_ajax.html
This pull request prevents the page transition confirmation from showing,
which has been leaked since the mechanism was taken.
=> Add missing domestic links #2235

server/src/HatoholArmPluginGateHAPI2.cc
I've noticed this confusing usage by this comment: https://github.com/project-hatohol/hatohol/pull/2247#discussion_r59320498
=> [HatoholArmPluginGateHAPI2] Use CountablePtr wrapped variable correctly

client/static/js/servers_view.js
Currently, the function is broken. We can not fix it till 16.04 release.
It is temporary commit till 16.12 and later release.
=> [client][server_view] Hide bulk upload button

server/hap2/hatohol/hap2_ceilometer.py, server/hap2/hatohol/hap2_nagios_ndoutils.py, server/hap2/hatohol/hap2_zabbix_api.py, server/hap2/hatohol/hapcommon.py, server/hap2/hatohol/simple_caller.py, server/hap2/hatohol/simple_server.py, server/hap2/hatohol/transporter.py
Let's use `HAPI2` notation.
ref: https://github.com/project-hatohol/HAPI-2.0-Specification/pull/80/files#diff-04c6e90faac2675aa89e2176d2eec7d8R5
=> [hap2] Unify "HAPI2" notation

doc/server/hap2/HowToUse.md
Add a necessary command for install a package and a description for BrokerURL 
For using "Zabbix (HAPI2)" as monitoring server type, I had to install
hatohol-hap2-zabbix. And I thought some description was necessary for
BrokerURL, so I add it and an example.
=> 16.04 releng/tsatoh hap2 doc

server/hap2/hatohol/haplib.py
```log
return ->
raise
```
`return` and `raise` are confusable appearance... :cold_sweat:
=> [hap2] Fix a typo

server/hap2/hatohol/hap2_nagios_ndoutils.py
Some users want to change DB listening port from 3306 and it should
convert parsed port variable's type into `int` from `str`.
Otherwise, the following exception is raised:
```log
Plugin Error: <type 'exceptions.TypeError'>, an integer is required
```
=> [hap2] Convert ndoutils port number correctly

server/hap2/hatohol/hap2_nagios_livestatus.py
`mk_livestatus` uses `socket` module internally.
It uses `socket#connect` like this: https://github.com/arthru/python-mk-livestatus/blob/master/mk_livestatus/livestatus.py#L58-L61
`socket#connect` seems to require `("ip address", integer value of port_number)` tuple: https://docs.python.org/2.7/howto/sockets.html#creating-a-socket.
We should fix it by similar approach like #2292.
=>  [hap2][nagios-livestatus] Convert ndoutils port number correctly

setup-with-ansible/roles/libraries/redhat7/tasks/main.yml
CentOS 7 has `epel-release` package in base.
=> [ansible][centos7] Use epel-release package in base

server/hap2/hatohol/hap2_nagios_ndoutils.py
hap2_nagios_ndoutils.py complains the following flood of errors:
```log
ERROR:hatohol.hap:hap2_nagios_ndoutils.py:Poller:hap.py:96:26318:Unexpected error: <type 'exceptions.NameError'>, global name 'log' is not defined
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/hatohol/haplib.py", line 1123, in __poll_in_try_block
self.poll()
File "/usr/local/lib/python2.7/dist-packages/hatohol/haplib.py", line 1066, in poll
action()
File "/usr/local/libexec/hatohol/hap2/hatohol/hap2_nagios_ndoutils.py", line 374, in poll_events
self.collect_events_and_put()
File "/usr/local/libexec/hatohol/hap2/hatohol/hap2_nagios_ndoutils.py", line 292, in collect_events_and_put
logger.warning("Unknown status: " + str(status))
NameError: global name 'log' is not defined
... …
```
=> [hap2][nagios_ndoutils] Fix global name is not defined error

client/static/js/history_view.js
Slightly related to #2078.
This PR fixes doubly requested graph drawing requests.
=> [HistryView][WebUI] Prevent doubly requested graph drawing requests

client/static/js/overview_triggers.js
overview_trigger page will handle user-defined severity colour like this:
=> [OverviewTrigger] Handle user defined severity color

client/static/js/events_view.js, client/static/js/triggers_view.js
This PR reduces potential issue that previous values are not to be stored in selectPickers.
But for now, I'm not sure what really causes this problem.... :/
=> [EventsView][TriggersView] Add missing selectPicker refreshing things

client/static/js/hatohol_history_loader.js
Dividing loadHistory request is now needless.
But applying this patch, still there is a problem pending GET history request.
=> [HatoholHistoryLoader] Stop to divide request loadHistory

client/static/js/hatohol_monitoring_view.js
This typo causes the problem that hostname query does not restore
correctly after filtering.
host'N'name should be hostname.
Otherwise, $("#select-hostname").val(query.hostName) sets empty string
into the specified selectbox.
=> [HatoholMonitoringView] Fix a wrong query name

server/hap2/hatohol/hap2_fluentd.py
With systemded hatohol server daemon, it runs by `root` user and `td-agent` does not added root's `PATH`.
Then, it causes following flood of warnings:
```log
May 17 12:59:21 localhost journal: hap2_fluentd.py:94 hatohol.hap2_fluentd:hap2_fluentd.py:Process-3: [28712]: [INFO] Started fluentd manger process.
May 17 12:59:21 localhost journal: standardhap.py:155 hatohol.standardhap:hap2_fluentd.py:Process-3: [28712]: [WARNING] Got SIGCHLD
May 17 12:59:31 localhost journal: hap2_fluentd.py:94 hatohol.hap2_fluentd:hap2_fluentd.py:Process-3: [28712]: [INFO] Started fluentd manger process.
May 17 12:59:31 localhost journal: standardhap.py:155 hatohol.standardhap:hap2_fluentd.py:Process-3: [28712]: [WARNING] Got SIGCHLD
May 17 12:59:41 localhost journal: hap2_fluentd.py:94 …
```
=> [hap2][fluentd] Use full path to `td-agent`

client/test/browser/test_events_view.js
Because the column is removed at #2354.
=> [WebUI][test][EventsView] Remove tests for "Current trigger status" column

client/static/js.plugins/hap2-zabbix.js, client/static/js/events_view.js, client/test/browser/test_hap2_zabbix.js, client/test/browser/test_latest_view.js, client/test/browser/test_utils.js
2.x uses a query as ”itemid=” but 3.0 uses "itemids[]=".
This PR resolve it to use the both in one URL.
=> [item][zabbix] Correspond to zabbix 3.0

server/hap2/hatohol/hap2_nagios_ndoutils.py
Currently, Hatohol server output the following message when get events from hap2_nagios_ndoutils.
```
[ERR] <ActionManager.cc:1626> Not found: svID: 17, trigID:
```
Because, Nagios events do not have trigger id.
The PR fix this problem.
=> [hap2_nagios_ndoutils] Fix a bug that is correct trigger_id is not registered

server/hap2/hatohol/hap2_ceilometer.py, server/hap2/hatohol/hap2_nagios_livestatus.py, server/hap2/hatohol/hap2_nagios_ndoutils.py, server/hap2/hatohol/hap2_zabbix_api.py, server/hap2/hatohol/haplib.py, server/hap2/hatohol/rabbitmqconnector.py, server/hap2/hatohol/test/TestHap2Ceilometer.py, server/hap2/hatohol/test/TestHap2NagiosLivestatus.py, server/hap2/hatohol/test/TestHap2NagiosNdoutils.py
When hap2 get request(ex. item, history) and monitoring target does not have data, HAP2 does not return nothing.
So, request become timeout. After apply this PR, request does not become by HAP2 return empty list(items, histories).
=> Put empty contents

configure.ac, server/Makefile.am, server/log/Makefile.am, server/log/hatohol-syslog.conf
This patch provides a syslogd configuration file to
save Hatohol server log into /var/log/hatohol/hatohol-server.log.
=> [server] Add a config file for syslog.

client/conf/locale/ja/LC_MESSAGES/djangojs.po, client/static/js/events_view.js
As reported in https://github.com/project-hatohol/hatohol/pull/2316,
The patch set breaks user fileter.
Note that date-time and some line information in djangojs.po conflicted.
They are just meta data and don't change behavior though.
I take the ones of HEAD.
=> Work for splitting #2370 revert 2

client/hatohol/base_settings.py
Because it's take too long time to fetch all items if many
monitoring servers & hosts are registered. We need a breakthrough
idea to revive it.
In this commit I uncomment a configuration "ENABLED_PAGES" in
client/hatohol/base_settings.py except "ajax_overview_items" to
disable the page, but it's may not proper way to do it. So way may
change the way in the future release.
=> Don't show "Overview : Items" page

client/static/js/servers_view.js, client/viewer/servers_ajax.html
This patch removes the Maps column in Monitoring servers page.
Because the page is for setting server's paramters and checking them,
using it as the gate to the map differents from the original
purpose of the page.
In addition, map is only provided by Zabbix. So showing it in the
common column will cause wasted spaces when Zabbix is not used.
=> [client][Servers] Remove Maps columns that is less useful.

server/log/Makefile.am, server/log/hatohol-arm-plugin2, server/log/hatohol-server
Now logs for hatohol server and arm plugins are being
stored in the private file. This patch provides setting files
for logrotate in order to prevent the large log from being crated.
=> [server][log] Setting files for logrotate.

client/static/js/dashboard_view.js
These two values are generally difficult to obtain efficiently.
So now they aren't used informative.
=> [client][dashboard] Remove Number of items and New values per second.

server/hap2/hatohol/hap2_nagios_ndoutils.py, server/hap2/hatohol/test/TestHap2NagiosNdoutils.py
The previous way get older data than the plugin is registered.
The volume of the data is possible to be gigantic. It may take
a long time to handle all of them, which is typicaly not urgent.
=> [hap2_nagios_ndoutils] Avoid a plugin from getting old data.

client/static/js/dashboard_view.js, client/static/js/latest_view.js, client/static/js/overview_items.js, client/static/js/overview_triggers.js, client/static/js/triggers_view.js
After the monitoring is stopped by pressing the 'Monitoring' button
in the navi bar, it isn't reverted on pressing the manual update
button just under it.
This patch fixed the problem.
=> [WebUI] Revert 'Monitoring' label correctly on manual update.

client/static/css/hatohol.css
Fix the worng format for the color in the CSS.
However, Google chrome (and probably other browsers) shows it in white,
which is much natural on the current design. So we hadn't noticed it.
=> [WebUI] Fix an invalid value for the color.

client/static/js/events_view.js
parseErrorCallback() needs two parameters. However, it had given
nothing. When an error happensi, the call back won't work properly.
=> [WebUI] Add missing parameter for parseErrorCallback()

client/static/js/events_view.js
There is a bug that makes it impossbile to edit comment after the
column order is changed. This patch fixes it.
=> [WebUI][EventsView] Work after the column order change (#2399)

client/static/js/servers_view.js
The current deleting/reloading confirmation dialog can be closed.
This patch disables closing due to the following two reasons.
- The time for the actions is not so long.
- Updating the information on the servers page asynchronously
sometimes makes users confused.
=> [WebUI][Servers] Make deleting/reloading confirmation dialog sync.

client/static/js/events_view.js
It's more natural to linking to the corresponding the event page
than the latest information of the event.
=> [WebUI][Events] Link to the Zabbix event page instead of the lastest.

server/common/HatoholArmPluginInterfaceHAPI2.cc
The current code doesn't check the return value of publish().
If it fails, this patch logs that.
=> [server] Log an error message on publish() failure.

server/src/RestResourceMonitoring.cc
These values are no longer shown in WebUI dashboard.
So they are unnecessary.
=> [Server] Don't send numberOfItems and nvps for dashboard.

client/static/js/hatohol_events_view_config.js
JQuery attr() with 'checked' only works on JQuery version before
1.5 and 1.6.1 to 1.8. While, prop() is a good alternative, which
works on wide versions.
=> [WebUI] Use prop() instead of attr() for wide JQuery compatibility.

client/static/js/hatohol_server_edit_dialog_parameterized.js
This patch removes the close button on server update/add dialog.
Typically it doesn't take so long. In addition, asynchronous update
sometimes makes users confused.
=> [WebUI][servers] Remoev close button on server update/add dialog.

server/src/RestResourceMonitoring.cc, server/src/RestResourceMonitoring.h
This option is assumed to return only servers with the given
conditions. Currently more than one data has to be gotten to
obtain it.
=> [RestResourceMonitoring] Add a query option: empty=true

server/src/UnifiedDataStore.cc
When a plugin gets an errors, the running state becomes false.
The state cannot be recovered. This patch fixes the issue by
updating the server information.
=> [server] Turn plugin's running state on when updating server information

client/static/js/events_view.js
Previously, severities and incident statuses to be shown, setting
by the base filter, are overritten by the URI's query parameters,
which is typically set by the quick filter.
=> [WebUI][Events] Fix a problem that overwrites base filter settings.

client/static/js/hatohol_item_selector.js
It will take a long time if the zabbix server monitors a lot of
hosts with many items. So this patch get item candidates after the
host is determined.
=> [WebUI][history] Get item candidates after the host is fixed.

client/static/js/overview_triggers.js
Current implementation loads all of the triggers. This may take
a long time. This patch addresses the problem by getting them
after the target server is selected.
=> [WebUI][OverviewTriggers] Load triggers after the server is decided.

client/static/js/hatohol_item_selector.js
(self-monitor) is typically not a target to view history.
Removing it from the selection box makes the UI simple.
=> [WebUI][History] Hide (self-monitor) from the host selection.

server/src/DBTablesMonitoring.cc
syncItem() assumes there is at least one elements in an input list.
Current implementation may cause crash if the list is empty.
This patch avoids the crash by checking the number of elements.
=> [servers] Fix a crash when the number of items is zero.

client/static/js/overview_triggers.js
This is a leak in the following commit.
So this should be merged into it.
commit 00ca77971efbeb50201b86365272828f914c90f2
Date:   Mon Dec 19 21:11:46 2016 +0900
[WebUI][OverviewTriggers] Load triggers after the server is decided.
=> [WebUI][OverviewTriggers] Remove an unnecessary setup.

client/static/js/latest_view.js
Current implementation gets items without any condition. Althogh
the nubmer of items to be obtained is limited, this query might
make the Hatohol server heavy and take a while.
So with this patch, items aren't loaded automatically. By explit
update is need to load items typically after the query conditions
are set.
=> [WebUI][latest_view] Show items on explicit update operation.

client/static/js/overview_items.js
This mistake was included in the following commit.
This patch should be merged into it.
commit 01900200904260fd8b4dd6c663c706d0f5eac2ae
Date:   Mon Dec 19 20:37:41 2016 +0900
[WebUI][OverviewItem] Get item data after the monitoring server is decided.
=> [WebUI][OverviewItem] Fix a wrong indent.

server/src/DBTablesMonitoring.cc
Current value 2048 is sometimes a little short to write a detailed
comment.
=> [server] Increase length of incident_histories.comment by 32767.

server/hap2/Makefile.am
In general, content of a config file is different among plugins.
So we prepare a default config file for each plugin.
=> [hap2] Create conf. file for each plugins.

server/src/ItemFetchWorker.cc
This patch avoids the problem that cannot get items if it's requested
soon after getting items under another server, as written in #2442.
However, it has not been discussed well whether the cache mechanism is
unnecessary or not. So the following variable and the related code
are still remaining.
=> [server][Item] Inactivate the item cache mecanism.

server/src/RestResourceSummary.cc
Unhandled import incidents should include NONE.
Currently behavior including HOLD makes users confused.
=> [server][RetResourceSummary] Exclude HOLD state.

server/src/HostResourceQueryOption.cc, server/test/Helpers.cc, server/test/Helpers.h, server/test/testHostResourceQueryOption.cc
This PR fixes a problem in which the some members in
HostResourceQueryOption aren't copied in the copy
constructor.
=> Work for splitting #2370 fix hostqueryopt

server/src/ActionManager.cc, server/src/ActionManager.h, server/src/DBTablesAction.cc, server/src/DBTablesAction.h, server/src/DBTablesMonitoring.cc, server/src/DBTablesMonitoring.h, server/src/main.cc
This is a revised version of #2471
====
This patch adds a feature that executes unfinished actions
when Hatohol server restarts.
Currently, when the Hatohol server craashes or quits forcely,
running and queued actions aren't taken care on the restart of
Hatohol server.
=> [server][Action] Reexecute action mechanism.

client/test/feature/feature_test_utils.js, client/test/feature/register_action_test.js, client/test/feature/register_log_search_system_test.js, client/test/feature/register_redmine_test.js, client/test/feature/register_server_test.js, client/test/feature/register_user_access_info_test.js, client/test/feature/register_user_roles_test.js, client/test/feature/register_users_test.js
This patch adds an action that opens Settings menu in the navi bar
before clicking an item inside it. Without this operations,
no click event generates on the recent TravisCI.
=> [WebUI][feature-test] Fix failure on TravisCI.

server/src/DataStore.h, server/src/DataStoreFactory.cc, server/src/DataStoreFactory.h, server/src/DataStoreManager.cc, server/src/DataStoreManager.h, server/src/HatoholArmPluginGateHAPI2.h, server/src/HatoholArmPluginGateJSON.h, server/src/ItemFetchWorker.cc, server/src/ItemFetchWorker.h, server/src/RestResourceMonitoring.cc, server/src/TriggerFetchWorker.cc, server/src/TriggerFetchWorker.h, server/src/UnifiedDataStore.cc, server/src/UnifiedDataStore.h, server/test/testDataStoreFactory.cc, server/test/testDataStoreManager.cc, server/test/testHatoholArmPluginGateHAPI2.cc, server/test/testUnifiedDataStore.cc
DataStrore近辺では独自のスマートポインタを使用する必要性がないので, std::shared_ptrを使うほうが将来的にも良いと思うのですが, どうでしょうか?
=> replace UsedCountable of DataStore by shared_ptr

server/mlpl/src/StringUtils.cc, server/mlpl/src/StringUtils.h, server/mlpl/test/testStringUtils.cc, server/src/ArmRedmine.cc, server/src/FaceRest.cc, server/src/GateJSONEventMessage.cc, server/src/HatoholArmPluginGateHAPI2.cc, server/src/IncidentSenderHatohol.cc, server/src/RedmineAPI.cc, server/src/RestResourceMonitoring.cc, server/src/RestResourceServer.cc, server/src/RestResourceUser.cc, server/test/DBTablesTest.cc, server/test/FaceRestTestUtils.cc, server/test/testDBTablesConfig.cc, server/test/testDBTablesHost.cc, server/test/testDBTablesLastInfo.cc, server/test/testDBTablesMonitoring.cc, server/test/testFaceRestCustomIncidentStatus.cc, server/test/testFaceRestIncident.cc, server/test/testFaceRestIncidentTracker.cc, server/test/testFaceRestMonitoring.cc, server/test/testFaceRestServer.cc, server/test/testFaceRestSeverityRank.cc, server/test/testFaceRestUser.cc, server/test/testIncidentSenderRedmine.cc, server/tools/hatohol-def-src-file-generator.cc
StringUtils::toStringはc++11でstd::to_stringとして標準化されているので置き換えました。
=> Replace StringUtils::toString to std::to_string

server/common/Utils.cc, server/common/Utils.h, server/test/testUtils.cc
=> Remove Utils::getCurrTimeAsMicroSecond

server/src/DBTablesMonitoring.cc
未更新のトリガーが「~2017:xx:yy:zz」の条件で検索した時に含まれないように変更した。
#2522
=> [Trigger] Remove unupdate triggers when specified endTime

client/static/js/events_view.js, client/static/js/triggers_view.js
#2523 時間，日付を選択してもウィンドウが閉じないようにした。
=> [js] Does not hide time range window when select date and time

client/Makefile.am, client/static/css/hatohol.css, client/static/js.external/jquery.shiftcheckbox.js, client/static/js/actions_view.js, client/static/js/events_view.js, client/static/js/graphs_view.js, client/static/js/hatohol_hostgroup_privilege_edit_dialog.js, client/static/js/hatohol_incident_trackers_editor.js, client/static/js/hatohol_monitoring_view.js, client/static/js/hatohol_privilege_edit_dialog.js, client/static/js/hatohol_user_roles_editor.js, client/static/js/incident_settings_view.js, client/static/js/servers_view.js, client/static/js/severity_ranks_view.js, client/static/js/users_view.js, client/viewer/base_ajax.html
#2528 の機能追加です.
GmailのようにShift + クリックで範囲選択できるようにしました.
=> Add range select checkbox

client/static/js/events_view.js
#2524 の修正です.
イベント, トリガー画面において"監視サーバー"を選択した際に"ホスト名", "ホストグループ名"がDisabledになるように修正しました.
=> Disabled host name and host group name filter when select server

client/static/css/hatohol.css, client/static/js/triggers_view.js, client/viewer/events_ajax.html
#2527 
htmlの修正をaddし忘れていたので, 追加しました.
=> Integrate default filter html
