client/static/js/hatohol_add_action_dialog.js

[WebUI][AddActionDialog] Make selectable host pull-down menu when ANY is selected in hostgroup pull-down menu

---

server/common/HatoholThreadBase.cc
server/common/HatoholThreadBase.h
server/src/FaceRest.h

Handle exception from FaceRest as fatal event.
Otherwise other thread continue running.

Fatal server error from FaceRest

---

server/src/DBTablesUser.cc
server/src/DBTablesUser.h
server/src/RestResourceUser.cc
server/test/testFaceRestUser.cc

User role update together user info

---

client/static/js/history_view.js

Add a new JavaScript object "HistoryLoader" to make easy to load history of multiple items asynchronously.

Add HistoryLoader

---

server/common/Monitoring.h
server/src/DBTablesMonitoring.cc
server/src/DBTablesMonitoring.h
server/src/RestResourceHost.cc

Exclude triggers of invalid hosts of Triggers and Overview triggers.
Exclude invalid host's trigger from Global status count of the Dashboard.

Exclude triggers of invalid hosts.

---

server/src/DBTablesUser.cc
server/src/DBTablesUser.h
server/src/RestResourceUser.cc
server/src/UnifiedDataStore.cc
server/src/UnifiedDataStore.h
server/test/DBTablesTest.cc
server/test/testDBTablesUser.cc

A part of remaining tasks of issue #890.

[server] Update user's flag by single query with transaction

---

client/static/js/hatohol_user_edit_dialog.js

The last part of fixing issue #890.

[client][WebUI] Adjust selected user role after editing user role in user role edit dialog

---

server/common/Monitoring.h
server/src/DBTablesMonitoring.cc
server/src/DBTablesMonitoring.h
server/src/RestResourceHost.cc

Exclude Items of invalid hosts ,In the same way as Trigger.
From "Overview : Items" and "latest data".
Dealing with isseue#20(https://github.com/project-hatohol/hatohol/issues/20) comments.

Exclude items of invalid hosts.

---

server/test/testFaceRestHost.cc

Need Hosts Table, is reference of Items Tables.
Test failure deal of #942(https://github.com/project-hatohol/hatohol/pull/942) .

Fixed test code in relation to #942.

---

client/static/js/triggers_view.js

[TriggersView] Fix an inappropriate absolute path

---

client/static/js/hatohol_pager.js

This fixes following Webpage Error with Internet Explorer:
| Error: Object doesn't support property or method 'update'

[client] hatohol_pager: Add missing function-local variable self.

---

server/test/testArmZabbixAPI.cc

This pull request adds test for implementation of `updateTriggerExpandedDescriptions`.
Related to issue #326.

[server][test][Zabbix] Add ArmZabbixAPI::updateTriggerExpandedDescriptions test

---

client/test/browser/test_utils.js

`getNickName` is added in #957.

[client][test][Utils] Add getNickName tests

---

client/static/js/triggers_view.js
client/test/Makefile.am
client/test/browser/index.html
client/test/browser/test_triggers_view.js

* Use expandedDescription if available in WebUI
* Add TriggersView browser js test

[client][WebUI][TriggersView] Zabbix macro replacement use expanded info in webui

---

server/common/ZabbixAPI.cc
server/src/ArmIncidentTracker.cc
server/src/ArmRedmine.cc
server/src/IncidentSenderRedmine.cc

Add NULL checks to avoid crash.

Issue 955 fix crash

---

server/common/Monitoring.h
server/src/DBTablesMonitoring.cc
server/src/DBTablesMonitoring.h
server/src/RestResourceHost.cc
server/src/RestResourceHost.h
server/test/testFaceRestHost.cc

* Retrieve trigger.extendedInfo if avaliable.

[server][EventInfo] Zabbix macro replacement in event info

---

client/static/js/events_view.js
client/test/browser/test_events_view.js

* Use expandedDescription if available in WebUI

[client][WebUI][EventsView] Zabbix macro replacement events_view

---

server/common/HatoholArmPluginInterface.cc
server/common/HatoholArmPluginInterface.h
server/src/DataStore.cc
server/src/DataStore.h
server/src/DataStoreNagios.cc
server/src/DataStoreNagios.h
server/src/DataStoreZabbix.cc
server/src/DataStoreZabbix.h
server/src/HatoholArmPluginGate.cc
server/src/HatoholArmPluginGate.h
server/src/ItemFetchWorker.cc
server/src/ItemFetchWorker.h

Add exception handling of Send (Exception occurs when Qpidd is stopped).
Fixed processing of response received.

When Qpid daemon is absent, continue to update the WebUI.

---

server/common/ZabbixAPI.cc
server/common/ZabbixAPI.h
server/hap/HapProcessZabbixAPI.cc
server/hap/HapProcessZabbixAPI.h
server/src/ArmZabbixAPI.cc
server/src/HatoholDBUtils.cc
server/src/HatoholDBUtils.h
server/test/Helpers.cc
server/test/ZabbixAPIEmulator.cc
server/test/ZabbixAPITestUtils.cc
server/test/ZabbixAPITestUtils.h
server/test/testZabbixAPI.cc

This is HAPI version of work replacing Zabbix macro.
* get extendDescription request to HapProcessZabbixAPI
* merge extendDescription into plain information which is gotten HapProcessZabbixAPI
* save merged information into hatohol.triggers entended_info column
* unify implemantation related to Zabbix macro replacement

[Zabbix][HAPI] Zabbix macro replacement

---

client/static/js/hatohol_add_action_dialog.js

[client][AddActionDialog] Fix a bug that unexpectedly changing monitoring server when updating incident setting

---

client/static/js/hatohol_add_action_dialog.js

[WebUI][AddActionDialog] Update incident tracker pulldown menu

---

client/hatohol/forwardview.py
client/viewer/base_ajax.html

* Django 1.5: https://docs.djangoproject.com/en/1.5/ref/request-response/#setting-headers
#979

[client] Add no-cache headers in response

---

hatohol.spec.in
server/data/Makefile.am
server/src/DBTablesConfig.cc
server/src/DBTablesConfig.h
server/test/DBTablesTest.cc
server/test/testDBTablesConfig.cc
server/tools/hatohol-db-initiator
server/tools/hatohol-server-type-util

A part of work related to #672.
* split server_type SQL
* support upsert for `server_types`

[server][tools] Split server types

---

server/tools/hatohol-db-initiator

A part of work related to #672.
* split update target

[server][tools] Split update target

---

client/static/js/triggers_view.js
client/test/browser/test_triggers_view.js

Because users may misunderstood it as problem triggers.

[TriggersView] Don't colorize non-fired triggers

---

client/static/js/events_view.js

And I delete garbage code that was not deleted by me when pull request #1003 .

The auto refresh feature is enabling when press "To next" button.

---

.travis.yml
client/Makefile.am
client/test/python/run-test.sh
server/mlpl/test/run-test.sh
server/test/run-test.sh
server/tools/test/run-test.sh
test/dist-check.sh
test/feature-test.sh
test/launch-hatohol-for-test.sh

* Build at `script` instead of `before_script` to reduce needless build
* Exclude some needless test patterns
* Start slower tests ASAP
* Don't use the make option `-j` for distcheck to try to avoid compiler error

[Travis] Reduce needless build

---

client/test/feature/feature_test_utils.js
client/test/feature/register_action_test.js
client/test/feature/register_incident_setting_test.js
client/test/feature/register_redmine_test.js

* register/unregister Redmine
* register/unregister Incident settings
and some comment and selector etc. fixes for actions.

[client][test][feature] Add feature test incident redmine

---

client/test/Makefile.am
client/test/feature/feature_test_utils.js

[client][Makefile] Add missing EXTRA_DIST files for feature test into Makefile.am

---

client/test/Makefile.am
server/src/Makefile.am

```log
DBTermCStringProvi er.h  ->
DBTermCStringProvider.h
+
```

[distcheck][Makefile] Fix a typo in Makefile.am

---

server/mlpl/src/SmartBuffer.cc
server/mlpl/src/SmartBuffer.h
server/mlpl/test/testSmartBuffer.cc

These patches add features to insert string into an SmartBuffer object.

Mlpl smart buffer ver up 2

---

server/src/DBTablesMonitoring.cc

This just filter removed hosts and passes pseudo hosts
such as self monitoring hosts.

[DBTablesMonitoring] Fix a problem in which pseudo hosts.

---

server/src/ArmBase.cc
server/src/ArmBase.h
server/src/ArmUtils.cc
server/src/ArmUtils.h
server/src/DBTablesMonitoring.cc
server/src/HatoholArmPluginGate.cc
server/src/HatoholArmPluginGate.h
server/src/Makefile.am
server/test/Makefile.am
server/test/testArmUtils.cc

These patches extract similar lines in ArmBase and HatoholArmPluginGate to a new class ArmUtils.

Arm utils 2

---

server/src/ArmIncidentTracker.cc
server/src/ArmIncidentTracker.h
server/src/IncidentSender.cc
server/src/IncidentSender.h
server/src/IncidentSenderManager.cc
server/src/IncidentSenderManager.h
server/src/IncidentSenderRedmine.cc
server/src/UnifiedDataStore.cc
server/src/UnifiedDataStore.h

This pull request is work for #954.

[server][IncidentSender] Get latest incident setting when updating them

---

client/static/js/hatohol_add_action_dialog.js
client/static/js/incident_settings_view.js

インシデント設定にて、
* インシデント管理設定編集のダイアログを開く
* インシデント管理サーバーの編集のダイアログを開く
* インシデント管理サーバー(Redmine)の設定を更新
* インシデント管理サーバーのダイアログを閉じる
の一連の操作を行うと、
インシデント管理サーバーの新しい値にドロップダウンが追従しないバグを見つけました。
そのバグに対する修正のPull Requestです。
ついでに文末のセミコロン漏れがかなりあったのでそちらの修正も行いました。

[WebUI][IncidentSettings] Fix incident setting editor dialog

---

server/src/IncidentSenderManager.cc
server/src/IncidentSenderManager.h
server/src/UnifiedDataStore.cc
server/src/UnifiedDataStore.h

This pull request is a part of the work for #954.

[server][IncidentSenderManager][UnifiedDataStore] Stop incident post thread and arm thread when incident settings is deleted

---

server/src/ConfigManager.cc
server/test/testArmZabbixAPI.cc

[ConfigManager] Fix a bug that loads old events unexpectedly

---

client/Makefile.am
client/hatohol/models.py
client/hatohol/urls.py
client/hatohol/views.py
client/static/css/hatohol.css
client/static/js/graphs_view.js
client/static/js/hatohol_item_selector.js
client/static/js/hatohol_navi.js
client/static/js/history_view.js
client/test/Makefile.am
client/test/browser/index.html
client/test/browser/test_graphs_view.js
client/test/browser/test_hatohol_navi.js
client/test/browser/test_history_view.js
client/test/python/TestGraphsView.py
client/viewer/graphs_ajax.html
client/viewer/history_ajax.html
client/viewer/urls.py
client/viewer/userconfig.py

I added a new table to client's DB because it's UI specific.

[Graph] Enable to save graph settings

---

client/test/feature/feature_test_utils.js
client/test/feature/register_action_test.js
client/test/feature/register_incident_setting_test.js
client/test/feature/register_log_search_system_test.js
client/test/feature/register_redmine_test.js
client/test/feature/register_server_test.js
client/test/feature/register_user_roles_test.js
client/test/feature/register_users_test.js

I added assertions for:
* add/delete operations
Edit assertion and its test are not implemented yet.
And I reduced magic numbers for waiting CSS selectors.

[client][test][feature] Add assertions and more reduce magic numbers for waiting CSS selectors

---

server/common/HatoholArmPluginInterface.h
server/common/Monitoring.h
server/common/ZabbixAPI.cc
server/src/ArmNagiosNDOUtils.cc
server/src/ArmZabbixAPI.cc
server/src/ArmZabbixAPI.h
server/src/DBTablesMonitoring.cc
server/src/HatoholArmPluginGate.cc
server/src/HatoholArmPluginGate.h
server/src/HatoholDBUtils.cc
server/src/HatoholDBUtils.h
server/src/HostInfoCache.h
server/src/RestResourceHost.cc
server/test/DBTablesTest.cc
server/test/DBTablesTest.h
server/test/HatoholArmPluginGateTest.cc
server/test/HatoholArmPluginGateTest.h
server/test/Helpers.cc
server/test/ZabbixAPIEmulator.cc
server/test/ZabbixAPIEmulator.h
server/test/testArmBase.cc
server/test/testArmZabbixAPI.cc
server/test/testDBTablesMonitoring.cc
server/test/testFaceRestHost.cc
server/test/testHapProcessStandard.cc
server/test/testHapProcessZabbixAPI.cc
server/test/testHatoholArmPluginGate.cc
server/test/testHatoholDBUtils.cc
server/test/testHostResourceQueryOptionSubClasses.cc
server/test/testUnifiedDataStore.cc

This is a fix for #1065.
In this patch, the type of host ID was changed to string as well as the other IDs.

Issue 1065 3

---

client/static/js/events_view.js
client/test/browser/test_events_view.js
server/src/RestResourceHost.cc
server/test/testFaceRestHost.cc

I added Zabbix web interface page link to event page, like this:
This pull request is related to #80.

[client][server][EventsView] Generate detail Zabbix web interface event page link

---

client/static/js/servers_view.js
client/static/js/utils.js
client/test/browser/test_events_view.js
client/test/browser/test_utils.js

[Issue 839] Fix wrong link about nagios WebUI

---

client/static/js/hatohol_dialog.js
client/static/js/hatohol_host_selector.js
client/static/js/hatohol_hostgroup_privilege_edit_dialog.js
client/static/js/hatohol_hostgroup_selector.js
client/static/js/hatohol_incident_trackers_editor.js
client/static/js/hatohol_item_remover.js
client/static/js/hatohol_login_dialog.js
client/static/js/hatohol_monitoring_view.js
client/static/js/hatohol_navi.js
client/static/js/hatohol_selector_dialog.js
client/static/js/hatohol_server_bulkupload_dialog.js
client/static/js/hatohol_server_edit_dialog_parameterized.js
client/static/js/hatohol_server_selector.js
client/static/js/hatohol_trigger_selector.js
client/static/js/hatohol_userconfig.js
client/static/js/history_view.js
client/static/js/latest_view.js
client/static/js/servers_view.js
client/static/js/triggers_view.js
client/static/js/utils.js
client/test/browser/test_server_view.js
client/test/browser/test_utils.js

Missing trailing semicolons causes curious problem when JavaScript minifying.
This curious problems only occurs after minifying JavaScript.

[client] Add missing trailing semicolons

---

client/viewer/base_ajax.html

I update copyright year in front end pages.

[BaseAjax] Update copyright year to 2015

---

server/hap/HapProcessCeilometer.cc

Change the type of ID to pass from ArmPlugin(Ceilometer) to "string".

Change the type of the ID to string (HAPI-Ceilometer).

---

server/hap/HapProcessCeilometer.cc
server/hap/HapProcessCeilometer.h

Add the function of draw the graph of the Ceilometer resource item.

Add the graph of the Ceilometer.

---

server/common/Params.h
server/src/ActionManager.cc
server/src/ArmNagiosNDOUtils.cc
server/src/ArmUtils.cc
server/src/ArmZabbixAPI.cc
server/src/DBTablesHost.cc
server/src/DBTablesHost.h
server/src/DBTablesMonitoring.cc
server/src/HatoholArmPluginGate.cc
server/src/HatoholDBUtils.cc
server/src/HostInfoCache.cc
server/src/HostInfoCache.h
server/src/UnifiedDataStore.cc
server/src/UnifiedDataStore.h
server/test/ZabbixAPIEmulator.cc
server/test/testArmBase.cc
server/test/testDBTablesHost.cc
server/test/testHostInfoCache.cc

These patches gives proper global host IDs for triggers and items to be saved.

Set proper global host id 3

---

server/common/Monitoring.h
server/src/DBTablesMonitoring.cc

This Pull Request improve the following points.
- improve performance by using pointer instead of unnecessary deep copy.
- use a readable name.

Brush up update triggers

---

client/static/js/graphs_view.js
client/static/js/history_view.js
client/viewer/graphs_ajax.html

Removed:
* create=true/false
* edit=true/false
Added:
* mode=create
* mode=edit

[HistoryView] Modify query parameters for specifying view mode

---

server/src/ArmNagiosNDOUtils.cc

Modified mismatch of variable type
Modified column specified order.

Fixed collection failure of NagiosNDOUtils.

---

wercker/Dockerfile

It is reasonable to confirm building rpm on Wercker.

[Wercker] building rpm on CentOS 6.x series

---

client/static/js/hatohol_privilege_edit_dialog.js
server/src/DBTablesHost.cc
server/src/DBTablesHost.h
server/src/DBTablesMonitoring.cc
server/src/DBTablesMonitoring.h
server/src/RestResourceHost.cc
server/test/testArmZabbixAPI.cc
server/test/testHostResourceQueryOptionSubClasses.cc

Fix a bug that access control doesn't work

---

server/src/ArmNagiosNDOUtils.cc

issue #1114.
As with ArmZabbixAPI, I will zero padding the event ID of Nagios.

Zero padding the EventID of NagiosNDOUtils.

---

ReleaseNote

RelNote: Fix date of release.

---

ReleaseNote

RelNote: changes for 15.04 by yoshfuji.

---

ReleaseNote

Signed-off-by: Takuro Ashie <ashie@clear-code.com>

ReleaseNote: Changes for 15.03 by Takuro Ashie

---

ReleaseNote

Signed-off-by: Hiroshi Hatake <hatake@clear-code.com>

ReleaseNote: Changes for 15.03 by Hiroshi Hatake

---

server/src/ArmNagiosNDOUtils.cc

[ArmNagiosNDOUtils] Fix a bug that the hostgroup filter doesn't work

---

server/src/ArmNagiosNDOUtils.cc

[server] Avoid registering duplicate hostgroups of Nagios

---

ReleaseNote

* Add an item for issue #1151 
* Fold long lines

15.03 releng/releasenote ashie 2

---

ReleaseNote
server/src/ArmNagiosNDOUtils.cc

issue #1163 
#1168 をrebaseしました。

[ArmNagiosNDOUtils] Avoid registering duplicate items and triggers

---

client/test/feature/dashboard_test.js
client/test/feature/login_logout_test.js
client/test/feature/register_action_test.js
client/test/feature/register_incident_setting_test.js
client/test/feature/register_redmine_test.js
client/test/feature/register_server_test.js
client/test/feature/register_user_roles_test.js
client/test/feature/register_users_test.js

* More remove magic numbers
But I have no idea to do todo about "Registered incident setting assertion", though. :<

[client][test][feature] Use JQuery#on() to wait elements/text appearing

---

server/src/HatoholArmPluginGateJSON.cc

[HatoholArmPluginGateJSON] Fill hostIdInServer

---

client/test/feature/register_action_test.js
client/test/feature/register_incident_setting_test.js
client/test/feature/register_log_search_system_test.js
client/test/feature/register_redmine_test.js
client/test/feature/register_server_test.js
client/test/feature/register_user_roles_test.js
client/test/feature/register_users_test.js

Add following feature tests:
* Edit Action
* Edit Log Search System
* Edit Monitoring Server
* Edit User Roles
* Edit Users
* Edit Incident Tracker Server

[client][test][feature] Add edit feature test

---

server/README.md

* created -> is created
* ~~${prefix}/etc/hatohol/hatohol.conf ->
${sysconfdir}/hatohol/hatohol.conf~~
* ${prefix}/etc/hatohol/hatohol.conf ->
/etc/hatohol/hatohol.conf

[doc] Fix document

---

client/static/js/events_view.js
client/static/js/triggers_view.js
client/test/browser/test_events_view.js
client/test/browser/test_triggers_view.js
server/src/RestResourceHost.cc
server/test/testFaceRestHost.cc

Because we decided to accept any string in it:
https://github.com/project-hatohol/HAPI-2.0-Specification

Use extendedInfo in TriggerInfo & EventInfo directly

---

.travis.yml
server/test/DBTablesTest.cc
server/test/DBTablesTest.h
server/test/Helpers.cc
server/test/Helpers.h
server/test/ZabbixAPITestUtils.cc
server/test/run-test.sh
server/test/testActionManager.cc
server/test/testArmZabbixAPI.cc
server/test/testDBTablesConfig.cc
server/test/testJSONParser.cc
server/test/testMain.cc
server/tools/test/run-test.sh

Enable to run tests without changing directory.

Fix test pathss

---

.travis.yml
server/mlpl/test/run-test.sh
server/test/run-test.sh
test/dist-check.sh
test/feature-test.sh
test/launch-hatohol-for-test.sh
test/run-client-test.sh
test/run-server-test.sh

* Avoid using parallel build to reduce load
* Join some tests to reduce number of builds
https://travis-ci.org/project-hatohol/hatohol/builds/62514289

[travis] Try to avoid unexpected failure

---

server/src/DBTablesLastInfo.cc
server/src/DBTablesLastInfo.h
server/test/DBTablesTest.cc
server/test/testDBTablesLastInfo.cc

* add unique index in `last_info` table
* Allow upsert on duplicate
* Rename `addLastInfo` to `upsertLastInfo`

[server][LastInfo] LastInfo revised

---

server/src/DBTablesLastInfo.cc
server/test/testDBTablesLastInfo.cc

I'll merge it by myself because it a easy fix.

[DBTablesLastInfo] Fix build problems on 32bit environment

---

server/test/Helpers.cc

[server][test] Ensure to read all pending data on reading a pipe

---

server/src/ArmBase.cc
server/src/ArmBase.h
server/src/Closure.h
server/src/DataStore.cc
server/src/DataStore.h
server/src/DataStoreNagios.cc
server/src/DataStoreNagios.h
server/src/DataStoreZabbix.cc
server/src/DataStoreZabbix.h
server/src/HatoholArmPluginGate.cc
server/src/HatoholArmPluginGate.h
server/src/RestResourceServer.cc
server/src/RestResourceServer.h
server/src/TriggerFetchWorker.cc
server/src/TriggerFetchWorker.h
server/src/UnifiedDataStore.cc
server/src/UnifiedDataStore.h
server/test/testArmBase.cc
server/test/testHapProcessStandard.cc
server/test/testHatoholArmPluginGate.cc

Because it's completely same with Signal0 except the name.

[server] Remove a needless template "Signal2" and related codes

---

server/common/HatoholArmPluginInterfaceHAPI2.cc
server/common/HatoholArmPluginInterfaceHAPI2.h
server/src/HatoholArmPluginGateHAPI2.cc
server/src/HatoholArmPluginGateHAPI2.h
server/test/testHatoholArmPluginGateHAPI2.cc

Although it's not completed yet, I want to merge it once because it's already too big...
Known issues:
* Error handling is too weak
* "fetchEvent" isn't implemented yet
* "fetchItems" & "fetchTriggers" don't accept "hostIds" parameter
* "mayMore" parameter isn't handled yet
* "updateHostParent" doesn't support updateType=ALL
* And so on...
I believe it doesn't break existing functions.

Initial implementation of HatoholArmPluginGateHAPI2

---

server/common/HatoholArmPluginInterfaceHAPI2.cc
server/src/HatoholArmPluginGateHAPI2.cc
server/test/testHatoholArmPluginGateHAPI2.cc

[HAPI 2.0] Fix some broken validations

---

server/src/HatoholArmPluginGateHAPI2.cc
server/test/testHatoholArmPluginGateHAPI2.cc

[server][HAPI 2.0] Validate for mandatory JSON parameters 2

---

server/src/DataStore.cc
server/src/DataStore.h
server/src/DataStoreNagios.cc
server/src/DataStoreNagios.h
server/src/DataStoreZabbix.cc
server/src/DataStoreZabbix.h
server/src/HatoholArmPluginGate.cc
server/src/HatoholArmPluginGate.h
server/src/HatoholArmPluginGateHAPI2.cc
server/src/HatoholArmPluginGateHAPI2.h
server/src/ItemFetchWorker.cc
server/src/TriggerFetchWorker.cc
server/test/testHapProcessStandard.cc
server/test/testHatoholArmPluginGate.cc
server/test/testHatoholArmPluginGateHAPI2.cc

* Use plural form
* Fix indent
* Order of arguments
They are trivial fixes so I'll merge it by myself.

[DataStore] Unify style of fetch API

---

server/src/HatoholArmPluginGateHAPI2.cc

[HatoholArmPluginGateHAPI2] Add missing result values

---

server/src/HatoholArmPluginGateHAPI2.cc

[HatoholArmPluginGateHAPI2] Add a warning for fetch API

---

server/src/HatoholArmPluginGateHAPI2.cc

[HatoholArmPluginGateHAPI2] Remove an unused variable

---

server/test/testHatoholArmPluginGateHAPI2.cc

[testHatoholArmPluginGateHAPI2] Fix broken tests in #1246

---

server/src/ItemFetchWorker.cc
server/src/ItemFetchWorker.h
server/src/RestResourceHost.cc
server/src/UnifiedDataStore.cc
server/src/UnifiedDataStore.h

* Use ItemsQueryOption in fetchItemsAsync
* Pass ItemsQueryOption to ItemFetchWorker
* Narrow down candidates for getting target with hostIds

[server][HAPI 2.0] Accept ItemsQueryOption and specify targetHostId in fetchItems

---

server/src/RestResourceServer.cc
server/src/TriggerFetchWorker.cc
server/src/TriggerFetchWorker.h
server/src/UnifiedDataStore.cc
server/src/UnifiedDataStore.h

[server][HAPI 2.0] Accept TriggersQueryOption and specify targetHostId in fetchTrigger

---

server/hap2/haplib.py

This patch defines a file and defines some constants in it.

haplib: a HAPI plugin framework based on python.

---

server/src/HatoholArmPluginGateHAPI2.cc
server/src/HatoholArmPluginGateHAPI2.h
server/test/Helpers.cc
server/test/Helpers.h
server/test/testDBTablesHost.cc
server/test/testDBTablesMonitoring.cc
server/test/testHatoholArmPluginGateHAPI2.cc

* LastInfo
* PutItems
* PutHosts
* PutHostGroups
* PutTriggers
* PutEvents
* PutArmInfo
* PutHostGroupMembership
- Because `syncHostGroupMembers` does not ensure consistency yet.

[server][test][HAPI 2.0] Add DB assertions and related code fixes

---

server/src/HatoholArmPluginGateHAPI2.cc
server/test/testHatoholArmPluginGateHAPI2.cc

[server][test][HAPI 2.0] Add DB assertions to hostgroupMembers and assigning id

---

server/hap2/haplib.py
server/hap2/test/TestHaplib.py

This class provides a framework to run registered callback methods.

Implement a class Callback in haplib.

---

server/hap2/haplib.py
server/hap2/test/TestHaplib.py

This class provides a framework to invoke a method in another
process.

Implemnt a class CommandQueue in haplib.

---

server/src/DBTablesHost.cc
server/test/testDBTablesHost.cc
server/test/testHatoholArmPluginGateHAPI2.cc

Related this comment: https://github.com/project-hatohol/hatohol/pull/1225#discussion_r32903050.
* replace more actual fixture data for PutHostGroupMembership test
* more valid syncing HostGroupMembers

[server][DBTablesHost] More actual fixture PutHostGroupMembership and more valid syncing HostGroupMembers

---

server/src/HatoholArmPluginGateHAPI2.cc
server/test/testHatoholArmPluginGateHAPI2.cc

hostGroupsMembership ->
hostGroupMembership

[HatoholArmPluginGateHAPI2] Fix typo

---

server/src/HatoholArmPluginGateHAPI2.cc
server/test/testHatoholArmPluginGateHAPI2.cc

* Fill some uninitialized members
* Fix a bug that hostIdInServer aren't stored

[HatoholArmPluginGateHAPI2] Fill unintialized members

---

server/src/DBTablesHost.cc
server/src/DBTablesMonitoring.cc
server/test/testDBTablesHost.cc
server/test/testDBTablesMonitoring.cc

* name
* name
* status
* severity
* lastChangeTime
* globalHostId
* hostIdInServer
* hostName
* brief
* extendedInfo
* validity

[server][HAPI2.0] HostName, HostgroupName and Trigger's description changing detection

---

server/src/HatoholArmPluginGateHAPI2.cc
server/src/HatoholArmPluginGateHAPI2.h
server/test/testHatoholArmPluginGateHAPI2.cc

* lastSuccessTime
* lastFailureTime

[HatoholArmPluginGateHAPI2] Allow empty timestamps in putArmInfo

---

server/hap2/simple_caller.py

This utility sends some RPC request such as fetchTriggers and
fetchItems to look at the behaivor of the Hatohol Plugins quickly.

Add a utility for quick testing.

---

server/hap2/simple_server.py

This utility works like as a Hatohol server, receives
RPCs and replay something.

Add a utility for quick testing of RPCs from plugins.

---

server/hap2/standardhap.py
server/hap2/test/TestStandardHap.py

正常系の動作検証のテストしか作成できていません。
各関数のテストは，後で作成し，別PRを送る予定です。

Create a standardhap.py

---

server/src/HatoholArmPluginGateHAPI2.cc
server/test/testHatoholArmPluginGateHAPI2.cc

Follow the change of the specification:
https://github.com/project-hatohol/HAPI-2.0-Specification/issues/47
I'll also modify REST API in another pull request.

[HatoholArmPluginGateHAPI2] Rename "histories" to "samples"

---

server/hap2/hap2_nagios_ndoutils.py
server/hap2/misc/ms-info-ndoutils-example.json
server/hap2/test/TestHap2NagiosNdoutils.py

This patch includes a HAPI 2.0 plugin for Nagios and NDOUtils.

HAPI2.0 Plugin for Naigos and NDOUtils.

---

server/hap2/hap2_ceilometer.py
server/hap2/misc/ms-info-ceilometer.example.json
server/hap2/test/TestHap2Ceilometer.py

This patch includes the plugin, tests, and file used for
the quick interactive test with simple_server.py

New HAPI2.0 Plugin for Ceilometer.

---

server/src/HatoholArmPluginGateHAPI2.cc
server/src/HatoholArmPluginGateHAPI2.h
server/test/testHatoholArmPluginGateHAPI2.cc

[HAPI2][test] Wait HAP connection

---

server/common/HatoholArmPluginInterfaceHAPI2.cc
server/common/HatoholArmPluginInterfaceHAPI2.h

[HAPI2] Add callbacks

---

server/common/HatoholArmPluginInterfaceHAPI2.cc
server/common/HatoholArmPluginInterfaceHAPI2.h
server/src/HatoholArmPluginGateHAPI2.cc

#1318 から、AMQPConsumerの明示的なstop()処理を抽出。
この修正で不要コードを減らせる箇所が一つあったので、最後に自分のコミットを一つ追加。

[HAPI2] Stop AMQPConsumer

---

server/hap2/hap2_fluentd.py
server/hap2/test/TestHap2Fluentd.py
server/hap2/test/hap2-fluentd-tester.sh

This pull request includes a new HAPI plugin.

HAPI2.0 Plugin for Fluentd.

---

.travis.yml

[travis] Install a missing python package for a test of hap2

---

server/hap2/rabbitmqconnector.py

See also.
How to create key and certificate files:
https://github.com/project-hatohol/hatohol/wiki/Log-monitoring

Support SSL connection from HAPI2.0 plugins.

---

server/hap2/haplib.py
server/hap2/misc/ms-info-ndoutils-example.json
server/hap2/simple_caller.py
server/hap2/test/TestHaplib.py

However, validation of some paramters are a little complicated.
They are remaining and will be fixed by 15.09.

Improve validations for RPC requests.

---

server/hap2/hap2_fluentd.py
server/hap2/test/TestHap2Fluentd.py

The pattern is given via a command line option.

Can give the tag pattern for searching the line.

---

server/src/HatoholArmPluginGateHAPI2.cc

[server][HAPI2] Update armInfo onGotResponse

---

server/hap2/hatohol/haplib.py
server/hap2/hatohol/rabbitmqconnector.py
server/hap2/hatohol/standardhap.py
server/hap2/hatohol/test/TestRabbitMQConnector.py
server/hap2/hatohol/test/TestStandardHap.py
server/hap2/hatohol/transporter.py

This PR enables restart of Hap2 plugin when one of the children is
terminated.

Hap2 recover

---

server/common/AMQPConnection.cc

[server][HAPI2] Fix unexpectedly hang when restarting AMQP broker

---

server/src/HatoholArmPluginGateHAPI2.cc

[server][HatoholArmPluginGateHAPI2] Fix missing initialize armInfo

---

server/src/DBTablesMonitoring.cc
server/test/testDBTablesMonitoring.cc

[DBTablesMonitoring] Add missing quote for Trigger ID in deleteTriggerInfo()

---

server/test/testHatoholArmPluginGateHAPI2.cc

[server][test][HatoholArmPluginGateHAPI2] Add assertion to armInfo.stat in ExchangeProfile

---

server/hap2/hatohol/haplib.py

See also.
https://docs.python.org/2/library/sets.html

[hap2][haplib] Use frozenset instead of deprecated type: sets.

---

ReleaseNote

[ReleaseNote] Fix a typo

---

server/common/AMQPConsumer.cc
server/common/AMQPMessageHandler.h
server/common/HatoholArmPluginInterfaceHAPI2.cc
server/src/HatoholArmPluginGateJSON.cc
server/test/testAMQPConnection.cc
server/test/testHatoholArmPluginGateHAPI2.cc

[HAPI2] Retry sending procedure response

---

hatohol.spec.in
setup-with-ansible/Vagrantfile
setup-with-ansible/centos.yml
setup-with-ansible/ubuntu.yml

* always execute `yum update`
* Add devtoolset-2 toolchain installation
* fix hatohol repo URL
* install epel
* install python-argparse with yum 
* pip install packages
- daemon
- pika
* always execute `apt-get update`
* add missing packages installation
* pip install packages
- daemon
- pika
* add functionality to specify number of cores
* add functionality to specify amount of memory

[Ansible] Adopt ansible playbook current dependencies

---

hatohol.spec.in

- This patch can be able cope incase of used all 2.x version python.

Fix spec file

---

server/hap2/hatohol/hap2_zabbix_api.py
server/hap2/hatohol/test/TestHap2ZabbixApi.py

Because, This method get gotten event.

Increment event_id_from

---

server/hap2/hatohol/rabbitmqconnector.py

It corrects the following broken test:
https://travis-ci.org/project-hatohol/hatohol/jobs/70841127

[HAP2] Avoid circular import

---

.travis.yml
server/hap2/hatohol/test/run-test.sh
server/misc/setup-librabbitmq-ppa.sh
server/test/testHatoholArmPluginGateHAPI2.cc
test/run-server-test.sh

* Use librabbitmq 0.5.0 ppa and install: https://launchpad.net/~cosmo0920-oucc/+archive/ubuntu/rabbitmq-c
* Specify `TEST_AMQP_URL`
* Update hap2 test workaround
Related to #1211.

[Travis][server] Start to test AMQP and HatoholArmPluginGateHAPI2

---

server/misc/setup-librabbitmq-ppa.sh

Tidy up for https://github.com/project-hatohol/hatohol/pull/1470.

[server][misc] Add a missing exitcode check

---

client/static/js/servers_view.js

paramArray ->
paramsArrayMap
paramObj ->
paramsArray

[client][servers_view] Rename some variables to represent their actual roles

---

client/static/js.plugins/hap1-zabbix.js
client/static/js.plugins/nagios.js
client/static/js.plugins/zabbix.js
client/static/js/utils.js

They should be escaped at caller side.

[client][plugins] Don't escape URL 

---

client/static/js.plugins/hap2-zabbix.js
client/static/js.plugins/nagios.js
client/test/Makefile.am
client/test/browser/index.html
client/test/browser/test_hap2_zabbix.js

And simplify getTopURL() in nagios.js.
(Remove problematic codes in #1480)

[hap2][client][zabbix] Implement get{Top,Maps,ItemGraph}URL()

---

server/common/AMQPConnection.cc
server/common/AMQPConnection.h

1 [sec] -> 60 [sec]
issue #1425

[AMQPConnection] Lengthen heartbeat check to receive larger data

---

server/common/AMQPConnection.cc

* Always try reconnecting when an error occured
* Ensure to show more information of an error
issue #1425, #1482

[AMQPConnection] Correct error handling of AMQPConnection

---

configure.ac
server/Makefile.am
server/common/Makefile.am
server/src/DataStoreFactory.cc
server/src/FaceRest.cc
server/src/Makefile.am
server/src/RestResourceServer.cc
server/test/DBTablesTest.cc
server/test/Makefile.am
server/test/testDataStoreFactory.cc
server/test/testFaceRestServer.cc

[server] Add configure option to disable HAP1

---

client/static/js/hatohol_graph.js
client/static/js/incident_settings_view.js
client/static/js/utils.js
client/test/browser/test_utils.js

It won't be used anymore.
Use getNickName() instead.
issue #1499

[client] Remove getServerName()

---

server/hap2/hatohol/hap2_fluentd.py
server/hap2/hatohol/test/TestHap2Fluentd.py

This is a revised version of  #1494.
I confirmed the followings.
- All hap2 tests passed.
- status is logged with the given period.

Log status periodically (fluentd).

---

client/Makefile.am
client/static/css.external/jquery.datetimepicker.css
client/static/css/hatohol.css
client/static/js.external/jquery.datetimepicker.js
client/static/js/events_view.js
client/test/browser/test_events_view.js
client/viewer/base_ajax.html
client/viewer/events_ajax.html
server/src/DBTablesMonitoring.cc
server/src/DBTablesMonitoring.h
server/src/RestResourceHost.cc
server/test/testDBTablesMonitoring.cc
server/test/testDBTablesMonitoring.h
server/test/testFaceRestHost.cc
server/test/testHostResourceQueryOptionSubClasses.cc

We are planning to add a time range filter for events to the next version.
So I made a prototype for it.
The page layout will be modified later (until the next release).

[EventsView] Initial implementation of the time range filter

---

server/src/DBTablesAction.h

int -> ActionIdType
uint64_t -> GenericIdType

[server] Use defined types instead of native types.

---

server/src/DBTablesMonitoring.cc
server/src/DBTablesMonitoring.h
server/test/DBTablesTest.cc
server/test/DBTablesTest.h
server/test/testActionManager.cc
server/test/testArmRedmine.cc
server/test/testDBTablesAction.cc
server/test/testDBTablesConfig.cc
server/test/testDBTablesHost.cc
server/test/testDBTablesMonitoring.cc
server/test/testDBTablesMonitoring.h
server/test/testDBTablesUser.cc
server/test/testFaceRestHost.cc
server/test/testFaceRestUser.cc
server/test/testIncidentSenderManager.cc
server/test/testIncidentSenderRedmine.cc

These patches makes built-in test materials immutable in order to
prevent them from being changed by mistake.

Immutable built in test material #1446

---

server/hap2/hatohol/test/TestTransporters.py
server/hap2/hatohol/transporters/__init__.py

This patch replaces the raw numbers with the functions with meaningful names.

[hap2] Improve readability.

---

server/hap2/hatohol/hap.py
server/hap2/hatohol/hap2_ceilometer.py
server/hap2/hatohol/hap2_fluentd.py
server/hap2/hatohol/hap2_nagios_ndoutils.py
server/hap2/hatohol/haplib.py
server/hap2/hatohol/rabbitmqconnector.py
server/hap2/hatohol/standardhap.py
server/hap2/hatohol/transporter.py
server/hap2/hatohol/zabbixapi.py

This pull request enables the plugins to show logging messages with date, time, process ID, module name, and line number.
The following is an example of the new format.
<pre>
2015-08-18 21:52:52,360     INFO [ 3930] hatohol.standardhap:186:  started dispatcher process.
2015-08-18 21:52:52,361     INFO [ 3930] hatohol.haplib:620:  deamonized: 3932 (Receiver)
</pre>

Use logger instead of logging #1453

---

server/hap2/hatohol/hap.py
server/hap2/hatohol/misc/logging.example.conf
server/hap2/hatohol/standardhap.py

This pull request enables user to customize logging destinations and the format by a configuration file.

User logging config fileconfig

---

server/hap2/hap2-control-functions.sh.in
server/hap2/hatohol/rabbitmqconnector.py

This pull request fixed security problem that makes users add a password as a command line option, which can be seen from other people.

Hap2 password by env var #1420

---

server/src/HostResourceQueryOption.cc
server/src/HostResourceQueryOption.h
server/test/TestHostResourceQueryOption.cc
server/test/TestHostResourceQueryOption.h
server/test/testHostResourceQueryOption.cc

The code to building a condition to select hosts is too complicate.
I want to make easy to read before adding new features to it.

[HostResourceQueryOption] Clean up building hosts filter

---

server/hap2/hatohol/hap2_nagios_ndoutils.py

Implement trigger updated option3

---

server/src/ActionManager.cc
server/src/DBTablesMonitoring.cc
server/src/DBTablesMonitoring.h
server/src/IncidentSender.cc
server/src/IncidentSender.h
server/src/RestResourceHost.cc
server/src/RestResourceHost.h
server/src/UnifiedDataStore.cc
server/src/UnifiedDataStore.h
server/test/testDBTablesMonitoring.cc
server/test/testFaceRestHost.cc
server/test/testIncidentSenderManager.cc
server/test/testIncidentSenderRedmine.cc

This modification adds REST API for incident.
Only PUT method (updating an incident) is allowed.

[server] Add REST API for incident

---

server/src/Makefile.am
server/src/StatisticsCounter.cc
server/src/StatisticsCounter.h
server/test/Makefile.am
server/test/testStatisticsCounter.cc

This class provides features store and give statistical information.
We will use it for counting the number of events written in a
certain time.

[server] Add a new class: StatisticsCounter.

---

client/conf/locale/ja/LC_MESSAGES/django.po
client/conf/locale/ja/LC_MESSAGES/djangojs.po
client/static/js/events_view.js
client/test/browser/test_events_view.js
client/viewer/events_ajax.html

The UI for customizing visible columns isn't implemented yet.
I'll add it later.
In addition, I'll also modify the default order of columns later.

[client][EventsView] Add a mechanism to customize visible columns on the events table

---

client/hatohol/models.py
client/hatohol/urls.py
client/hatohol/views.py
client/test/python/TestEventFiltersView.py

It's almost same with graph settings.
So I use a same method to implement them.

[client] Add API to store event filters

---

client/static/js/events_view.js
client/test/browser/test_events_view.js

Default colors will be changed later.
It's the revised version of #1571

[client][EventsView] Colorize all columns

---

client/static/js/hatohol_add_action_dialog.js
client/static/js/incident_settings_view.js
server/src/ArmIncidentTracker.cc
server/src/UnifiedDataStore.cc

Treatment incident hatohol arm incident sender

---

client/conf/apache/hatohol.conf.package6
client/conf/apache/hatohol.conf.package7

The reverse proxy is realized by forwardview.py. The removed lines
has had no effect.

[WebUI] Remove unncessary lines in config. file: ProxyPass.

---

client/static/css/hatohol.css
client/static/js/events_view.js
client/static/js/hatohol_events_view_config.js
client/static/js/hatohol_incident_trackers_editor.js
client/static/js/hatohol_userconfig.js
client/test/Makefile.am
client/test/browser/index.html
client/test/browser/test_events_view.js
client/test/browser/test_hatohol_events_view_config.js
client/test/browser/test_hatohol_incident_tracker_editor.js
client/viewer/events_ajax.html

Revice #1583 
I added UI to define filters.
It's not completed yet.
* "Default filter" setting isn't implemented yet
* No one uses created filters yet.
It's just only create filter settings (JSON) and store them to DB.
Note that this page isn't shown by default.
You can see it by the following query:
http://localhost/ajax_events?devel=true

[client][EventsView] Add UI for creating filter definitions (WIP)

---

server/src/DBTablesMonitoring.cc
server/src/DBTablesMonitoring.h
server/src/RestResourceHost.cc
server/test/testDBTablesMonitoring.cc
server/test/testFaceRestHost.cc
server/test/testHostResourceQueryOptionSubClasses.cc

Example query:
* /event?incidentStatuses=NONE%2CHOLD
Decodeded query part:
* incidentStatuses=NONE,HOLD
I resolved issues in #1595.

[server] Filter events by incident statuses

---

client/conf/apache/hatohol.conf.package6
client/conf/apache/hatohol.conf.package7
client/conf/apache/hatohol.site
client/hatohol/settings_product.py
client/static/js/hatohol_connector.js
client/static/js/hatohol_navi.js
client/test/browser/index.html
client/viewer/base_ajax.html
client/viewer/views.py

These patches enables users to set any WebUI path.
This is a revised version of #1604 and 1606

Brush up production web ui config 3

---

client/static/js/hatohol_user_roles_editor.js
server/src/DBTablesConfig.cc
server/src/DBTablesConfig.h
server/src/DBTablesUser.cc
server/src/OperationPrivilege.h
server/test/DBTablesTest.cc
server/test/testDBTablesConfig.cc

* Add severity rank settings UI into WebUI
* Add severity rank privileges
* constants
* constraint to get severity ranks user defined settings
* Add migration for administrator user privileges

Implement important rate privileges

---

client/static/css/hatohol.css
client/static/js/events_view.js
client/viewer/events_ajax.html

[EventsView] Add clear buttons to time range filter entries

---

server/common/Params.h
server/src/DBTablesConfig.cc
server/src/DBTablesConfig.h
server/src/FaceRest.cc
server/src/Makefile.am
server/src/RestResourceSeverityRank.cc
server/src/RestResourceSeverityRank.h
server/src/UnifiedDataStore.cc
server/src/UnifiedDataStore.h
server/test/DBTablesTest.cc
server/test/Helpers.cc
server/test/Helpers.h
server/test/Makefile.am
server/test/testDBTablesConfig.cc
server/test/testFaceRestSeverityRank.cc

 [SeverityRanks] Implement severity rank REST API

---

client/static/css/hatohol.css
client/static/js/events_view.js
client/static/js/hatohol_events_view_config.js
client/test/browser/test_events_view.js
client/test/browser/test_hatohol_events_view_config.js
client/viewer/events_ajax.html
server/src/DBTablesMonitoring.cc

Default filter:
Filter chooser:

[EventsView] Add default filter config & filter chooser

---

hatohol.spec.in
server/data/Makefile.am
server/data/severity-ranks.sql
server/tools/hatohol-db-initiator.in

Before implementing statistics, we should have a severity_ranks fixture into database.

[HatoholDBInitiator] Add severity-ranks target and sql file

---

server/src/HatoholArmPluginGateHAPI2.cc

This patch makes code simple and removes the dependency of the number
of target types.

[server][HatoholArmPluginGateHAPI2] Use a map instead of simple if statements

---

server/common/Monitoring.h
server/src/DBTablesConfig.cc
server/src/DBTablesConfig.h
server/src/DBTablesMonitoring.cc
server/src/DBTablesMonitoring.h
server/src/DataQueryOption.cc
server/src/DataQueryOption.h
server/src/FaceRest.cc
server/src/IncidentSenderHatohol.cc
server/src/Makefile.am
server/src/RestResourceHost.cc
server/src/RestResourceHostUtils.cc
server/src/RestResourceHostUtils.h
server/src/RestResourceSummary.cc
server/src/RestResourceSummary.h
server/src/UnifiedDataStore.cc
server/src/UnifiedDataStore.h
server/test/testDBTablesConfig.cc
server/test/testDBTablesMonitoring.cc
server/test/testDataQueryOption.cc
server/test/testFaceRestNoInit.cc

* Add `GET /summary/` REST API
* Add event statistics APIs
* DataQueryOption
* Add `groupBy` methods and accessors
* Tidy up parseEventXXX functions
* Move into RestResourceHostUtil
* RestResrouceSummary REST API test
* But tested manually for now

[RestResrouceSummary] Implement event statistics REST API

---

server/test/Makefile.am
server/test/testFaceRestSummary.cc

I implemented RestResourceSummary REST API test.

[RestResourceSummary][test] Implement REST API test

---

client/static/css/hatohol.css
client/static/js.external/jquery.flot.resize.js
client/static/js/events_view.js
client/viewer/events_ajax.html

In narrow window width (< 1000px) environment:
In wide window width (> 1000px) environment:
Related to #1645.

[EventsView] Resize pie chart

---

client/static/js/hatohol_navi.js
client/static/js/severity_ranks_view.js
client/viewer/severity_ranks_ajax.html
client/viewer/urls.py
server/src/RestResourceSeverityRank.cc
server/test/testFaceRestSeverityRank.cc

Currently, only toggle important/not important functionality is available in severity ranks page.

[WebUI][SeverityRanksView] Implement WebUI Severity Ranks Settings

---

client/static/js/events_view.js
client/viewer/events_ajax.html

* Disable "Change treatment" menu when no item is selected
* Add an empty menu item ("----------")

[EventsView] Improve "Change treatment" menu

---

client/static/css.external/spectrum.css
client/static/js.external/spectrum.js
client/static/js/severity_ranks_view.js
client/viewer/base_ajax.html
client/viewer/severity_ranks_ajax.html

* Stop to conceal label and color columns.
* Use spectrum.js for color picker

[WebUI][SeverityRanksView] Make label and color columns editable

---

server/hap2/hatohol/simple_server.py

simple_server.py has not been maintained. So it caused the error
when running with up-to-date haplib and the depending libraries.
This patch makes simple_server work well.

[hap2][simple_server] Follow the up-to-date haplib.

---

server/hap2/hatohol/simple_server.py

These patches fixes some trivial bugs.

Simple server bug fixes

---

client/static/js/events_view.js
server/src/DBTablesHost.cc
server/src/DBTablesHost.h
server/src/RestResourceSummary.cc
server/src/UnifiedDataStore.cc
server/src/UnifiedDataStore.h
server/test/testDBTablesHost.cc
server/test/testFaceRestSummary.cc

* Add counting number of registered hosts
* Fix incorrect algorithm to calculate important event occurred host percentage

[Summary] Fix incorrect summary hosts statistics

---

client/viewer/events_ajax.html

Follow the style of other buttons.

[EventsView] Change the place of an icon on "Apply filter(s)" button

---

client/static/css/hatohol.css
client/static/js/events_view.js
client/viewer/events_ajax.html

[EventsView] Enable to switch the filter for summary view quickly

---

server/common/Params.h
server/src/DBTablesConfig.cc
server/src/DBTablesConfig.h
server/test/DBTablesTest.cc
server/test/DBTablesTest.h
server/test/testDBTablesConfig.cc

* Add upsert/update/get/delete CustomIncidentStatus
* check user's privileges properly

[CustomIncidentStatus][server] Add CRUD operations for custom incident status

---

server/hap2/hatohol/simple_server.py

simple_server is simple implementation of a HAPI 2.0 server.
This pull request improves the following two points.
- Can use logging configuration file
- Terminate children when it finises.

brash up simple_server

---

server/hap2/hatohol/zabbixapi.py

These patches add a framework to parse of the content from Zabbix server in a try block and use it in order to save normal elements instead of the drop of all data
As a side effect, deep indents decreased.

Cleanup zabbixapi

---

client/hatohol/base_settings.py
client/static/js/hatohol_navi.js
client/test/browser/test_hatohol_navi.js
client/viewer/base_ajax.html
client/viewer/views.py

Add a new configuration value "ENABLED_PAGES" to base_settings.py.

[client] Enable to hide navbar items

---

client/static/js/events_view.js
client/test/browser/test_events_view.js

"SeverityRanks" should be loaded before loading events & summary to determine colors of severities.  Revise #1720.

[EventsView] Refine load order

---

client/static/css/hatohol.css
client/static/js/custom_incident_labels_view.js
client/static/js/events_view.js
client/static/js/severity_ranks_view.js
client/viewer/severity_ranks_ajax.html
server/data/severity-ranks.sql

[EventsView] Enable to customize severity labels

---

client/static/css/hatohol.css
client/static/js/hatohol_events_view_config.js
client/viewer/events_ajax.html

[EventsView] Simplify the filter config UI

---

client/Makefile.am

[Makefile][client] Add missing external css and js files

---

server/common/AMQPConnection.cc

Do not use amqp_bytes_malloc_dup.

[server][common][AMQPConnection] Plug a memory leak

---

server/hap2/hatohol/hap2_zabbix_api.py
server/hap2/hatohol/standardhap.py

[standardhap] Remove a unnnecessary import serntece
[hap2_zabbix_api] Fix python grammer

[hap2] Fix some careless misstake

---

client/static/js/events_view.js
client/test/browser/test_events_view.js

Fix a bug which is related to user-defined incident code. ref: https://github.com/project-hatohol/hatohol/pull/1754#issuecomment-159468800

[WebUI][EventsView] Fix undefined map element accessing

---

version-generator.sh

RPM packages have already been uploaded:
https://github.com/project-hatohol/hatohol-packages/tree/master/RPMS/16.01/alpha1

Bump up the version number to 16.01_alpha1

---

client/static/js/triggers_view.js
client/test/browser/test_triggers_view.js

see: https://github.com/project-hatohol/hatohol/issues/1645#issuecomment-152098571
With the following severity settings:
This PR makes triggers page like this:

[TriggersView] Apply user defined table color

---

server/tools/Makefile.am
server/tools/hatohol-house-keeper

Revised #1287.
Related to #1777.
* Refer hatohol.conf and use it

Hatohol house keeper (revised)

---

.travis.yml
server/mlpl/test/testLogger.cc
server/test/Helpers.cc
server/test/testActionManager.cc
test/run-server-test-core.sh
test/run-server-test-misc.sh

These patches fix problems on the new TravisCI infrastructure (since Dec. 2015).
Although we have still the following two problems, I send a PR once because almost all the issues are resolved.
1. Tests with clang still fail.
(@ashie is working on it now and will send the PR.)
2. test_syslogout() sometimes fails.

Support New travis CI

---

client/conf/locale/ja/LC_MESSAGES/django.po
client/conf/locale/ja/LC_MESSAGES/djangojs.po
client/viewer/events_ajax.html

Unify words:
* Config -> Console Setting
* Customize Events View -> Customize Event Console 
and its translations.

[EventView] Unify event console words and translations

---

server/common/AMQPConsumer.cc
server/common/AMQPConsumer.h
server/common/HatoholArmPluginInterfaceHAPI2.cc
server/src/HatoholArmPluginGateHAPI2.cc
server/src/SelfMonitor.cc
server/test/testHatoholArmPluginGateHAPI2.cc

These patch adds a self monitor for AMQP connection.
*******
This is a revised version of #1809.

Error Notification of communication with AMQP Broker. (2nd try)

---

server/src/DBTablesConfig.h
server/src/DBTablesMonitoring.h

[DBTablesMonitoring][DBTablesConfig] Fix typos

---

client/test/browser/index.html
client/test/browser/test_hatohol_modal.js

[HatoholModal] Add HatoholModal browser test cases

---

client/test/browser/index.html
client/viewer/base_ajax.html
client/viewer/latest_ajax.html
client/viewer/triggers_ajax.html

[client][viewer][test] Remove loading stupid table

---

client/Makefile.am
client/static/js/hatohol_connector.js
client/static/js/hatohol_modal.js
client/static/js/hatohol_reconnection_modal.js
client/static/js/hatohol_user_profile.js
client/test/browser/test_hatohol_modal.js
client/viewer/base_ajax.html

With this patch, the modal dialog is shown when a
connection error happens. It also try to reconnect
after a while (currently 30sec. after).
This enables users to notice the error and block
the operation.
***
This is a fixed version of #1842.

[WebUI] Show a modal for connection error.

---

client/conf/apache/django.wsgi
client/hatohol/models.py
client/hatohol/views.py
client/test/python/testsettings.py

Address following issues:
* https://docs.djangoproject.com/en/dev/releases/1.6/#modelform-without-fields-or-exclude
* https://docs.djangoproject.com/en/1.8/releases/1.8/#features-removed-in-1-8
* https://docs.djangoproject.com/en/1.7/releases/1.7/#standalone-scripts
* https://docs.djangoproject.com/en/1.7/releases/1.7/#wsgi-scripts

[client] Support Django 1.8 LTS

---

client/static/js/events_view.js

Sorry, I missed to merge it at #1858.

[EventsView] Fix a bug that invalid tracker IDs are set to all rows

---

hatohol.spec.in

* %{_datadir}/hatohol/sql/actions.sql
* %{_datadir}/hatohol/sql/incident-trackers.sql

[RPM] Add missing files

---

client/static/js/events_view.js

Fix following bugs and simplify the code:
* Labels of severities aren't set to filter menu.
* Values of incidents aren't set to filter menu when they are failed to load.

[EventsView] Fix labels of filter candidates

---

client/static/js/hatohol_reconnection_modal.js

When the added button is pressed, the modal tries to reconnect
soon.

[WebUI][HaotholReconnectionModal] Add a "Retry now" button.

---

client/Makefile.am

We forgot to add the file when it was created.

[WebUI] Add a missing JS in Makefile.am

---

server/hap2/hatohol/zabbixapi.py

[hap2][zabbixapi] Add exception that notices authenticate failure

---

server/hap2/hatohol/hap2_starter.py

[hap2][starter] Fix hap2 starter

---

client/conf/locale/ja/LC_MESSAGES/django.po
client/conf/locale/ja/LC_MESSAGES/djangojs.po

There are still not yet Japanese translated messages.
This PR is adding the translation.

Add Japanese translation as gettext message

---

client/conf/locale/ja/LC_MESSAGES/django.po
client/conf/locale/ja/LC_MESSAGES/djangojs.po
client/viewer/events_ajax.html

Fix config button design in event page

---

client/static/js/custom_incident_labels_view.js
client/viewer/custom_incident_labels_ajax.html

[CustomIncidentSettingsView] Apply same appearance and functionality as SeverityRanksView 

---

server/hap2/hatohol/zabbixapi.py

Related to https://github.com/project-hatohol/hatohol/issues/1926#issuecomment-171171647.

[Hap2][ZabbixAPI] Add malformed response dictionary checking code

---

client/static/js/latest_view.js
client/static/js/triggers_view.js

[TriggersView][LatestView] Fix a bug that changing page size doesn't work correctly

---

server/hap2/hatohol/hap2_zabbix_api.py
server/hap2/hatohol/haplib.py
server/hap2/hatohol/test/TestHap2ZabbixApi.py

[hap2_zabbix_api] Fix to not get old events

---

client/conf/locale/ja/LC_MESSAGES/django.po
client/conf/locale/ja/LC_MESSAGES/djangojs.po
server/tools/hatohol-server-type-util

[client] Add missing Japanese translation

---

client/static/js/hatohol_events_view_config.js

[HatoholEventsViewConfig] Add missing implementation of "Select All" button

---

server/hap2/hatohol/hap2_zabbix_api.py
server/hap2/hatohol/test/TestZabbixApi.py
server/hap2/hatohol/zabbixapi.py

[hap2][zabbixapi] Organize the casting

---

server/hap2/hatohol/test/TestZabbixApi.py
server/hap2/hatohol/zabbixapi.py

[zabbixapi] Fix check_response function

---

doc/server/hap2/how-to-setup-livestatus.md
server/README.md

[hap2][document] Create how to use livestatus module

---

client/static/js/hatohol_item_selector.js
client/viewer/history_ajax.html

[HatoholItemSelector] Fix wrong insert position of newly added item

---

server/common/Monitoring.h
server/common/Params.h
server/src/DBTablesMonitoring.cc
server/src/DBTablesMonitoring.h
server/src/UnifiedDataStore.cc
server/src/UnifiedDataStore.h
server/test/DBTablesTest.cc
server/test/DBTablesTest.h
server/test/Helpers.cc
server/test/Helpers.h
server/test/testDBTablesMonitoring.cc

Revise #1974 (remove changes in RestResourceHost.cc)

[IncidentStatusHistory] Add a DB table for incident status history feature

---

client/static/js/triggers_view.js
client/test/browser/test_triggers_view.js

In triggers view, it should be colorize entire row with user-defined color:

[TriggersView] Colorize entire row when incident occurred

---

server/hap2/hap2-logging.conf
server/hap2/hatohol/hap.py
server/hap2/hatohol/hap2_ceilometer.py
server/hap2/hatohol/hap2_fluentd.py
server/hap2/hatohol/hap2_nagios_livestatus.py
server/hap2/hatohol/hap2_nagios_ndoutils.py
server/hap2/hatohol/hap2_zabbix_api.py
server/hap2/hatohol/haplib.py
server/hap2/hatohol/rabbitmqconnector.py
server/hap2/hatohol/standardhap.py
server/hap2/hatohol/test/TestHaplib.py
server/hap2/hatohol/transporter.py
server/hap2/hatohol/zabbixapi.py

Related: #1982 
Before(streamHandler):
```
INFO:13151:LastStat: OK, NumSuccess: 1 (20160204075926.414961), NumFailure: 0 (): FailureReason: 
```
After(StreamHandler):
```
INFO:hatohol.haplib:hap2_zabbix_api.py:Poller:haplib.py:980:24308:LastStat: OK, NumSuccess: 1 (20160202104706.343966), NumFailure: 0 (): FailureReason: 
```
Before(syslogHandler):
```
haplib.py:1100 [13151]: [INFO] LastStat: OK, NumSuccess: 1 (20160204075926.414961), NumFailure: 0 (): FailureReason:
```
After(syslogHandler):
```
haplib.py:980 hatohol.haplib:hap2_zabbix_api.py:Poller: [24308]: [INFO] LastStat: OK, NumSuccess: 1 (20160202104706.343966), NumFailure: 0 (): FailureReason: 
```

[hap2] Expand hap2 logger

---

client/static/js/triggers_view.js
client/test/browser/test_triggers_view.js
client/viewer/triggers_ajax.html
server/src/RestResourceHost.cc
server/test/testFaceRestHost.cc

Implement time-range filter as `EventsView`'s one like this:
* Leave HatoholPager as-is
* Leave filter behaviour as-is

[TriggersView][WebUI][server] Use time range filter

---

server/test/testFaceRestHost.cc

Fixes: https://github.com/project-hatohol/hatohol/pull/2004#issuecomment-180257242

[server][FaceRestHost][test] Fix a bug which is caused by unintendedly initialized variable

---

client/static/js/triggers_view.js
client/viewer/triggers_ajax.html

I've implemented event page like filter functionality like this:

[TriggersView] Stop to apply filter immediately

---

hatohol.spec.in
server/data/Makefile.am
server/tools/hatohol-db-initiator.in

And not install create-db.sql.
Related: #1415 , #2014

[hatohol-db-initiator][hap2] Replace server type SQL file

---

client/static/js.plugins/hap2-ceilometer.js
client/static/js.plugins/hap2-fluentd.js
client/static/js.plugins/hap2-nagios-livestatus.js
client/static/js.plugins/hap2-nagios-ndoutils.js
client/static/js.plugins/hap2-zabbix.js
client/static/js.plugins/hapi-json.js
client/static/js.plugins/nagios.js
client/static/js.plugins/zabbix.js
client/static/js/hatohol_server_edit_dialog_parameterized.js
client/static/js/utils.js

[WebUI][client] Change the sort of server types

---

client/static/js/events_view.js
client/test/browser/test_events_view.js
client/viewer/triggers_ajax.html
server/tools/hatohol-def-src-file-generator.cc

[client] Add a missing trigger status "TRIGGER_STATUS_UNKNOWN"

---

client/static/js/servers_view.js

[ServersView][Lint] Fix lint errors

---

client/static/js/actions_view.js

[ActionsView][Lint] Use type safe comparison operators

---

client/static/js/utils.js

[client][util][Lint] Fix lint errors

---

client/static/js/hatohol_events_view_config.js

[Lint][HatoholEventsViewConfig] Fix lint errors

---

client/static/js/hatohol_server_edit_dialog_parameterized.js

[HatoholServerEditDialogParametrized] Fix lint errors

---

client/static/js/hatohol_server_bulkupload_dialog.js

[HatoholServerBulkuploadDialog][Lint] Fix lint errors

---

client/static/js/hatohol_incident_trackers_editor.js

[HatoholIncidentTrackersEditor][Lint] Use type safe comparison operators

---

client/static/js/incident_settings_view.js

[IncidentSettingsView][Lint] Fix lint errors

---

client/static/js/custom_incident_labels_view.js

[CustomIncidentLabelsView][Lint] Fix lint errors

---

client/static/js/hatohol_message_box.js

[HatoholMessageBox][Lint] Fix lint errors

---

client/static/js/hatohol_server_edit_dialog_parameterized.js

Follows up https://github.com/project-hatohol/hatohol/pull/2054.
Also related to #2044.

[HatoholServerEditDialogParametrized][Lint] Use function top level var

---

client/static/js/hatohol_pager.js

[HatoholPager][Lint] Fix lint errors

---

client/static/js/hatohol_monitoring_view.js

[HatoholMonitoringView][Lint] Fix lint errors

---

client/static/js/hatohol_history_loader.js

[HatoholHistoryLoader][Lint] Fix lint errors

---

client/static/js/hatohol_dialog.js

[HatoholDialog][Lint] Fix lint errors

---

client/static/js/hatohol_user_edit_dialog.js

[HatoholUserEditDialog][Lint] Fix lint errors

---

client/static/js/hatohol_log_search_system_editor.js

[HatoholLogSearchSystemEditor][Lint] Fix lint errors

---

client/static/js.plugins/hap2-ceilometer.js
client/static/js.plugins/hap2-fluentd.js
client/static/js.plugins/hap2-zabbix.js

[js.plugins][Lint] Fix lint errors

---

client/static/js/hatohol_user_roles_editor.js

[HatoholUserRolesEditor][Lint] Use type safe comparison operators

---

client/static/js/latest_view.js

[LatestView][Lint] Fix lint errors

---

client/static/js/dashboard_view.js

[DashboardView][Lint] Fix lint errors

---

client/static/js/hatohol_user_profile.js

[HatoholUserProfile][Lint] Remove needless trailing semicolons

---

client/static/js/hatohol_privilege_edit_dialog.js

[HatoholPrivilegeEditDialog][Lint] Add trailing semicolons

---

client/static/js/overview_items.js

[OverviewItems][Lint] Fix lint errors

---

client/static/js/overview_triggers.js

[OverviewTriggers][Lint] Fix lint errors

---

client/static/js/severity_ranks_view.js

[SeverityRanksView][Lint] Fix lint errors

---

server/hap2/hatohol/hap.py
server/hap2/hatohol/hap2_ceilometer.py
server/hap2/hatohol/hap2_nagios_livestatus.py
server/hap2/hatohol/hap2_nagios_ndoutils.py
server/hap2/hatohol/hap2_zabbix_api.py
server/hap2/hatohol/standardhap.py
server/hap2/hatohol/transporter.py

And modified standardhap logger name.

[hap2] Remove unneccesarry import sentence

---

client/static/js/hatohol_graph.js

[HatoholGraph][Lint] Use a type safe comparison operator

---

client/static/js/hatohol_connector.js

[HatoholConnector][Lint] Use a type safe comparison operator

---

client/static/js/hatohol_item_update.js

[HatoholItemUpdate][Lint] Add a missing trailing semicolon

---

client/static/js/hatohol_navi.js

[HatoholNavi][Lint] Fix lint errors

---

client/static/js/hatohol_actor_mail_dialog.js

[HatoholActorMailDialog][Lint] Remove needless var quailfier

---

client/static/js/hatohol_password_changer.js

[HatoholPasswordChanger][Lint] Use a type safe comparison operator

---

client/static/js/hatohol_selector_dialog.js

[HatoholSelectorDialog][Lint] Fix lint errors

---

client/static/js/hatohol_time_range_selector.js

[HatoholTimeRangeSelector][Lint] Use a type safe comparison operator

---

client/static/js/users_view.js

Related to #2044.
This is the last PR to pass lint tool which is called in `jshint`! :muscle:

[UsersView][Lint] Fold long lines

---

server/hap2/hatohol/hap2_ceilometer.py
server/hap2/hatohol/hap2_fluentd.py
server/hap2/hatohol/hap2_nagios_livestatus.py
server/hap2/hatohol/hap2_nagios_ndoutils.py
server/hap2/hatohol/hap2_zabbix_api.py
server/hap2/hatohol/haplib.py
server/hap2/hatohol/test/TestHap2Ceilometer.py
server/hap2/hatohol/test/TestHap2Fluentd.py
server/hap2/hatohol/test/TestHap2NagiosLivestatus.py
server/hap2/hatohol/test/TestHap2NagiosNdoutils.py
server/hap2/hatohol/test/TestHap2ZabbixApi.py

Related: #1926
But one problem still exists.
The problem occurs on graph page. 
I will create a new issue which treats it.

[hap2] Separate the putXXX contents by using new function

---

test/run-client-test.sh

Related to #2044.
Let's start to use lint task in client test phase.

[test][client] Execute gulp lint task in client test

---

server/src/IncidentSender.cc
server/src/IncidentSender.h
server/src/IncidentSenderHatohol.cc
server/src/IncidentSenderHatohol.h
server/src/IncidentSenderManager.cc
server/src/IncidentSenderManager.h
server/src/IncidentSenderRedmine.cc
server/src/IncidentSenderRedmine.h
server/src/RestResourceHost.cc
server/test/testFaceRestHost.cc
server/test/testIncidentSenderManager.cc

To track all changes of incidents.
Revise #2113

[server] Save IncidentStatusHitory after creating/updating incidents

---

server/src/DBTablesMonitoring.cc
server/src/DBTablesMonitoring.h
server/test/testDBTablesMonitoring.cc

Related to https://github.com/project-hatohol/hatohol/issues/2118.

[DBTablesMonitoring][TriggersQueryOption] Add triggerBrief option

---

client/static/css/hatohol.css
client/static/js/events_view.js

#1980 【「未対処」が折れ曲がってほしくない】
フロントエンド実装です。

[WebUI:events] Info table Text Nowrap

---

server/common/Params.h
server/src/ActionManager.cc
server/src/HatoholArmPluginGateHAPI2.h
server/test/testHatoholArmPluginGateHAPI2.cc

[ActionManager] Suppress error level log when triggerId is a special ID

---

server/common/Monitoring.h
server/common/Params.h
server/src/DBTablesMonitoring.cc
server/src/DBTablesMonitoring.h
server/src/IncidentSender.cc
server/src/RestResourceIncident.cc
server/src/RestResourceIncident.h
server/src/UnifiedDataStore.cc
server/src/UnifiedDataStore.h
server/test/DBTablesTest.cc
server/test/DBTablesTest.h
server/test/Helpers.cc
server/test/Helpers.h
server/test/testDBTablesMonitoring.cc
server/test/testFaceRestIncident.cc
server/test/testIncidentSenderManager.cc

[server] Rename IncidentStatusHistory to IncidentHistory

---

client/static/css/hatohol.css
client/static/js/events_view.js
client/test/browser/test_events_view.js

#1981 【通知のアイコンが侵入禁止なのに違和感】
フロントエンド実装です。
よろしくお願いします。

[UI:events] Icon Adjustment

---

client/static/css/hatohol.css
client/static/js/events_view.js

#1979 【対処列のチェックマークが想定より大きい場合あり】
フロントエンド実装です。

[WebUI:events] Incident Checkmark Adjustment

---

server/src/HatoholArmPluginGateHAPI2.cc
server/test/testHatoholArmPluginGateHAPI2.cc

[HAPI2.0][server] Add log condition when optional items are omitted

---

client/static/js/hatohol_monitoring_view.js
client/static/js/triggers_view.js
client/viewer/triggers_ajax.html

Add `hostgroup name` beyond monitoring server filter:

[TriggersView][BeyondMonitoringServerFilter] Implement beyond monitoring server filter against Hostgroup name

---

server/hap2/hatohol/hapcommon.py

Previously, we do not have import hap2 module on interactive mode.
If merge this patch, we will become execute it.

[hap2][hapcommon] Add try section that become effective on interactive mode

---

server/hap2/hatohol/hapcommon.py

Reverts project-hatohol/hatohol#2158
Sorry, it breaks the normal case.

Revert "[hap2][hapcommon] Add try section that become effective on interactive mode"

---

server/hap2/hatohol/hapcommon.py

Previously, we do not have import hap2 module on interactive mode.
If merge this patch, we will become execute it.

[hap2][hapcommon] Add try section that become effective on interractive mode

---

client/static/css/hatohol.css
client/static/js/events_view.js
client/static/js/hatohol_events_view_config.js
client/viewer/events_ajax.html

#2006 『イベント画面のサマリエリアを狭くできないか？』
フロントエンド実装です。

[WebUI:events] Summary Relocation

---

client/static/js/hatohol_monitoring_view.js
client/static/js/triggers_view.js
client/test/browser/test_triggers_view.js
client/viewer/triggers_ajax.html
server/src/RestResourceUtils.cc

As usual, trigger briefs is too long to show select box, so I added a restriction which is the number of displaying trigger briefs candidates to 10.

[TriggersView][BeyondMonitoringServerFilter] Implement trigger briefs filter

---

client/viewer/triggers_ajax.html

It becomes more event page like design:

[TriggersView] Fix filter accordion appearance

---

client/static/js/events_view.js
client/viewer/events_ajax.html

[EventsView] Use bootstrap select in accoudion filter selectboxes

---

client/viewer/events_ajax.html

[EventsView] Redesign event config table mock layout

---

server/src/RestResourceIncident.cc
server/test/testFaceRestIncident.cc

Sorry, I forgot to add tests for it...

[RestResourceIncidnet] Fix a bug that can't post comments

---

client/static/js/events_view.js
client/static/js/triggers_view.js

In the previous version sometimes candidates & status aren't
synchronized correctly in some cases.

[EventsView][TriggersView] Make sure to refresh bootstrap-select

---

server/hap2/hatohol/hap2_zabbix_api.py
server/hap2/hatohol/test/TestHap2ZabbixApi.py
server/src/DBTablesHost.cc
server/src/DBTablesHost.h
server/src/FaceRest.cc
server/src/RestResourceMonitoring.cc
server/test/testHatoholArmPluginGateHAPI2.cc
server/test/testHostResourceQueryOptionSubClasses.cc

Related: #2029.
NOTE: This is a revised version of #2194.

Undisplay disabled hosts and trigger (take 2)

---

client/static/js/events_view.js

[EventsView] Don't show .incidentCheckbox when the feature is disabled or conflicts

---

client/static/js/actions_view.js

[ActionsView] Fix a bug that "Status" and "Severity" are shown as "INVALID"

---

client/static/css/hatohol.css
client/static/js/dashboard_view.js
client/static/js/latest_view.js
client/static/js/overview_items.js
client/static/js/overview_triggers.js
client/static/js/triggers_view.js
client/viewer/base_ajax.html
client/viewer/dashboard_ajax.html
client/viewer/events_ajax.html
client/viewer/latest_ajax.html
client/viewer/overview_items_ajax.html
client/viewer/overview_triggers_ajax.html
client/viewer/triggers_ajax.html

* Unify the style of "Last update" label & conatiner (Apply event view's style)
* Add a reload button to all monitoring pages
* Remove "Last Update" label from all settings pages (because they don't have auto reload feature)

[WebUI] Unify the style of "Last update" label & conatiner

---

client/Makefile.am
client/static/js/hatohol_triggers_view_config.js
client/static/js/triggers_view.js
client/test/browser/index.html
client/viewer/triggers_ajax.html

[WebUI] Add settings dialog for triggers view

---

client/static/js/events_view.js

I fogot to remove it at 09bf843.
I'll merge it myself since it's a trivial fix.

[EventsView] Remove needless code

---

client/static/js/events_view.js
client/static/js/hatohol_events_view_config.js
client/test/browser/test_events_view.js

https://github.com/project-hatohol/hatohol/issues/2119#issuecomment-202198354

[WebUI][EventsView] Enable user comment by default

---

client/static/js/events_view.js
client/viewer/events_ajax.html
server/src/DBTablesMonitoring.cc
server/src/RestResourceUtils.cc
server/test/testDBTablesMonitoring.cc

[EventsView] Implement links in the summary bar

---

client/static/js/history_view.js

The other lines in the file doesn't use tabs.
So the point should be expanded.

[WebUI][HisotryView] Expand a tab into spaces.

---

configure.ac
server/common/Makefile.am
server/src/DataStoreFactory.cc
server/src/Makefile.am
server/test/Makefile.am
server/test/testDataStoreFactory.cc
server/test/testFaceRestServer.cc

[server] Change LIBRABBITMQ optional to mandatory

---

server/src/HatoholArmPluginGateHAPI2.cc
server/src/HatoholArmPluginGateHAPI2.h
server/test/testHatoholArmPluginGateHAPI2.cc

Currently, this PR contains naive divideInfo implementation:
* Concatenate divideInfo included JSON records
* Invalid serialId validations
* Timeout mechanism
* Erase invalid temporary multimap elements

[HAPI2.1][server] Implement divideInfo

---

server/hap2/hatohol/hapcommon.py
server/hap2/hatohol/haplib.py
server/hap2/hatohol/test/TestHapCommon.py
server/hap2/hatohol/test/TestHaplib.py

- Add divideInfo to each put procedure

Apply hapi 2.1

---

client/conf/locale/ja/LC_MESSAGES/django.po
client/conf/locale/ja/LC_MESSAGES/djangojs.po
client/static/js/dashboard_view.js
client/viewer/dashboard_ajax.html

Dynamic change dashboard severity label

---

client/conf/locale/ja/LC_MESSAGES/django.po
client/conf/locale/ja/LC_MESSAGES/djangojs.po
server/tools/hatohol-server-type-util

"Retry interval (sec)" in "Monitoring Servers" page isn't translated.

[client] Fix an untranslated label

---

client/static/js/hatohol_add_action_dialog.js
client/static/js/incident_settings_view.js

Dynamic change action dialog severity label and Fix invalid label

---

client/static/js/events_view.js

[client][event_view] Save current page when update incident status

---

server/src/HatoholArmPluginGateHAPI2.cc
server/src/HatoholArmPluginGateHAPI2.h
server/test/testHatoholArmPluginGateHAPI2.cc

Follows up #2245.
* Timeout mechanism
* Currently, it is hardcorded as 90 * 1000 (msec.) = 90 (sec.) = 1.5 (min.) 
* Erase invalid temporary multimap elements
* Testing? (For timeout mechanism)

[HAPI2.1][server] Validations for devideInfo

---

server/src/DBTablesMonitoring.cc

When the multiple item groups (applications) were supported,
the problem in which the returned number of the items is smaller
than that of the request was included.
This patch addresses it by excuting two SQL statements. The first
one just collects the IDs of required items. Then the sencond
one creates ItemInfoList with the IDs.

[Server][DBTableMonitoring] Returns the correct number of items (#2213)

---

server/common/Monitoring.h
server/src/DBTablesMonitoring.cc
server/src/DBTablesMonitoring.h
server/src/HatoholArmPluginGateHAPI2.cc
server/src/UnifiedDataStore.cc
server/src/UnifiedDataStore.h
server/test/Helpers.cc
server/test/testDBTablesMonitoring.cc
server/test/testHatoholArmPluginGateHAPI2.cc

[server] Sync items

---

server/src/IncidentSender.cc
server/src/IncidentSender.h
server/src/IncidentSenderHatohol.cc
server/src/IncidentSenderHatohol.h
server/src/IncidentSenderRedmine.cc
server/src/IncidentSenderRedmine.h
server/test/testIncidentSenderManager.cc

Related to https://github.com/project-hatohol/hatohol/issues/2263.
Cc: @ashie

[IncidentSender] Avoid to record incidentHistory when using Redmine incident server

---

client/conf/locale/ja/LC_MESSAGES/djangojs.po
client/static/js/events_view.js

[client][po] Add Japanese transrations

---

server/hap2/hatohol/haplib.py

We should validate result object if it contains `"FAILURE"`.

[hap2] Validate result dictionary

---

server/hap2/hatohol/standardhap.py

[hap2][tls] Add Sender

---

doc/server/hap2/HowToUse.md
server/README.md

* Add missing 'the' articles
* these package -> these package**s**
* Ubuntu 13.10 -> Ubuntu 13.10 **or later**

[doc] Fix english

---

client/static/js/hatohol_connector.js
client/static/js/history_view.js

Added `connectParam.timeout` option to set timeout value(Unit: milliseconds).

[HatoholConnector][HatoholHistory] Use timeout property in Ajax

---

client/conf/locale/ja/LC_MESSAGES/djangojs.po
client/static/js/events_view.js

[client][js][event_view] Dynamic change events to click sammary button

---

client/conf/locale/ja/LC_MESSAGES/django.po
client/conf/locale/ja/LC_MESSAGES/djangojs.po
client/static/js/hatohol_reconnection_modal.js

How about add `cancel retrying` button into HatoholReconnectionModal?
I'd been annoying the behaviour which is infinite retrying with HatoholReconnectionModal.
This infinite retrying is mainly occurred in graph rendering.

[HatoholReconnectionModal] Add cancel retrying button

---

server/src/HatoholArmPluginGateHAPI2.cc

[HatoholArmPluginGateHAPI2] Ensure running fetch history callback

---

client/static/js/events_view.js

[client][Event] Remove current trigger status

---

client/hatohol/base_settings.py

Before code was causing a FormatError in django.

[client] Fix timezone format

---

doc/server/hap2/HowToUse.md

[doc] Modified a HowToUseHAP2

---

hatohol.spec.in

[spec] Add MySQL-python module into hap2 ndoutils

---

client/static/js/hatohol_history_loader.js

I'll merge it myself because it's a trivial cosmetic fix.

[HatoholHistoryLoader] Fix indent

---

server/hap2/hatohol/zabbixapi.py

[zabbixapi] Consider about $ macro is not digit

---

client/static/js/history_view.js

Reverts project-hatohol/hatohol#2315
Reason: https://github.com/project-hatohol/hatohol/pull/2357#issuecomment-230477149

Revert "[HistryView][WebUI] Prevent doubly requested graph drawing requests"

---

server/hap2/hatohol/test/TestStandardHap.py

A test for hap (StandardHapTestee.test_normal_run)
sometimes failed with the following error.
AssertionError: 'None' != '1 http://example.com:80 0 exampleName Admin examplePass 30 10 exampleExtraInfo'
The root cause is that test code runs
an unexpected path by receiving SIGCHILD due to the exit of
a child process created in a previous test.

Fix a problem that make a test fail. (#1892)

---

client/conf/apache/hatohol.conf.package7

This patch adds some setting for apache in order to enhance security.

[WebUI] Enhancement security for apache.

---

server/log/Makefile.am

This is a leak for fed6b499a911.
So it should be merged(squahsed) in it before the branch is merged
into master.

[server][log] Fix the failure of test/dist-check.sh on TravisCI.

---

server/hap2/hatohol/standardhap.py

[Client] Fix a typo.

---

server/hap2/hap2-logging.conf
server/hap2/hap2.conf.in
server/hap2/hatohol/hap.py
server/hap2/hatohol/hap2_starter.py

WatchFileHandler supports change of the target log file,
which typically happens when logroate is used.

Work for splitting #2370 loglevel refactor

---

server/hap2/hap2-logging.conf
server/hap2/hatohol/hap.py
server/hap2/hatohol/haplib.py

WatchFileHandler supports change of the target log file,
which typically happens when logroate is used.

[hap2] Use WatchFileHandler for logging.

---

hatohol.spec.in
server/hap2/Makefile.am
server/hap2/hatohol/hap2_starter_alive.py

This command line utility returns 0 if the number of running
plugins on the local equals to the expected one with data in
the DB. Otherwise it returns 1, including some troubles.

[hap2] Add hap_starter_alive for monitoring HAPs.

---

client/static/js/events_view.js

[WebUI] Fix typos

---

server/hap2/hatohol/hap2_nagios_ndoutils.py
server/hap2/hatohol/test/TestHap2NagiosNdoutils.py

The commit cd40fc7402c53e has a problem.
This fixes it and should be merged into the commit.

[hap2_nagios_ndoutils.py] Fix problem in cd40fc7402c53e (#2407)..

---

client/static/js/utils.js

[WebUI] Use more suitable word.

---

server/test/README

Test don't need obsolete Qpid.

Remove section of Qpid

---

client/static/js/hatohol_events_view_config.js

- Update interval
- Number of incidents
- Make sure one of the filter conditions is selected
- Add suffix if the same filter name already exists

[WebUI] Add some validations on Events view configuration.

---

client/static/js/hatohol_triggers_view_config.js

- Update interval
- Number of triggers

[WebUI] Add some validations on Triggers view configuration.

---

client/test/browser/test_utils.js

This patch should be merged into 4b11689.

[WebUI] Fix broken tests (#2424).

---

client/test/browser/test_events_view.js

This patch should be merged into 4d7d20c.

[WebUI][test] Fix broken test (#2424)

---

server/test/testFaceRestMonitoring.cc

This patch should be merged into
commit 10dd478
[Server] Don't send numberOfItems and nvps for dashboard.

[test] Fix the bug #2423

---

server/hap2/hatohol/haplib.py

Log the unexpected situation with a parameter.

[haplib] Log error message when the reply wasn't gotten.

---

server/hap2/hatohol/hap.py

This patch should be merged into the following.
commit f1be447faff272cee51cf504fddc9d034a0d10e5
Date:   Wed Nov 23 10:59:50 2016 +0900
[hap2] Renew a mechanism reading a config file.

[hap] Add missing lines.

---

client/viewer/overview_triggers_ajax.html

This patch makes the order be the same as that of latest view.

[WebUI][trigger] Reorder the filter elements.

---

client/viewer/events_ajax.html
client/viewer/triggers_ajax.html

There is an available range and the validation mechanism.
It's better to show the range.

[WebUI] Show range of the parameter values for convenience.

---

client/static/js/events_view.js
client/viewer/events_ajax.html

These patches improves the behavior related to Unhandled important events.

Work for splitting #2370 important evet vis

---

client/static/js/hatohol_events_view_config.js

This is a leak for
commit 45bf8fd8e198265f2e10cdcab2c1b29890ee5f7f
[WebUI] Add some validations on Events view configuration.
and should be merged into it.

[WebUI] Add missing validation for Events view.

---

client/static/js/overview_items.js

Current implementation gets all items at first. This may take a
long time. This patch addresses the problem by delaying items
acquisition.

[WebUI][OverviewItem] Get item data after the monitoring server is decided

---

client/static/js/overview_triggers.js

This patch fixes the problem that may show a wrong severity label.

[WebUI][OverviewTrigger] Fix the severity rank bug.

---

client/viewer/events_ajax.html

This is a leak in 30cc3da521.
However, it should be merged into 3bb439dc1da1.
This patch also should be into it.

[WebUI] A leak of deleting a line.

---

client/static/js/hatohol_monitoring_view.js
client/static/js/latest_view.js
client/static/js/overview_items.js
client/static/js/overview_triggers.js
server/tools/hatohol-def-src-file-generator.cc

Currently there's no way to specify the server which is none of
actual and all ones. This patch makes the query include INVALID_SERVER_ID.

[WebUI] Add overview mode for query with INVALID_SERVER_ID

---

client/conf/locale/ja/LC_MESSAGES/django.po
client/conf/locale/ja/LC_MESSAGES/djangojs.po
client/static/js/before_close.js

This patch merged into the following
commit 0bb46db6c287f80cf01685c3d8a2379679d91d1f
Date:   Tue Dec 20 16:07:01 2016 +0900
[WebUI] Update Japanese translation files.
Similary, the following commit should be merged int the above.
22d902c684af34def45d919deed8ae2249f74451
Date:   Wed Dec 21 13:06:42 2016 +0900
[WebUI] Update last author's name.

[WebUI] Fix the build error for JS po files.

---

client/test/browser/test_latest_view.js
client/test/browser/test_overview_items.js

These commits fix the broken test.
See #2475.

Work for splitting #2370 fix browertest

---

client/static/js/before_close.js

This should be merged into the following commit.
The lint pointed out hat the line is too long
(over 108 characters).
commit 073ba1dba3cc4a66ea82ca71a9c9b855dbdc49f9
Date:   Wed Dec 21 14:08:36 2016 +0900

[WebUI] Fix a lint error.

---

configure.ac
data/init.d/centos/Makefile.am
data/init.d/centos/generate_hap2_init_file.sh.in
data/systemd/Makefile.am
data/systemd/generate_hap2_service_file.sh.in
data/systemd/hatohol.conf
data/systemd/hatohol.conf.in
hatohol.spec.in

This PR update int script including configuration file for each plugin.

Update init scripts for CentOS and systemd.

---

server/hap2/hatohol/hap2_starter.py

This PR includes the following improvements
- correct handle of PID file
- don't exit by SIGINT
- exit if the unexpected situation (child process failed to boot ) happens.

Work for splitting #2370 hap2starter

---

server/hap2/hatohol/rabbitmqconnector.py

[hap2][RabbitMQConnector] Retry on the failure of publish.
This patch adds a feature that retries to publish again on a failure.

Work for splitting #2370 rabbitmq

---

server/hap2/hap2-control-functions.sh.in

This PR fixes some problems in hap2-control-functions.sh.

Work for splitting #2370 ctl func

---

server/hap2/hatohol/rabbitmqconnector.py

This should be merged into the following.
commit 176e663c5dfb9bef81ccf272c04bc80856c746cf
Date:   Thu Dec 22 18:51:12 2016 +0900
[hap2][RabbitMQConnector] Sends heartbeat periodically.

[rabbitmqconnector] Fix a test failure only on TravisCI.

---

server/src/DBAgent.cc
server/src/DBAgent.h
server/src/DBTablesAction.cc
server/src/DBTablesConfig.cc
server/src/DBTablesHost.cc
server/src/DBTablesLastInfo.cc
server/src/DBTablesMonitoring.cc
server/src/DBTablesUser.cc

runTransactionのidが返ってくる引数をポインターから参照に変更しました。

Replace pointer by reference

---

server/common/Utils.cc
server/common/Utils.h
server/test/testUtils.cc

Remove Utils::sum

---

server/common/AMQPConnection.cc
server/common/AMQPConnection.h
server/common/AMQPConsumer.cc
server/common/AMQPConsumer.h
server/common/AMQPPublisher.cc
server/common/AMQPPublisher.h
server/common/HatoholArmPluginInterfaceHAPI2.cc
server/common/HatoholArmPluginInterfaceHAPI2.h
server/src/HatoholArmPluginGateHAPI2.cc
server/src/HatoholArmPluginGateHAPI2.h
server/test/testAMQPConnection.cc
server/test/testHatoholArmPluginGateHAPI2.cc

used countableをshared_ptrに置き換えました

Replace used countable

---

.travis.yml
server/README.md
wercker.yml

werkerの環境をcentos6からcentos7に変更しました.
READMEからcentos6の記述を削除しました.

Bump Centos7

---

.travis.yml
wercker.yml

Clean get number of processor

---

setup-with-ansible/roles/libraries/redhat7/tasks/main.yml

Fix playbook dependencies

---

client/static/js/latest_view.js

#2521 
監視サーバー，ホスト，グループ，アプリケーションなどでフィルターをかけた際にページネーションが0に戻るように変更した。

[latest_view] Return zero page when select host selector

---

client/static/js/hatohol_modal.js
client/static/js/hatohol_reconnection_modal.js

Remove auto reconnection function

---

client/static/js/graphs_view.js
client/static/js/history_view.js
client/static/js/latest_view.js

Open graph new window

---

client/conf/locale/ja/LC_MESSAGES/djangojs.po
client/static/js/events_view.js
client/static/js/hatohol_events_view_config.js
client/static/js/hatohol_triggers_view_config.js

#2527 
サマリバー，イベントリストの2箇所に別れていたデフォルトフィルターを1つに統一した

Integrate filter

---

client/static/js/hatohol_events_view_config.js
client/viewer/events_ajax.html

フィルターリスト内に存在した新規フィルター追加ボタンを外側にし、アイコンで配置した。
#2530

Add add filter button

---

client/static/js/events_view.js

#2525
サマリバーの「全てのイベント」「未対処の重要イベント」「重要イベント」クリック時にajaxで動的に反映するようにした

[event_view] Dynamic change when click summary button

---

client/static/js/hatohol_events_view_config.js
server/src/RestResourceUtils.cc
server/test/testFaceRestMonitoring.cc

#2520
サーバー/ホストグループ/ホストに対してそれぞれ5,30,100ずつの上限を設けた。

Set element limit for each filter

---

setup-with-ansible/roles/build/tasks/main.yml
setup-with-ansible/roles/config/tasks/main.yml
setup-with-ansible/roles/libraries/redhat/tasks/main.yml
setup-with-ansible/roles/libraries/ubuntu/tasks/main.yml
setup-with-ansible/roles/mysql-server/meta/main.yml
setup-with-ansible/roles/mysql-server/redhat/tasks/main.yml
setup-with-ansible/roles/mysql-server/redhat7/tasks/main.yml
setup-with-ansible/roles/mysql-server/ubuntu/tasks/main.yml
setup-with-ansible/roles/rabbitmq-server/meta/main.yml
setup-with-ansible/roles/rabbitmq-server/redhat/tasks/main.yml
setup-with-ansible/roles/rabbitmq-server/ubuntu/tasks/main.yml
setup-with-ansible/roles/run/tasks/main.yml
setup-with-ansible/roles/toolchain/redhat/tasks/main.yml
setup-with-ansible/roles/toolchain/redhat7/tasks/main.yml
setup-with-ansible/roles/toolchain/ubuntu/tasks/main.yml
setup-with-ansible/setup-hatohol-build-and-run.yaml

現状のplaybookはビルド用のパッケージをインストールするだけなので, そこからBuild & Runするplaybookを追加で作りました

Add setup hatohol build and run playbook

---

client/conf/locale/ja/LC_MESSAGES/djangojs.po

[po] Remove verbose wording

---

client/static/js/triggers_view.js

#2524 
トリガー画面も選択時に無効化するようにしました.

[trigger] Disabled host name and host group name filter when select server

---

server/common/HatoholException.h
server/common/ItemData.cc
server/src/DBAgent.h
server/src/DBTablesMonitoring.cc
server/src/ResidentCommunicator.cc

static_assertとenable_ifで代用できるので削除しました.

Remove hatohol build expect

---

server/common/HatoholArmPluginInterfaceHAPI2.cc
server/common/HatoholException.h
server/common/ItemData.h
server/src/Closure.h
server/src/DBTablesConfig.h
server/src/DBTablesUser.h
server/src/HatoholArmPluginGateJSON.cc

add override

---

client/static/js/events_view.js
client/static/js/hatohol_user_roles_editor.js
client/static/js/severity_ranks_view.js

インシデント管理サーバーにRedmineが入った時にテーブルヘッダがずれるのを修正.

Fix show and hide targets
